### ISSUE TITLE
Add OpenAPI support to QuickStart MP

### ISSUE THREAD

**Issue by m0mus** [helidon-io/helidon#1190]
It would be nice to add `OpenAPI` annotations to our QuickStart MP application and make sure that it's testable in Swagger UI.

**Comment by tomas-langer** [comment]
This is already part of quickstart. @m0mus could you please confirm (and close) if the current state is OK?

Thanks

**Comment by tjquinno** [comment]
The OpenAPI document is valid, and therefore the swagger tools work. But there is only one method--`updateGreeting`-- on `GreetingResource` which has relatively complete full MP OpenAPI annotations. The other methods, the gets, have no OpenAPI annotations at all so the information in the OpenAPI document is minimal.
