### ISSUE TITLE
DB Client: Fix get prototype in DbExecute interface

### ISSUE THREAD

**Issue by Tomas-Kraus** [helidon-io/helidon#1326]
## Environment Details
* Helidon Version: 2.0-SNAPSHOT
* Helidon SE
----------
## Problem Description
API inconsistency in `io.helidon.dbclient.DbExecute` interface
```
    default OptionalCompletionStage<DbRow> namedGet(String statementName, Object... parameters)
```
vs.
```
default CompletionStage<Optional<DbRow>> get(String statement, Object... parameters)
```
Both methods shall return `OptionalCompletionStage<DbRow>`

**Comment by Captain1653** [comment]
Looks like this issue is already done in [this PR](https://github.com/helidon-io/helidon/pull/1828/files#diff-3f4240f1e6098d3ce2a049a9743890b14a3358e308cb9412dd83924d1f3b5158).

Should it be closed?
