### ISSUE TITLE
Simplify adding *-image profile configuration

### ISSUE THREAD

**Issue by batsatt** [helidon-io/helidon#1391]
Given that the profile declarations are in the `helidon-se` or `helidon-mp` parent poms, adding configuration in the application pom is either verbose or somewhat ugly.

The ugly solution is to use global properties with fully qualified names, e.g.
``` 
<native.image.buildShared>false<\native.image.buildShared>
```

The more natural solution is to use a configuration element:
```
<configuration>
    <buildShared>false<\buildShared>
<\configuration>
```
The only way I know to add that configuration and retain the profile behavior is by duplicating the parent `<profile>` declaration. Hopefully there is a less verbose way to do this.

**Comment by romain-grecourt** [comment]
If you have a profile like this:
```xml
    <profiles>
        <profile>
            <id>native-image</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.helidon.build-tools</groupId>
                        <artifactId>helidon-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>native-image</id>
                                <goals>
                                    <goal>native-image</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
            <dependencies>
                <dependency>
                    <groupId>io.helidon.integrations.graal</groupId>
                    <artifactId>helidon-graal-native-image-extension</artifactId>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
```

You can override the configuration per execution like this:
```xml
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>io.helidon.build-tools</groupId>
                    <artifactId>helidon-maven-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>native-image</id>
                            <configuration>
                                <finalName>foo</finalName>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
```

**Comment by batsatt** [comment]
I see; yes, that works. Unfortunately, though, IntelliJ doesn't understand that idiom enough to provide any completions for the supported configuration options. I find those so useful that in my local project I would just copy the `<profile>`.

**Comment by batsatt** [comment]
So with the current version of IntelliJ, even adding the goal doesn't cause completions to work. This is really frustrating, as it is vastly easier to add configuration when the IDE helps!

**Comment by spericas** [comment]
Would most of the use cases be covered by using some properties in the configuration that poms can override? Something like `surefire.argLine`?

**Comment by batsatt** [comment]
We won't get completions, but you can already just set properties in the pom; this is certainly the easiest thing to document.

**Comment by batsatt** [comment]
So, for example, you can just add:
```
<properties>        
    <jlink.image.addClassDataSharingArchive>false</jlink.image.addClassDataSharingArchive>
</properties>
```
to your pom rather than the entire `pluginManagement` block. This works for every property that is specific to the plugins because the names are global. The `pluginManagement` block would still be required for things like `project.build.finalname` because the names aren’t specific enough.

**Comment by romain-grecourt** [comment]
In the example above, is that property pre-configured in the parent pom for the plugin execution or is it the property mapping of the mojo itself ?

**Comment by batsatt** [comment]
The mojo itself.

**Comment by romain-grecourt** [comment]
Using mojo-mapped configuration properties means we have to point people at our plugin documentation.

The parent pom could be self-documenting if the properties that user can override or set are all declared in it.

**Comment by batsatt** [comment]
Yes, we could do that as well, although you obviously have to navigate to the parent to see them. 

We still need our docs to point at something that describes each property, though; Joe's new docs point at the plugin docs for this.

**Comment by tomas-langer** [comment]
As we have switched to the maven plugin of graalvm native image, I am closing this issue.
Please create a new one if there is an issue for the new approach.
