### ISSUE TITLE
Some of the tests are failing if default port (7001) is already in use

### ISSUE THREAD

**Issue by aseovic** [helidon-io/helidon#1433]
## Environment Details
* Helidon Version: 1.4.1
* Helidon SE or Helidon MP: both
* JDK version: any
* OS: any
* Docker version (if applicable):

----------

## Problem Description
A number of tests are failing if port 7001 is in use when building Helidon, as they either don't specify the port or specify -1 as port number, which ends up using the default port (7001). Considering that this is the default port Helidon uses, this issue is very easy to hit when *using* Helidon to write custom applications and *working* on Helidon itself at the same time.

All the tests that start the server should explicitly specify port 0 in order to bind to an ephemeral port instead, which reliably eliminates the issue.

## Steps to reproduce
Start any server on port 7001.
Try to build Helidon using `mvn clean install`

**Comment by tomas-langer** [comment]
We will not fix this in 1.x
This should be resolved in 2.x and newer versions of Helidon. If not, please create a new issue (ideally with the test that fails).
We cannot do this for TCK tests, as they must run on a predefined port (`8080`)
