### ISSUE TITLE
Supporting XML processing in a fashion similar to JsonSupport

### ISSUE THREAD

**Issue by gcameo** [helidon-io/helidon#1561]
## Environment Details
* Helidon Version: 2.0.0-M1
* Helidon SE
* JDK version: 14
* OS: Docker
* Docker version (if applicable):

----------
Helidon has lots of JSON processing support via JsonSupport and JacksonSupport but I can't find an example of how to process an inbound XML data through HTTP Body - possibly unmarshalling via Jaxb. I am currently converting it to String but that is not very efficient and wastes memory.

Is there an efficient way to do this? Does the new MultiPart feature in Helidon 2 support this?

Rgds

**Comment by tomas-langer** [comment]
XML processing is not planned for Helidon. You can write your own writers/readers for Helidon SE (source code for JSON-P and JSON-B is available as part of this repo).
For Helidon MP, you can use Jersey support for XML.

**Comment by romain-grecourt** [comment]
To clarify this issue is to provide readers / writers based of STAX and JAXB for Helidon SE.

**Comment by gcameo** [comment]
Yes, That is correct so I can use "Handle.create" method to receive a mapped Java object in my handler method.
