### ISSUE TITLE
Enhancement: Can Helidon examples moved to a separate repository?

### ISSUE THREAD

**Issue by ksurendra** [helidon-io/helidon#1854]
Can Helidon examples moved to a separate repository so the platform "core" is seprate

**Why?**
1. This will be helpful for contributors to submit PR's. As of now we have to FORK the entire repo with core and examples.
2. Merging to a respective folder may become simpler

**Challenges:**
1. Most examples depend on parent pom's, moving them out to separate folder may pose challenges with build failures. 
2. Standalone examples like [helidon-standalone-quickstart-mp](https://github.com/oracle/helidon/tree/master/examples/quickstarts/helidon-standalone-quickstart-mp) will work fine.

This will be helpful for contributors

**Comment by romain-grecourt** [comment]
This is something that we do have in scope.

Currently the examples that inherit an "application parent pom" must reference it using `<relativePath>` and indeed these examples cannot be moved or extracted as-is without updating the `<relativePath>`.

If we do move the examples, the development work will have to be carried out in branches where the version is a SNAPSHOT version for the corresponding Helidon version. Building the examples will still requires a local build of Helidon unless we deploy SNAPSHOT regularly to a remote maven repository (also in scope).

Tags will offer fully functional examples, each of them being properly self-contained.
We can decide to merge the latest tag in master in and do the development work in branches named "dev" and "1.x".

**Comment by ksurendra** [comment]
I agree @romain-grecourt (and i've also noted some challenges). This was an observation and can be a back-burner and can be addressed when this may become a problem as Helidon platform/community grows.

**Comment by barchetta** [comment]
This has been completed for Helidon 3. After a little soak time we will do it for Helidon 4.

- https://github.com/helidon-io/helidon/pull/8437
- https://github.com/helidon-io/helidon/pull/7889
- [Helidon 3 Examples](https://github.com/helidon-io/helidon-examples/tree/helidon-3.x)

We will use #5887 to track work for Helidon 4
