### ISSUE TITLE
Webserver fluent path params processing

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#1867]
Follow up from #1217 

As proposed by @romain-grecourt :
Process path params using fluent style (`Optional` instead of plain types).

**Comment by romain-grecourt** [comment]
Fixed in Nima.

E.g.

```java
req.path()
   .pathParameters()
   .first("foo")
   .map(Integer::parseInt)
   .orElse(0);
```

This also works for query parameters:

```java
req.query()
   .first("foo")
   .map(Integer::parseInt)
   .orElse(0);
```
