### ISSUE TITLE
Issuer validator should accept List of String as possible issuers

### ISSUE THREAD

**Issue by abhishek-mvr** [helidon-io/helidon#2075]
Issuer validator should be able to validate against multiple possible jwt issuers. This would benefit when integrating to multiple services.

https://github.com/oracle/helidon/blob/c0f4a86acde11d33e593bb88c8d5f0ddcf99d82f/security/jwt/src/main/java/io/helidon/security/jwt/Jwt.java#L408

**Comment by barchetta** [comment]
Also, see this issue from `java-jwt`: https://github.com/auth0/java-jwt/issues/246

**Comment by tomas-langer** [comment]
Issuer validator is validating a token against a single issuer (the one that our configuration is created for) - an issuer is mapped to either an endpoint (metadata), or `jwk`  to validate  a signature (or to decrypt).

So what I understand from this is that we want to choose an OIDC provider (JWT configuration) based on the issuer in the JWT.
This could be achieved through our new multitenancy support in OIDC, where the tenant finder would choose tenant id from the JWT issuer (would cause double parsing of the token).
We may want to consider this use case when selecting the correct OIDC configuration for validation.

@Verdent FYI

**Comment by tomas-langer** [comment]
We are currently investigating this issue. 
This is basically a request for federation. We are looking into the possibilities of achieving this with third party tools (such as Keycloak) and integration with Helidon through existing means (OIDC). 
We have a workaround (using multiple providers in sequence, until one that can authenticate is found) - this is not the most efficient way of solving this problem, but it should work (as issuer would fail validation very quickly, so there will be no network traffic involved for providers that do not match it).

After our investigation, we will decide how to treat this issue (enhancement request, guide, workaround).

**Comment by tomas-langer** [comment]
The referenced issue (really) mentions support for an array of issuers as a claim in JWT (as @Verdent noticed).
This fix would be quite easy, nevertheless I do have issues with it:
If a JWT defines multiple issuers, what does it mean?
- Are these aliases for the same issuer?
- Are these issuers sharing private keys (please do not do this) and provide replaceable tokens?

Also the JWT specification clearly states that `iss` claim is a single string, not an array:
https://www.rfc-editor.org/rfc/rfc7519#section-4.1.1

**Comment by tomas-langer** [comment]
@barchetta could you please go through my comments and provide feedback?

**Comment by barchetta** [comment]
@tomas-langer  I'm no expert here, but the use case where  multiple issuers are aliases is mentioned in the discussion of the referenced issue. This seems like a reasonable use case to address (and a simple one based on your comments?). I think that, combined with the multitenancy enhancement would cover this issue.

**Comment by tomas-langer** [comment]
OK. 
We will go with this "easy" fix, even though it is against the spec.
