### ISSUE TITLE
Consider using System.getLogger

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#2174]
We are currently using Java Util Logging methods to obtain a `Logger` instance.
We could switch to `System.getLogger` that uses a service loader (to support third party implementations), using JUL as the default implementation.

Just by switching to `System.getLogger`, we could simplify replacing of logging implementation for our users

**Comment by Captain1653** [comment]
Is this issue similar to https://github.com/helidon-io/helidon/pull/5936 ? I can try to do it for 2.x or 3.x
