### ISSUE TITLE
Support Time-based Sliding Window Reservoir in Helidon Histogram

### ISSUE THREAD

**Issue by Clara9** [helidon-io/helidon#2191]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 1.4.5
* Helidon SE
* JDK version: 1.8.0_252
* OS: Linux
* Docker version (if applicable): 19.03.1

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
Hi we are looking at the implementation of histogram in Helidon timer. Currently histogram uses exponentially decaying reservoir for sampling, which puts more recent data into sampling. However, we noticed that there are usually some outdated values used for calculation every time when calling /metrics. Please consider adding an alternative implementation using sliding time window array reservoir which only keeps samples from past N seconds in a fixed size M reservoir.
It would be nice if histogram in timer can support both reservoir implementations, and would also be convenient if users can specify the value of N and M when creating a new instance of timer. 
Reference: https://metrics.dropwizard.io/4.1.2/manual/core.html#histograms

**Comment by tomas-langer** [comment]
Fix notes:
look at future of MicroProfile Metrics to see if such problem is addressed in the spec. If so, align with the future MP spec, otherwise use Helidon specific configuration.

**Comment by tjquinno** [comment]
Beginning with Helidon 4 we are layering Helidon's neutral metrics API on other implementations, such as Micrometer. As a result, we layer on the features in specific meter types present in the underlying implementation layer, including histograms (distribution summaries as Micrometer calls them).

As such, Helidon no longer provides its own implementation.
