### ISSUE TITLE
Doc: MP JPA/JTA updates for 2.0.x

### ISSUE THREAD

**Issue by ljamen** [helidon-io/helidon#2201]
## Environment Details
* Helidon Version: 2.0.x
* Helidon MP

----------

## Problem Description
Need to include additional content for MP JPA/JTA documentation. 
Specifically,
How to access databases
What is JPA 
What is JTA
How to configure it
Use cases

## Steps to reproduce
Existing doc is here:
https://helidon.io/docs/v2/#/mp/jpa/01_introduction

**Comment by i-am-nemo** [comment]
Hi Team,

I want to work on this. How to proceed ?

Thanks,
Sudip
