### ISSUE TITLE
Documentation Helidon MP: Maven command does not create ExampleResource

### ISSUE THREAD

**Issue by tvallin** [helidon-io/helidon#2608]
The Helidon MP Data Source Guide ask to update ExampleResource class but this class is not present into the sample project.
There is instead GreetResource class.

REPRODUCER:
```
mvn -U archetype:generate \
    -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-bare-mp \
    -DarchetypeVersion=2.1.1-SNAPSHOT \
    -DgroupId=io.helidon.example \
    -DartifactId=helidon-ds \
    -Dpackage=io.helidon.example.ds \
    -DrestResourceName=ExampleResource \
    -DapplicationName=ExampleApplication  
```

NOTE:
- The parameter `-DrestResourceName=ExampleResource` does not "rename" the GreetResource. But following the guide with GreetResource instead of ExamplesResource works perfectly fine.
- Is it useful to keep `-DapplicationName=ExampleApplication` as it is not used ?

**Comment by ljnelson** [comment]
Thanks for the report.  I just [recently updated some related documentation](https://github.com/oracle/helidon/pull/2570) and I think I missed this.  I'll assign it to myself.

**Comment by Captain1653** [comment]
Is it issue still valid? I tried to find it in the docs, but I couldn't.

**Comment by ljamen** [comment]
@ljnelson I think this can be closed now. I see the changes in your other PR.
