### ISSUE TITLE
Rest client does not properly add headers from ClientHeadersFactory

### ISSUE THREAD

**Issue by Verdent** [helidon-io/helidon#2739]
This issue will be fixed whenever we update jersey dependency in Helidon, which contains fix for the following issue. [Jersey #4715](https://github.com/eclipse-ee4j/jersey/issues/4715)

It is not needed to be added to the Backlog project.

**Comment by Captain1653** [comment]
[Jersey issue](https://github.com/eclipse-ee4j/jersey/issues/4715) was fixed in [version 2.34](https://github.com/eclipse-ee4j/jersey/pull/4724).

Helidon 4.x has jersey 3.1.5
Helidon 3.x has jersey 3.0.12
Helidon 2.x has jersey 2.41

Should this issue be closed?
