### ISSUE TITLE
Use com.sun.activation:jakarta.activation instead of jakarta.activation-api

### ISSUE THREAD

**Issue by lukasj** [helidon-io/helidon#2770]
## Environment Details
* Helidon Version: 2.2.1
----------

## Problem Description
Helidon currently removes `jakarta.activation` artifact from all its dependencies and uses `jakarta.activation-api` artifact instead. Problem with this is that the `-api` artifact contains no implementation and whoever depends on it may get unexpected behaviour due to missing functionality. Also note that `jakarta.activation-api` artifact may not be able to start properly on JPMS/OSGi due to missing implementation classes (that's activation's problem to be solved in that project).

**Comment by tomas-langer** [comment]
Use Angus activation as the implementation
Upgrade activation API to the latest version

**Comment by barchetta** [comment]
In 4.0 it appears as though we can remove almost all dependency on jakarta.activation. See PR #6138. I still need to investigate 3.x.

**Comment by barchetta** [comment]
With the latest PRs we have, for the most part, removed the dependency on jakarta.activation-api from Helidon 2, 3 and 4.  With that I think this issue no longer applies so I'm closing it.
