### ISSUE TITLE
Provide transition module for java/jakarta.activation

### ISSUE THREAD

**Issue by lukasj** [helidon-io/helidon#2771]
## Environment Details
* Helidon Version: 2.2.1

----------

## Problem Description
External libraries being migrated from JDK 8 to JDK 11 may have dependency on `java.activation` JPMS module buried somewhere deep in their dependency tree. To help these libraries move to Helidon 2.x and JDK 11, it may be useful to provide transition module, ie something having just following module-info with appropriate maven dependency defined:

```module-info.java
module java.activation {
    requires transitive jakarta.activation;
}
```

**Comment by barchetta** [comment]
We don not plan on addressing this.
