### ISSUE TITLE
Add media-support unmarshalling to TestResponse

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#3061]
`io.helidon.webserver.TestResponse` only supports unmarhalling to `byte[]` and `String` ; add support for 
media support unmarshalling with a method `as(Myclass.class)`.

This can be done by re-using `io.helidon.media.common.MessageBodyReadableContent`.

**Comment by tomas-langer** [comment]
This is fixed in 4.x and will not be backported to older versions.
We no longer have test client, we can use full client for testing routing in 4..
