### ISSUE TITLE
OCI Integration with Metrics/Monitoring

### ISSUE THREAD

**Issue by arjav-desai** [helidon-io/helidon#3137]
Validate we can easily add Metrics to OCI integration and write a short guide.

The idea is that metrics from helidon application should be sent to OCI metrics/monitoring service.

**Comment by klustria** [comment]
https://github.com/helidon-io/helidon/pull/4003 can also be used for SE hence closing this issue. I will use this bug to port issue 4003 to helidon 3.x and later versions.
