### ISSUE TITLE
How to enable h2 console in Helidon, similar to Spring property "spring.h2.console.enable=true"

### ISSUE THREAD

**Issue by ramakantharao** [helidon-io/helidon#3141]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version:
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

**Comment by barchetta** [comment]
Helidon does not currently support this.

Digging a little deeper it looks like the H2 Console can be run stand-alone or embedded using its servlet web application `org.h2.server.web.WebServlet`. I'm guessing the Spring support is done via this servlet.

Helidon does not support Servlet, so things get more complicated. Some possibilities:

* Write a Helidon integration that wraps `org.h2.server.web.WebServer` -- essentially performing the same role as H2's `WebServlet`. Unfortunately it looks like not all the H2 web APIs needed to do this are public.
* Write a Servlet shim with just-enough-servlet to use H2's `WebServlet`.  This is a bit gross and starts down a path we don't want to head (supporting Servlet), but would mean we only depend on stable, public APIs.
*  Contribute some alternative to H2's `WebServlet` to the H2 project. Maybe a JAX-RS resource? Or some other higher level delegating class?

**Comment by dansiviter** [comment]
@ramakantharao:

```java
@ApplicationScoped
public class H2Producer {
  private Server server;

  public void init(@Observes @Initialized(ApplicationScoped.class) Object o) throws SQLException {
    this.server = Server.createWebServer("-webPort", "8082").start();
  }

  @PreDestroy
  public void destroy() {
    server.stop();
  }
}
```

**Comment by Captain1653** [comment]
This issue is answered and quite old. 

Should it be closed?
