### ISSUE TITLE
Grpc creates new config where it should not

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#3288]
JavaMarshaller - line 54 uses `Config.create()` 
This is not a good practice, as it may produce unexpected configuration object (or even throw an exception).

Configuration must be moved somewhere else (either through builder/create method, or if that is not possible, this must switch to a system property/env var approach - may even use config for that, but with an explicitly built instances with no other sources).

Another option would be to use a shared config instance, if we decide to have such available in Helidon.

**Comment by tjquinno** [comment]
The affected class was deprecated as of 2.3.0 and has been removed in 3.x and 4.x. Tomas agrees that we should just leave this alone. None of the fixes (using a builder, restricting to env variables or properties, etc.) would be backward-compatible in upcoming 2.x releases.
