### ISSUE TITLE
end-to-end support for HTTP/2

### ISSUE THREAD

**Issue by FWiesner** [helidon-io/helidon#3304]
Let me write it as user story...

As developer of a HelidonSE-based service that offers REST APIs to user experiences like Oracle Visual Builder Cloud Service I would like to improve the overall page performance by leveraging productised HTTP/2. As my service performs downstream calls for each incoming request, I also need this performance improvement for the Helidon WebClient that I use. In a typical scenario my service is invoked per item in a list view. As this quickly leads to more than six concurrent requests, HTTP 1.1 and its browser implementation become a bottleneck.
I don't control the user experience, so cannot enforce UX-centric optimisations like batching. Full-fletched support for HTTP/2 in HeldionSE would allow me to solve the performance issue from the server/service-side

**Comment by danielkec** [comment]
We have end to end HTTP/2 support in both server and client in Helidon 4
