### ISSUE TITLE
java.util.logging.ConsoleHandler.formatter wrong formatter

### ISSUE THREAD

**Issue by wojtask9** [helidon-io/helidon#333]
in logging.properties 
`java.util.logging.ConsoleHandler.formatter` points to wrong `formatter`

Currently `io.helidon.webserver.netty.WebServerLogFormatter` but should be `io.helidon.webserver.WebServerLogFormatter`

Also small guidelines bug:
See bottom of page: https://helidon.io/docs/latest/#/guides/01_SE_REST_web-service

In this guideline there are lines
```
mvn package
java -jar target/se-restful-webservice.jar
```
this should be replaced with
```
mvn package
java -jar target/quickstart-se.jar
```

The same with MP guide

**Comment by romain-grecourt** [comment]
@wojtask9 The step in the guide with `java -jar target/se-restful-webservice.jar` is supposed to be executed against https://github.com/oracle/helidon/tree/0.11.0/examples/guides/se-restful-webservice ; we do have a bug to improve that last section of the guide: #167

I'll fix the wrong logger names.

**Comment by wojtask9** [comment]
@romain-grecourt 
Ok then. But there is another issue :)
See https://github.com/oracle/helidon/blob/master/examples/guides/se-restful-webservice/README.md

In README.md  example
```
java -jar target/quickstart-se.jar
```
should be switched to 

```
java -jar target/se-restful-webservice.jar
```

**Comment by romain-grecourt** [comment]
Oops, this one is legit, will fix! Thank you for reporting.
