### ISSUE TITLE
Add documentation for data source integration in MP

### ISSUE THREAD

**Issue by arjav-desai** [helidon-io/helidon#3395]
We currently on have only a guide https://helidon.io/docs/latest/#/mp/guides/07_datasource, which talks about how to use hikaricp with h2 and a pointer to mysql example.

With various integration that we have, we might want to consider adding a section.
- hikaricp
- ucp (including using Oracle ATP and how to specify wallet using TNS_ADMIN on jdbcURL or system property or env variable), see https://blogs.oracle.com/javamagazine/fast-flexible-data-access-in-java-using-the-helidon-microservices-platform
- micronaut data integration https://medium.com/helidon/helidon-with-micronaut-data-repositories-daf6ddefee0b
- mongo db (we have example of mongo db with db client but not for MP. With MP, we have mysql and h2 examples as pointed out in guide)
- we can also clarify various ways/properties that can be used to do this e.g. javax.sql.DataSource.* or oracle.ucp.jdbc.PoolDataSource.* and just datasource.default.* etc.

**Comment by arjav-desai** [comment]
Usage of hikaricp and ucp is mentioned as part of CDI Extensions documentation

- https://helidon.io/docs/latest/#/mp/extensions/02_cdi_datasource-hikaricp
- https://helidon.io/docs/latest/#/mp/extensions/02_cdi_datasource-ucp

**Comment by ljamen** [comment]
Hi @arjav-desai - These links are no longer working. I've asked @Geetha-Savithriamma to work with you on this.

**Comment by arjav-desai** [comment]
the issue was filed when v2 was latest buts its v3 now so if you change “latest” in link with “v2", it still works e.g. https://helidon.io/docs/v2/#/mp/guides/07_datasource

**Comment by arjav-desai** [comment]
It seems with v3 doc updates, we have consolidated following from v2 in 

- data
- https://helidon.io/docs/v2/#/mp/guides/07_datasource
- https://helidon.io/docs/latest/#/mp/extensions/02_cdi_datasource-hikaricp
- https://helidon.io/docs/latest/#/mp/extensions/02_cdi_datasource-ucp
- jpa
- https://helidon.io/docs/v2/#/mp/guides/09_jpa
- https://helidon.io/docs/v2/#/mp/jpa/01_introduction

in a single doc as https://helidon.io/docs/latest/#/mp/persistence.

**Comment by arjav-desai** [comment]
However, this doc is still doesn't include 

- mongo db (we have example of mongo db with db client but not for MP. With MP, we have mysql and h2 examples as pointed out in guide)
- we can also clarify various ways/properties that can be used to do this e.g. javax.sql.DataSource.* or oracle.ucp.jdbc.PoolDataSource.* and just datasource.default.* etc.

may be cause its JPA centric.

You can may be take the section about "Named Datasource integration" from new JPA doc and add above items to make it a new "Data" doc.

**Comment by Geetha-Savithriamma** [comment]
Most of the integrations have already been added in version 3: https://helidon.io/docs/latest/#/mp/persistence.
No further update is required at this point. Checked with Arjav who advised me to close the issue.
