### ISSUE TITLE
Update OCA links

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#3469]
The OCA link in the CONTRIBUTING.md file points to https://www.oracle.com/technetwork/community/oca-486395.html instead of https://oca.opensource.oracle.com

Update the CONTRIBUTING.md file and any other file containing the old OCA link.

**Comment by klustria** [comment]
Change completed via: https://github.com/oracle/helidon/pull/3476

**Comment by Captain1653** [comment]
This issue is really old. PR was merged. Should it be closed?

**Comment by klustria** [comment]
I thought this was already closed. Thanks for bringing it up. Closing this now as changed to resolve this issue has been committed.
