### ISSUE TITLE
Documentation : Add a link to CLI as a preferred way to create new Helidon apps

### ISSUE THREAD

**Issue by tvallin** [helidon-io/helidon#3621]
This change should be done for every guide.

**Comment by romain-grecourt** [comment]
We will likely have a widget for the cli in the docs, we could make a more manual change temporarily or wait until we have the widget in-place.

**Comment by ljamen** [comment]
Hi @romain-grecourt - do we want to go ahead and make these updates or are we still waiting for the 'widget'?

**Comment by romain-grecourt** [comment]
We are still a few months ahead of the documentation/site work that will include the new widgets.
Are you thinking of replacing every occurrence of `mvn archetype:generate` with `helidon init` ?

**Comment by ljamen** [comment]
If this is a high priority I can go in and modify all of the guides. It's just not clear to me if that's something we want to take on. I'll defer to you.

**Comment by romain-grecourt** [comment]
I put this back in triage to raise the question with the team again.
