### ISSUE TITLE
Add ability to get datasource password from vault(s)

### ISSUE THREAD

**Issue by paulparkinson** [helidon-io/helidon#3649]
Helidon now has the OCI ATP Service Integration with Wallet Management feature to automatically obtain the wallet for ADB datasource and also has the OCI and Hashicorp Vault integrations to get secrets. Would be nice if the latter could be used to automatically retrieve the password for a datasource (ie provide ocid/id of pw secret via config), in this way completely decoupling security info from the environment.

## Environment Details
* Helidon Version: 2.4.0
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
See overall description 

## Steps to reproduce
See overall description

**Comment by ljnelson** [comment]
This is now possible with the resolution of #4238 (see #7520, #7555, #7481, #7470, etc.)
