### ISSUE TITLE
Enhancement request to inject JedisSentinelPool object through "helidon-integrations-cdi-jedis" dependency

### ISSUE THREAD

**Issue by RaghuTrivandrum** [helidon-io/helidon#3891]
Enhancement request to inject JedisSentinelPool object through "helidon-integrations-cdi-jedis" dependency

## Environment Details
* Helidon Version: 2.4.1
* Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
Currently, JedisPool and JedisPoolConfig can be injected at the application scope through "helidon-integrations-cdi-jedis" dependency
Documentation: https://helidon.io/docs/v2/#/mp/extensions/03_cdi_jedis

This is an enhancement request to inject/support Sentinel setup through JedisSentinelpool object.

**Comment by RaghuTrivandrum** [comment]
There are breaking changes while migrating 3.x to 4.x of Jedis
https://github.com/redis/jedis/blob/master/docs/3to4.md

Do we plan to upgrade the version of Jedis ?

**Comment by ljnelson** [comment]
Closing as this extension/integration no longer exists in Helidon 4.x.
