### ISSUE TITLE
[Doc:] Helidon MP Persistence

### ISSUE THREAD

**Issue by dalexandrov** [helidon-io/helidon#4203]
Helidon MP JPA documentation (according to the new documentation structure).

Path: `/HelidonMP/Enterprise`

Currently just a link to JPA documentation. Should be extended.

- [ ] Overview (should be created)
- [ ] Maven Dependency (may be reused from current doc)
- [ ] Usage (should be created)
- [ ] API (should be created using JPA documentation)
- [ ] Configuration (should be created)
- [ ] Reference (should be created)
- [ ] Examples (Pokemon example with link to repo)
- [ ] Additional Information (if applicable)

**Comment by m0mus** [comment]
Reopening for language review.
