### ISSUE TITLE
Add Support to OCI Vault as a Config Source

### ISSUE THREAD

**Issue by klustria** [helidon-io/helidon#4238]
## Environment Details
* Helidon Version: 2.50
* Helidon MP

----------

## Problem Description
Find a suitable solution on how to use OCI Vault/Secrets as a config source

**Comment by trentjeff** [comment]
Relates to https://github.com/helidon-io/helidon/issues/3649
and https://github.com/helidon-io/helidon/issues/4191

We also need to determine whether we need refresh value, so that it could be cached or refreshed on a time interval.

**Comment by trentjeff** [comment]
Fwiw, I suggest we do this on 3.x and forward port it to 4.x

**Comment by ljnelson** [comment]
Fully addressed in #7520 and #7555. Closing.
