### ISSUE TITLE
Problem with running integration tests using maven

### ISSUE THREAD

**Issue by AlirezaDastyar** [helidon-io/helidon#4246]
Starting container (`@HelidonTest`) fails when running integration tests using maven failsafe plugin.
## Environment Details
* Helidon Version: 2.5.0
* Helidon MP
* JDK version: 18 (build 18+36-2087)
* OS: Fedora 36
* Docker version: 20.10.16

----------

## Problem Description
So when I try to run the integration tests with `mvn verify` I face following errors:
```
org.jboss.weld.exceptions.AmbiguousResolutionException: 
WELD-001335: Ambiguous dependencies for type DataSourceProvider with qualifiers 
 Possible dependencies: 
  - Managed Bean [class io.helidon.integrations.cdi.jpa.JtaDataSourceProvider] with qualifiers [@Any @Default],
  - Managed Bean [class io.helidon.integrations.cdi.jpa.JtaDataSourceProvider] with qualifiers [@Any @Default]

org.jboss.weld.exceptions.AmbiguousResolutionException: 
WELD-001335: Ambiguous dependencies for type TransactionSupport with qualifiers 
 Possible dependencies: 
  - Managed Bean [class io.helidon.integrations.cdi.jpa.JtaTransactionSupport] with qualifiers [@Any @Default],
  - Managed Bean [class io.helidon.integrations.cdi.jpa.JtaTransactionSupport] with qualifiers [@Any @Default]

```
Although tests do work just fine when I try `mvn failsafe:integration-test` or even running them manually using surefire.
I've managed to reproduce it by modifying the helidon-mp quick start project(attached as a zip file).
[helidon-quickstart-mp.zip](https://github.com/oracle/helidon/files/8742299/helidon-quickstart-mp.zip)

## Steps to reproduce
1. create a helidon-mp quick start project.
2. follow the JPA guide but for hibernate.
3. add a container managed `EntityManager` to greeting resource.
4. add maven failsafe plugin to pom.xml.
5. add a integration test class (`SomeNameIT`) with `@HelidonTest`.
6. run `mvn verify`

**Comment by tjquinno** [comment]
Jan found and pointed to this issue which, while closed, could be related: https://issues.apache.org/jira/browse/SUREFIRE-1286

**Comment by jvissers** [comment]
For me changing the failsafe configuration to include this:

```
<classesDirectory>${project.build.directory}/classes</classesDirectory>
```

resolved the issue.

**Comment by AlirezaDastyar** [comment]
The workaround that @jvissers suggested worked for me as well.

**Comment by ljnelson** [comment]
Closing this issue since the failsafe configuration resolves it. I may open another one to add archetype configuration by default.

**Comment by ljnelson** [comment]
See #9039.
