### ISSUE TITLE
OpenAPITool Helidon Documentation

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#4268]
- [ ] Server MP
- [ ] Server SE
- [ ] Client MP
- [ ] Client SE

See:
#4021
#4020
#4018
#4023

**Comment by tjquinno** [comment]
Re-opening this issue because we have not moved the docs to 4.x yet.

I will do that forward port at some point.

**Comment by tjquinno** [comment]
With 4.1 both the MP and SE docs for generating clients and servers reflect the recently-enhanced 4.x generation features. Closing.
