### ISSUE TITLE
Remove deprecated code

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#4362]
Remove deprecated code.

Tasks:
 - remove the deprecated code
 - make sure the deprecation is correctly documented in 2.x (since, forRemoval on `@Deprecated` annotation, use `@deprecated` javadoc tag to link to the correct new implementation, or describe what to do if a simple replacement does not exist)
 - validate documentation and examples are correct with regard to the deprecated element

The following modules should be updated (classes either contain a deprecated element, or are deprecated fully)
- [x] #4363
- [ ] #4364
- [x] #4365
- [x] #4366
- [x] #4367
- [x] #4368
- [x] #4369
- [x] #4370
- [x] #4371
- [x] #4372
- [x] #4373
- [x] #4374
- [x] #4480

**Comment by barchetta** [comment]
Closing epic. Leaving last issue open.
