### ISSUE TITLE
MP Metrics clears app registry late in CDI start-up life cycle

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#4656]
## Environment Details
* Helidon Version: 2.x, 3.x
* Helidon SE or Helidon MP MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
The Helidon metrics CDI extension clears out the application metrics registry in a method which `@Observes @Initialized(ApplicationScoped.class)`. Normally this is fine but a user has encountered a use case in which a provider has registered application metrics prior to this. Once the extension clears out the app registry the previously-registered metrics are missing.

## Steps to reproduce
To mimic the specific use case, create a CDI extension which `@Observes AfterBeanDiscovery` and have it register an application metric. Later, once the Helidon metrics CDI extension `registerService` method has run (after app-scoped initialization is complete), the previously-registered app metric is gone.

**Comment by spericas** [comment]
@tjquinno I'm assuming we do this to run multiple unit tests classes within a single VM

**Comment by tjquinno** [comment]
Yes, exactly. That avoids lots of duplicate-metric-registered errors. 

The `@HelidonTest` annotation accepts `resetPerTest` which  restarts the Helidon container for each test, but with that specified the test container is documented as not injecting into fields or constructors which causes other problems with the metrics MP unit tests, at least as written today.

**Comment by AshokVardhanM** [comment]
Hi @tjquinno,

can you please share information on when this issue will be fixed ?

Thanks,
Ashok

**Comment by tjquinno** [comment]
At the moment, we do not have an ETA for this fix. I wish we had more definite news to share on this.
