### ISSUE TITLE
Document `experimental` feature flag

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon#4667]
We should consider documenting what `experimental` feature is more precisely so its more obvious for our users.

Propositions:

- change the name! `cutting edge`, `brand new`, `incubated` ...
- create extra page explaining what `experimental` flag actually means and link every mention to it
- add `since` to the flag so we can track more carefully how much time/versions the features spend with this flag
- move experimental features to a separate "incubator" repo (under the new helidon-io org gitHub site, and name those modules accordingly with "-experimental" in their artifact names.

**Comment by tomas-langer** [comment]
Experimental no longer exists in 4.x
We now have:
- `Preview` (production ready, but may have backward incompatible changes)
- `Incubating` (not production ready, to play around with and provide feedback)

**Comment by tomas-langer** [comment]
Closing this issue, as it seems no longer valid.
