### ISSUE TITLE
Itermittent failure - archetype build (FT timeout)

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#4688]
The file `archetypes/helidon/src/main/archetype/se/custom/files/src/main/java/__pkg__/FtService.java.mustache` defines timeout to be `100` milliseconds
The file `archetypes/helidon/src/main/archetype/se/custom/files/src/test/java/__pkg__/FtServiceTest.java.mustache` defines a test that
- checks that a sleep of `50` ms passes
- checks that a sleep of `150` ms times out
The lambda is too small - on a slower environment, we can timeout the first request, and succeed the second one (which is happening in our pipelines sometimes).

We should have diffs of at least 5 seconds
- set timeout to 5 seconds
- check with 50 ms sleep (success)
- check with 10 seconds sleep (timeout)

This should be a sufficient buffer for our pipeline tests.

Please make sure there isn't another test in Helidon examples or integration test with similar issues.

**Comment by tvallin** [comment]
Fixed by https://github.com/helidon-io/helidon/pull/4690 in main branch and backport to 3.x here https://github.com/helidon-io/helidon/pull/4934
