### ISSUE TITLE
Metrics TCK runs twice with different test counts

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#4722]
## Environment Details
* Helidon Version: 2.x, 3.x
* Helidon SE or Helidon MP MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
Our driver project which runs the MP metrics TCK triggers two TCK runs which seem to duplicate some of the tests.

## Steps to reproduce
```
cd helidon/microprofile/tests/tck/tck-metrics
mvn test
```
Output shows two runs:
```
16:57:39,659 [INFO] Results:
16:57:39,660 [INFO] 
16:57:39,660 [INFO] Tests run: 233, Failures: 0, Errors: 0, Skipped: 0
16:57:39,660 [INFO] 
16:57:39,703 [INFO] 
16:57:39,703 [INFO] -------------------------------------------------------
16:57:39,703 [INFO]  T E S T S
16:57:39,703 [INFO] -------------------------------------------------------
16:57:40,213 [INFO] Running TestSuite
17:04:38,533 [INFO] Tests run: 213, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 418.3 s - in TestSuite
17:04:38,579 [INFO] 
17:04:38,579 [INFO] Results:
17:04:38,579 [INFO] 
17:04:38,579 [INFO] Tests run: 213, Failures: 0, Errors: 0, Skipped: 0
17:04:38,579 [INFO] 
```
There seems to be no inherent need to run any tests twice.

**Comment by Captain1653** [comment]
I think I've found the reason. It depends on the configuration of the `maven-surefire-plugin`. Root project `tck-project` has `surefire-testng`, but `tck-metrics` ingerited this configuration and has `surefire-junit`. 


<img width="1004" alt="Screenshot 2023-03-03 at 23 38 38" src="https://user-images.githubusercontent.com/4740207/222834518-c75bb562-a55c-4e5c-86a6-7e9eead556fa.png">

### The first run - junit, the second run - testng.

<img width="1681" alt="Screenshot 2023-03-03 at 23 30 03" src="https://user-images.githubusercontent.com/4740207/222835252-01f4d8b6-0e7e-46f1-8c48-45b9fa7387d4.png">


I changed all to `surefire-junit` and these tests run once. Should I create PR? I'm not sure. 

Some modules should use `surefire-testng`, but  some`surefire-junit`. Should every module configure its own dependency for `maven-surefire-plugin`?

**Comment by Captain1653** [comment]
Modules `tck-messaging` and  `tck-lra` have the same problem.

**Comment by tjquinno** [comment]
I incorporated this change into the recent 4.x metrics merge. I am closing this issue for metrics and will create two others for LRA and messaging.
