### ISSUE TITLE
JPA integration tests should run on every build

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#4740]
This should be fixed for:
 - helidon-2.x
 - helidon-3.x
 - main

The `tests/integration/jpa` module is only executed when profile `native-image` is enabled. They do not run in pipeline or during local builds.
Currently the tests seem to fail.

The test should be changed to be runnable in Java without any changes (e.g. if I do `mvn install -Ptests`, the test should run against an in-memory database.
When run with additional profiles, they can be used to validate other databases and/or native image (this should be pipeline specific and done in the appropriate scripts).

We should not have code that is not compiled and executed in the repository.

**Comment by Tomas-Kraus** [comment]
This should be ported to main branch too.
