### ISSUE TITLE
Incorrect use of `withSources` on SE `Config` in SE advanced config doc

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#4775]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.x, 3.x, 4.x
* Helidon SE or Helidon MP SE
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
The SE advanced config doc refers to a non-existent method: `Config.withSources(...)`. 

Should probably be `Config.builder(...)` instead.

- [x] 2.x - #4943
- [x] 3.x - #4920 
- [ ] 4.x - #4944

**Comment by Captain1653** [comment]
After merging backports:
[2.x](https://github.com/helidon-io/helidon/pull/4943)
[4.x](https://github.com/helidon-io/helidon/pull/4944) 

this issue can be closed. I didn't use 'Resolve' notation in my PR's.

**Comment by Captain1653** [comment]
All PR's were merged. This issue can be closed.
