### ISSUE TITLE
Upgrade GraalVM to v22

### ISSUE THREAD

**Issue by edbratt** [helidon-io/helidon#4836]
Tracking issue to coordinate work necessary for upgrading to GraalVM v22.

**Comment by tomas-langer** [comment]
Started working on this issue.
I will use GraalVM 22.3.0 dev builds, as since this version we can access required APIs in published module (and we no longer need to use the internal `svm` module).
Until 22.3 is released, we cannot finish this task.

**Comment by tomas-langer** [comment]
Fixed in 3.x and 4.x branches. I am not working on backport to 2.x. Is this something we should do as well?

**Comment by tomas-langer** [comment]
Closing this issue. If there is a specific problem, or this needs to be done for 2.x, please kindly create a new issue.
