### ISSUE TITLE
Guidance for implementing incoming bandwidth throttling

### ISSUE THREAD

**Issue by janotav** [helidon-io/helidon#4881]
## Environment Details
* Helidon Version: 2.5.0
* Helidon SE
* JDK version: 11
* OS: Linux

----------

We would like to implement bandwidth throttling in our Helidon-based web server. The common approach is for the server to return 429 status when it finds the client to be overrunning the portion of resources it has been allocated as described in https://www.rfc-editor.org/rfc/rfc6585.

Unfortunatelly in order for the mechanism to meaningfully protect the server from the client over-saturating the server ingress network capacity with many large requests, the 429 status must not be sent back after the server has fully received the incoming body payload. In such case the client would be notified about breaching the allotted quota, but the relevant server bandwidth would have been lost anyway without any possibility for the server to meaningfully moderate which clients to throttle and which to let through.

The above linked RFC mentions this in the 7.2. section:

>   When a server is under attack or just receiving a very large number
>   of requests from a single party, responding to each with a 429 status
>   code will consume resources.

>   Therefore, servers are not required to use the 429 status code; when
>   limiting resource usage, it may be more appropriate to just drop
>   connections, or take other steps.
   
What are our options here in relation to Helidon? It appears that if I implement the Helidon webserver to simply reject everything by immediately calling:

```
        private void handler(ServerRequest request, ServerResponse response) {
            response.status(429);
            response.send("Too many requests");
        }
```

The throttling response appears to be dispatched only the server fully receives the client request:

```
$ time curl --noproxy "*" -s -X POST -T hugefile -H "Expect:" --limit-rate 10M http://localhost:8080/test 
Too many requests
real	2m15,077s
user	0m0,628s
sys	0m2,818s
```

Is there a way how to avoid this? Is it possible to somehow force the connection to be closed instead?

**Comment by danielkec** [comment]
Is this solution you are looking for?
```
                .post("/test",(req, res) -> {
                    LongAdder reqContentSize = new LongAdder();
                    req.content()
                            .peek(dataChunk -> {
                                reqContentSize.add(dataChunk.remaining());
                                // Max file size 2Mb
                                if(reqContentSize.sum() > 2 * 1024 * 1024){
                                    req.closeConnection();
                                }
                            })
                            .forEach(dataChunk -> {
                                // Some business logic
                                dataChunk.release();
                            })
                            .onError(res::send)
                            .forSingle(unused -> res.send("File size "+reqContentSize.sum()));
                })
```

```
kec@romulus:~$ time curl -v --noproxy "*" -s -X POST -T ~/huge-file.zip -H "Expect:" --limit-rate 10M http://localhost:8080/test
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /test HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 171676507
> 
* Send failure: Broken pipe
* Closing connection 0

real	0m0,218s
user	0m0,004s
sys	0m0,004s

kec@romulus:~$ time curl -v --noproxy "*" -s -X POST -T ~/right-size-file.zip -H "Expect:" --limit-rate 10M http://localhost:8080/test
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /test HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 1071503
> 
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Fri, 30 Sep 2022 16:14:00 +0200
< connection: keep-alive
< content-length: 17
< 
* Connection #0 to host localhost left intact
File size 1071503
real	0m0,116s
user	0m0,003s
sys	0m0,003s
```

**Comment by janotav** [comment]
I think that what we ultimately want is what I later described in https://github.com/helidon-io/helidon/issues/4912

This snippet was quite helpful though. Thanks!
