### ISSUE TITLE
Revise OpenAPITools GitHub actions changes to remove Helidon-specific changes

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#4888]
We changes the generator GitHub actions to do some Helidon-specific things (which we do not want to change in the main OpenAPITools repo) as well as to add a step to find and run functional tests which we DO want to merge into the main repo.

This issue is for removing the Helidon-specific changes form the file.

**Comment by tvallin** [comment]
Closed in https://github.com/tjquinno/openapi-generator/pull/58
