### ISSUE TITLE
Tracing config updates in archetype

### ISSUE THREAD

**Issue by arjav-desai** [helidon-io/helidon#4892]
If we select tracing while generating either SE or MP, the tracing config is added to k8s yaml instead of config files. While this will be fixed as part of https://github.com/oracle/helidon/pull/4887 and https://github.com/oracle/helidon/pull/4891, we need to make sure tracing config is added at right location i.e. config file where it belongs.

Also, currently tracing config is generated only in yaml format but it should be generated in properties format for MP, see https://github.com/oracle/helidon/blob/helidon-3.x/archetypes/helidon/src/main/archetype/common/observability.xml

It would make sense to have SE and MP level config moved from common to those respective flavors.

**Comment by tvallin** [comment]
closed by #5001
