### ISSUE TITLE
Allow Helidon server to properly implement Expect: 100-continue protocol

### ISSUE THREAD

**Issue by janotav** [helidon-io/helidon#4912]
## Environment Details
* Helidon Version: 2.5.2
* Helidon SE
* JDK version: 11
* OS: Linux

----------

## Problem Description
When request with header "Expect: 100-continue" is received by Helidon server, it automatically responds with "100 Continue".

The webserver implementation must have means to respond with "417 Expectation Failed" if that is appropriate in given context. 

This ticket partially responds to the question I originally raised as https://github.com/oracle/helidon/issues/4881

### PRs:

- [x] 2x - #5912
- [x] 3x - #5714
- [x] 4x - #5965

**Comment by danielkec** [comment]
Fixed
