### ISSUE TITLE
OpenAPITools generators produce Helidon 3 projects that won't compile

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#4913]
I tried the latest generators (as of Tim's commit 3e0dad4ce3f17511660a59b5f0a0ce61373de275) and if I use helidon 3.0.1 then three of the four generators create projects that fail to compile because of the javax -> jakarta java package change. The failing generators are:

- [ ] Server MP
- [ ] Server SE
- [ ] Client MP

Client SE is OK.  To reproduce:

```
java -jar ${OPENAPIWS}/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java-helidon-server --library mp -i ../../quickstart-openapi.yaml  --additional-properties "helidonVersion=3.0.1"

mvn clean install
. . .
[ERROR] /Users/jdipol/tmp/openapi/3.x/server-mp/src/main/java/org/openapitools/server/api/DefaultServiceImpl.java:[18,24] package javax.ws.rs.core does not exist
. . .
```

In this case I used the openapi spec produced by the Helidon MP Quickstart. But I imagine any of the test specs will reproduce the error.

**Comment by tjquinno** [comment]
Although many (all?) of the relevant templates use the tag `rootEEPackage` as a prefix for various generated `import` statements, our Java code neither sets `rootEEPackage` according to the effective Helidon version (if the user did not explicitly set the package) nor does it check that the user didn't specific an invalid value for it. (Although we do not advertise this setting, users could specify it on the command line so we should check for that.)
