### ISSUE TITLE
Helidon MP 2.5.3 does not compile using/for Java 19

### ISSUE THREAD

**Issue by jvissers** [helidon-io/helidon#4939]
## Environment Details
* Helidon Version: 2.5.3
* Helidon Helidon MP
* JDK version: "19" 2022-09-20 (build 19+36-223)
* OS: 22.04.1 LTS
----------

## Problem Description
Trying to compile a Helidon MP 2.5.3 project using JDK 19 fails, in Hibernate/Bytebuddy byte code enhancement.

## Solution
Bump to following versions:
- Hibernate 5.6.11.Final
- ByteBuddy 1.12.17 (also for dependency convergence)
- jna & jna-platform 5.12.1 (dependency convergence)

**Comment by barchetta** [comment]
The issues had to do with bytecode manipulation. After upgrading Hibernate and Eclipselink I was able to build and run the following examples with `java 19 2022-09-20`

```
examples/integrations/cdi/jpa   # Uses eclipselink JPA
examples/integrations/cdi/pokemons # Uses Hibernate JPA
```

I was also able to build the other examples without problem.
