### ISSUE TITLE
Usused directory in generated Helidon SE quickstart application

### ISSUE THREAD

**Issue by m0mus** [helidon-io/helidon#4995]
I generated Helidon SE quickstart application using 3.0.1 Project Starter. It contains `META-INF.native-image` directory with `reflect-config.json` file which contains empty JSON array. I think we should remove this directory from *ALL* generated projects the same way as we've done with Helidon MP quickstart.

**Comment by tvallin** [comment]
Already fixed. 
Please see the filled issue here: https://github.com/helidon-io/helidon/issues/4833 
and the fix in `main` earlier this month: https://github.com/helidon-io/helidon/pull/4844
and backport to 3.x: https://github.com/helidon-io/helidon/pull/4874
