### ISSUE TITLE
When grpc-netty 1.49.x is pulled in gRPC protobuf servers will hang on onCompleted()

### ISSUE THREAD

**Issue by space88man** [helidon-io/helidon#4998]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 3.0.1
* Helidon MP
* JDK version: 17
* OS: Fedora 36
* Docker version (if applicable):

----------

## Problem Description
[//]: # Not a bug per se as Helidon gRPC integrations use 1.45.x
[//]: # Had a dependency that explicitly pulled in 1.49.x
[//]: # No exceptions were observed: but the stream observer `onCompleted` method hangs; `onNext()` is still working

## Steps to reproduce
[//]: # Create a grpc-java server implementation(standard protobuf-type server) and allow it to be started with Helidon integrations
[//]: # Explicitly pull in grpc-netty 1.49.0 or 1.49.x
[//]: # Observe that the method `onCompleted` hangs

This hang does not happen with 1.48.x and below.

**Comment by barchetta** [comment]
To support grpc 1.49.x we need to upgrade the version in Helidon. We should evaluate upgrading to 1.49.1 (https://github.com/grpc/grpc-java/releases)

**Comment by space88man** [comment]
@tomas-langer  @barchetta
> To support grpc 1.49.x we need to upgrade the version in Helidon. We should evaluate upgrading to 1.49.1 (https://github.com/grpc/grpc-java/releases)

FYI:
* when the dependency was pinned up to 1.48.1 the service continued to work.
* the moment the service used 1.49.0/1.49.1 then a hang occurred in `onCompleted()` — the client never received any (Unary) reply
* with 1.49.1 and **without**   Helidon gRPC integrations, i.e., starting the server manually — it works

```
// non-integrated - this works with 1.49.1 - onCompleted() does not hang
server = NettyServerBuilder.forAddress(new InetSocketAddress(getListeningHost(), getListeningPort()))
                .addService(new MyServiceImpl(...)).build();
        server.start();
```
