### ISSUE TITLE
[4.x] SE tracing doc shows obsolete technique for creating a server

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#5023]
## Environment Details
* Helidon Version: 3.x
* Helidon SE or Helidon MP SE
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
This doc section https://helidon.io/docs/latest/index.html#/se/tracing#_usage illustrates using `ServerConfiguration.builder()` which is now deprecated in favor of `WebServer.builder()`. 

There might be other similar places elsewhere in the doc. I have not looked.

I am marking this for 4.x but the same problem exists in earlier releases.

**Comment by Captain1653** [comment]
@romain-grecourt Close this issue, please.
