### ISSUE TITLE
Injected Bean created using @Produces is null when using @EntityListeners 

### ISSUE THREAD

**Issue by Neoministein** [helidon-io/helidon#5036]
## Environment Details
* Helidon Version: 3.0.1
* Helidon MP
* JDK version: 17.0.4
* OS: Windows 10
* Docker version (if applicable): -

----------

## Problem Description

~When accessing a CDI bean that gets instantiated through the `@Produces` annotation using `@EntityListeners` it results in being null.~

I've got `AGenericBean` which gets created by the `@Produces` annotation. It initially returns null but the object is set before anything requires it via an Inject. 

However when the `AGenericBean` gets injected into a class which is used by the `@EntityListeners` annotation it results in being null.

I've noticed that on startup the methods which are annotated with `@Produces` are being called when `@EntityListeners` annotation is used somewhere. It looks like the result from the initial call gets stored somewhere and used for those classes.

## Steps to reproduce

[Here](https://github.com/Neoministein/example/tree/master/issue/helidon/jpa-produces) is a simple project with a test which recreates the issue. 

### Java code

I am using the following Helidon dependencies:

- helidon-microprofile
- helidon-integrations-cdi-jpa
- helidon-integrations-cdi-hibernate
- helidon-integrations-cdi-jta-weld
- helidon-integrations-cdi-datasource-hikaricp
- helidon-microprofile-tests-junit5

```java
package com.neo.example;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Produces;

@ApplicationScoped
public class GenericBeanProducer {

    protected AGenericBean aGenericBean = null;

    @Produces
    public AGenericBean getAGenericBean() {
        return aGenericBean;
    }


    public void setAGenericBean(AGenericBean aGenericBean) {
        this.aGenericBean = aGenericBean;
    }
}
```

```java
package com.neo.example;

import jakarta.inject.Inject;
import jakarta.persistence.PrePersist;

public class BasicEntityListener {

    @Inject
    protected AGenericBean aGenericBean;

    @PrePersist
    public void prePersist(BasicEntity basicEntity) {
        aGenericBean.doStuff(); // <-- Throws NullPointerException
    }
}
```

```java
package com.neo.example;

import jakarta.persistence.EntityListeners;

@Entity
@Table(name = BasicEntity .TABLE_NAME)
@EntityListeners(BasicEntityListener.class)
public class BasicEntity {
...
}
```

**Comment by ljnelson** [comment]
Hello; thanks for using Helidon. I don't see any access of any kind here. Do you mean that in your second code sketch the `aGenericBean` field is `null`?  Or perhaps you mean that the `basicEntity` argument is `null`?  Or perhaps you mean something else?

Which JPA provider are you using?  Are you using Helidon's JPA integration, or just using JPA by hand?

In order to know how to proceed we'll need a lot more details.

**Comment by Neoministein** [comment]
I've updated the initial comment with more details and uploaded a project which recreates the issue. Hope this makes it more clear.

**Comment by ljnelson** [comment]
Thanks! Reproducers always help. I'll be digging into this soon. It's not immediately clear to me that Helidon itself needs to do anything (I think the JPA provider is responsible for setting up entity listeners) but there may be some CDI qualifier issues that are getting in the way.

**Comment by ljnelson** [comment]
Hello; it has been a long time; our team is small and has a massive workload. Sorry for the delay. I am looking at your reproducer. Could the problem simply be that your `@Produces` method produces an object in `Dependent` scope (you don't annotate the method with a scope, so it is `Dependent` by default)?

**Comment by Neoministein** [comment]
Thanks for looking into it after this long time.

> The short answer is: this works as it does, and has nothing to do with Helidon.

Good to know, I'll look at the Hibernate code, and perhaps open an issue there. 

> In general what you're doing is mildly frowned on in the CDI world anyway

Yeah I know :sweat_smile:, I wanted to propagate a `@Requestscoped` bean through my entire Application, and the value gets set by a `ContainerRequestFilter` so it always should be set.


## My Workaround 

For anybody stumbling onto this issue later. My workaround for this issue was to use a `Provider`.

```java
package com.neo.example;

import jakarta.inject.Inject;
import jakarta.inject.Provider;
import jakarta.persistence.PrePersist;

public class BasicEntityListener {

    @Inject
    protected Provider<AGenericBean> aGenericBeanProvider;

    @PrePersist
    public void prePersist(BasicEntity basicEntity) {
        aGenericBeanProvider.get().doStuff(); // <-- Works 
    }
}
```
