### ISSUE TITLE
Make UDP server possible with Helidon Nima

### ISSUE THREAD

**Issue by denismakogon** [helidon-io/helidon#5066]
Recently Helidon became even more attractive with the introduction of virtual threads through Project Nima.
As for now, it supports only TCP-based protocols at the same time there a huge area where's the UDP is much more appreciated than the TCP (with the delivery guarantee), for instance - gaming, F1 simulator in particular (see https://answers.ea.com/t5/General-Discussion/F1-22-UDP-Specification/td-p/11551274?attachment-id=607611). This game, like possibly many others use UDP sockets to push the data (telemetry) with a considerable frequency (from 120 to 200RPS or even more). So, virtual threads (alongside the ZGC) could make it possible to handle that workload coming from the UDP.

So, it would be great if Project Nima can be reused in the context of the UDP within Helidon.

**Comment by spericas** [comment]
@denismakogon In an attempt to initiate some discussion about UDP in Helidon Nima, I created a simple UDP API and wrote a couple of examples. I'd be interested in getting some feedback from your or others you may know that have experience in this area, from which we can then collect a more definitive list of requirements to explore this idea further.

**Examples**
- Non-declarative:
https://github.com/spericas/helidon/blob/udp-brainstorm/examples/nima/udp/src/main/java/io/helidon/examples/nima/udp/JsonUdpEndpoint1.java
- Declarative:
https://github.com/spericas/helidon/blob/udp-brainstorm/examples/nima/udp/src/main/java/io/helidon/examples/nima/udp/JsonUdpEndpoint2.java


**API**
- https://github.com/spericas/helidon/tree/udp-brainstorm/examples/nima/udp/src/main/java/io/helidon/examples/nima/udp

**Comment by denismakogon** [comment]
Hey! Thank you so much for moving this forward! Based on the given implementation, I only have one thing to bring: the UDP interface. After spending a lot of time working with Netty and Apache Mina, I realized that Apache Mina has probably the best interface - https://nightlies.apache.org/mina/mina/2.0.21/apidocs/org/apache/mina/core/service/IoHandlerAdapter.html

I guess it's fine to have `onError` and `onMessage` methods to accomplish minimal use cases, but ideally, I'd like to have a bit more control over request handling at every stage of the request.

**Comment by denismakogon** [comment]
I would also add C++ Boost-based framework https://github.com/chronoxor/CppServer#example-udp-echo-server, it has an interface similar to Mina which means it's totally fine to have similar one in Helidon.

**Comment by spericas** [comment]
@denismakogon I didn't know about any APIs like that, let me take a look at Mina in more detail and provide a new iteration over this.

**Comment by spericas** [comment]
@denismakogon `IoHandlerAdapter` is a bit more generic than what is required by UDP, which makes sense since Mina seems to be a more generic network library. There are two concepts there not covered by the proposal: 

1. the notion of a session and 
2. async sending of messages. 

(1) seems more for _connection oriented_ protocols like TCP where connections are potentially longer lived. (2) is easily added to the proposal. 

Perhaps you can outline some use cases to better understand what is missing in the proposal.

**Comment by spericas** [comment]
API proposal updated with async support and a notion of multiple clients (multicast via unicast)

**Comment by spericas** [comment]
@trentjeff The high-level use cases are the traditional ones for UDP, including any service that can tolerate packet losses and requires low latency: gaming, voice, video, stock tickers, etc. The only ideas and code at this time is what is linked in my first post above.

**Comment by spericas** [comment]
@denismakogon Hi, could you review the latest comments?

**Comment by trentjeff** [comment]
In my opinion all of the async methods should be removed, as that should be the responsibility of a higher level of abstraction over the base, blocking send methods - ideally provided by the developer and not by Helidon.

**Comment by denismakogon** [comment]
Thank you for making it possible, that's more than I could've expected to see. The only thing I have is the performance. Have you tried to generate some load against one of the examples shared above?

**Comment by spericas** [comment]
@trentjeff Perhaps, but often we find that there's need to propagate context and asking the user to handle that is too much. I think they belong to the core --as in other similar APIs like Web Sockets. 

@denismakogon There's no implementation of the API, just a sketch :) Obviously, performance is crucial for this API to be of any real use.

**Comment by spericas** [comment]
Closing to continue discussion in #5629.
