### ISSUE TITLE
Example Dockerfiles: migrate off of openjdk images and upgrade JDK version.

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#5209]
In our example Dockerfiles we use docker images that are based on openjdk docker images (from dockerhub). These have been EOL'd so we need to migration off of them -- at least for Helidon 3 (Java 17) and newer.

One example of problems this causes is #5048 . In this case we need at least Java 17.0.3. The openjdk docker images stop at 17.0.2

**Comment by Captain1653** [comment]
I can try to do it, but I have some questions:
1. Which new images should be used? [Official statement](https://github.com/docker-library/openjdk/issues/505) tells about Eclipse Temurin. There are images: [one](https://hub.docker.com/layers/library/maven/3.9.0-eclipse-temurin-17-alpine/images/sha256-6263b6ebe1682a0d54afc4b5d5d8b156771a46821aef5e26fdae589a523f5ff7?context=explore) and [two](https://hub.docker.com/layers/library/eclipse-temurin/17.0.3_7-jdk-alpine/images/sha256-c6622d0d0272a913dbebda7376af4ce2b1e2a296c8154e9cbbdf3d5d3fb4e763?context=explore) for example. These or different?
2. Should I change these two places? Right?
<img width="1047" alt="Screenshot 2023-02-26 at 21 06 26" src="https://user-images.githubusercontent.com/4740207/221431400-12a4d9b2-ff2e-4fad-8e1f-eb09e1061c8c.png">

3. How can I check my changes? Should I run the docker image?

Any advice will be appreciated. :)

**Comment by barchetta** [comment]
@Captain1653 thanks for your interest in this issue. There are some additional complexities that we are working through. So this might not be a good issue for an outside contributor.
