### ISSUE TITLE
Reactive WebServer/WebClient - measuring request telemetry

### ISSUE THREAD

**Issue by janotav** [helidon-io/helidon#5229]
Team,

I am currently adding basic telemetry to our Helidon based service. In a nutshell, our service is a simple web-based proxy that receives a request, forwards it to appropriate target and then sends back the proxied result to the original client.

In order to correctly asses our performance I would like to emit following metrics as accurately as possible:

- overall request time (as perceived by client who calls us)
- upstream request time (our perception of the time it took the target to respond)

From these two, we would then imply our overhead as **$overall_time** - **$upstream_time.**

Considering that Helidon (very successfully) shields me away from the gory details of reading/writing actual bits over the network, the best I could come up with are these approximations:

```
overall_time = 
  time after all proxied response data were sent (see bellow)
  -
  time of invocation of the Authentication Security Provider we register (which is the earliest callback available as authentication is performed earliest)
```
  
```
upstream_time =
  time after all response data from upstream are consumed (proxiedResponse.content().onComplete)   
  -
  time after the OutboundSecurityProvider responsible for singing the outgoing request completes  
```  
  
In a pseudo-code:

```
private void requestHandler(ServerRequest request, ServerResponse response) {
         // ... this is the incoming request handler, a lot of things omitted  ...
         // the request came though Authentication Security provider where overallTimer is started
         client
           .post()
           .submit(request.content()) // this request goes through OutBoundSecurity provider where upstreamTimer is started
           .thenAccept(proxiedResponse -> {
               Single<ServerResponse> serverResponse = response.send(proxiedResponse
                      .content()
                      .onComplete(upstreamTimer::stopTime));
               serverResponse.thenRun(() -> {
                   overallTimer.stopTime();

```

Do these approximation look reasonable? Is there a better way how to estimate these?

**Comment by tjquinno** [comment]
Hi, @janotav 

A couple thoughts...

Are you registering the authentication provider yourself when you construct the routing for your service? (I assume so.) It probably does not make much difference in terms of the timings you would observe, but it might be a little clearer if you register a separate handler for the paths of interest _before_  all others that affect that path with the only job of arranging the timing of the request.

This makes it easier to add, remove, or rearrange your various handlers as you construct the routing. It's more obvious where the timing-related handler should go and it keeps the timing code out of other handlers or services, the auth. handling in particular.

The other thing I'd suggest is updating the timer using `ServerResponse.whenSent`. Helidon invokes your consumer and passes the `ServerResponse` very late in Helidon's processing of the response. (Helidon ultimately hands the response off to Netty to actually transmit it to the client, so there is some more work done to send the response out to the client, but `whenSent` is as late in the response's life cycle that Helidon can give you control.)

Your `Main` class might look like this (patterned somewhat after the Helidon SE QuickStart example). (By the way, there are multiple ways of accomplishing this; I'm showing just one simple one). Of course, the code below comes without warranty or support!

```
public final class Main {
    private static SimpleTimer myTimer; // You will use this to time the requests of interest.

    private static Routing createRouting(Config config) {
        MetricsSupport metrics = MetricsSupport.create();
        ....
        // You might want to supply explicit Metadata for the simple timer but this is shorthand.
        myTimer = RegistryFactory.getInstance()
                .getRegistry(MetricRegistry.Type.APPLICATION)
                .simpleTimer("myTimer");
        ...
        return Routing.builder()
                .any("/yourPath", Main::timeMyRequestProcessing), Main::requestHandler) // Timer set-up first, then your handler
                .register(metrics)
                .build();
    }

    private static void timeMyRequestProcessing(ServerRequest request, ServerResponse response) {
        long start = System.nanoTime();
        response.whenSent()
                .thenAccept(resp -> {
                    // You can look at the response status if you don't want to pollute the timer with non-200 results, for example.
                    myTimer.update(Duration.ofNanos(System.nanoTime() - start));
                })
                .exceptionallyAccept(t -> {
                    // Add code to deal with errors.
                });
        request.next();
    }
 ```

I haven't included the registration of the security service in `createRouting`, but you get the idea. 

The one new handler both records the start time and also sets up the callback to your code to update the timer once the response has been sent.

----
I'll leave the issue open for a bit. Close it yourself if you're satisfied with what I've said, or I'll close it in a while.

Hope this helps.

**Comment by janotav** [comment]
Thanks for the suggestions! I am going to revisit the code based on these hints.
