### ISSUE TITLE
Helidon - Nima Is there any metrics on virtual thread running state.

### ISSUE THREAD

**Issue by joeyleeeeeee97** [helidon-io/helidon#5255]
Also, for helidon MP, the spec in https://download.eclipse.org/microprofile/microprofile-metrics-4.0/microprofile-metrics-spec-4.0.html#_thread_jvm_stats is not really specific about weather `virtual thread` should be included?

Thanks

**Comment by tjquinno** [comment]
Currently in Nima there is no visibility into any virtual thread metrics.

The current (and preceding) implementation of the family of base metrics, including thread data, uses Java management beans. This is from the JavaDoc for the `ThreadMXBean`:
> The management interface for the thread system of the Java virtual machine.
ThreadMXBean supports monitoring and management of platform threads in the Java virtual machine. Platform threads are typically mapped to kernel threads scheduled by the operating system. ThreadMXBean does not support monitoring or management of virtual threads.

Note the explicit mention of the management bean dealing with _platform threads_ and then the last sentence.

The jep-425 virtual threads document refers to only one enhancement to management beans related to virtual threads https://openjdk.org/jeps/425#Java-Management-Extensions-JMX, and that is to be able to trigger virtual thread dumps. That is not useful for metrics.

Java Flight Recorder has been enhanced with various virtual thread-related events, but again that technology is not suited to use in gathering and reporting metrics.

In the absence of meaningful data on virtual threads (and a way to access them), there is not much Helidon Nima can do about this.
