### ISSUE TITLE
Allow CORS dependency to be "softer" for health, metrics

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#5291]
## Environment Details
* Helidon Version: 3.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
Currently, health and metrics "extend" the `service-common/rest` component, and that has a hard built-time dependency on `helidon-webserver-cors`. 

We might want to see if we could make the dependency softer so not every service would have to include the CORS component (about 65K bytes). That would place a burden on developers to add a runtime dep. on CORS to their projects if they wanted CORS support at runtime.

## Steps to reproduce
```bash
cd health/health
mvn dependency:tree
```
`helidon-webserver-cors` will always be there.

**Comment by m0mus** [comment]
Won't fix
