### ISSUE TITLE
Nima: ReadableEntityBase

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#5388]
HTTP media - `ReadableEntityBase` TODO

**Comment by arjav-desai** [comment]
There is already an auto drain in place in Http1Connection.consumeEntity. See https://github.com/helidon-io/helidon/blob/main/nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http1/Http1Connection.java#L341

So just removing the comment as we don’t need to do anything is this case.
