### ISSUE TITLE
4.x: Pico and builder follow up

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#5440]
Follow up issues for builders and Pico API:

- [x] #5447
- [x] Current `@Annotated` allows only marker annotations, not annotations with values. Some annotations may only support fields, some methods - do we check this?
- [ ] #6231
- [x] #5578
- [x] Version ID recorded in builder-generated meta attributes (extensible for config-builder also); used for backwards interop
- [x] #5609
- [x] #5608
- [x] Use of assert() - should they stayor should they go? - If we decide to remove asserts(), then followup task is to remove them from #5598
- [x] #5712
- [x] #5978

Split off some tasks to https://github.com/helidon-io/helidon/issues/6221

**Comment by trentjeff** [comment]
Addressed in https://github.com/helidon-io/helidon/pull/5750
