### ISSUE TITLE
The documentation about the messaging support for native-image is incomplete - nothing said about missing JMS support

### ISSUE THREAD

**Issue by Majestry** [helidon-io/helidon#5478]
## Environment Details
* Helidon Version: 3.0.2
* Helidon MP
* JDK version: OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06)
* OS: MacOS Ventura Version 13.0.1 (22A400)

----------

## Problem Description
The documentation for the messaging support in the native-image section is incomplete: it's impossible to use Messaging/JMS with the native image.
The output of the building native-image executable: 
`[INFO] 2022.11.18 16:59:07 SEVERE io.helidon.common.HelidonFeatures Thread[main,5,main]: Feature 'JMS Connector' for path 'Messaging/JMS' IS NOT SUPPORTED in native image. Image may still build and run.`

## Steps to reproduce 
Example simple project is here: https://github.com/Majestry/helidon-native-check
Simply run mvn package -Pnative-image and observe the output. After the build is completed launch the executable.

**Comment by danielkec** [comment]
We don't have and never had `documentation for the messaging support in the native-image section`. Helidon's Reactive Messaging and JMS connector are native image friendly. Problem's are 3rd party JMS clients but that's outside the Helidon scope.
