### ISSUE TITLE
[4.x] - Tracing Test Fail

### ISSUE THREAD

**Issue by dalexandrov** [helidon-io/helidon#5487]
Intermittent:

```
io.helidon.tracing.tests.it1.OpentraceableClientE2ETest.e2e  Time elapsed: 0.358 s  <<< FAILURE!
java.lang.AssertionError: 
Expected: a collection with size <0>
     but: collection size was <1>
```

**Comment by tomas-langer** [comment]
Failing (quite consistently) on local machine.
Disabling test.

**Comment by tomas-langer** [comment]
Test is now refactored, I will create a PR soon.

**Comment by tomas-langer** [comment]
This should now be fixed. There was an interference from the other unit test, as it would create a span, activate it and then never closes the scope. I have refactored the filter tests to run on a different thread, so the thread local does not impact any other code.
