### ISSUE TITLE
[4.x] - Nima Fault Tolerance Bulkhead Test Fail

### ISSUE THREAD

**Issue by dalexandrov** [helidon-io/helidon#5488]
Intermittent:

```
io.helidon.nima.faulttolerance.BulkheadTest.testBulkhead  Time elapsed: 2.015 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <java.util.concurrent.ExecutionException> but was: <java.util.concurrent.TimeoutException>``

**Comment by tomas-langer** [comment]
Seen the same case on local builds and in pipeline:
https://github.com/helidon-io/helidon/actions/runs/3543404482/jobs/5949830584

**Comment by tomas-langer** [comment]
Reproduced even locally (repeated the test 10000 times)

**Comment by tomas-langer** [comment]
Disabling this test in my next PR, until it is fixed.

**Comment by spericas** [comment]
I can also get a failure if executed 10K times. The failure is related to the rejection of the third task when there's no more room in the bulkhead.
