### ISSUE TITLE
[3.x] Multi.flatMapCompletionStage operator returns null instead of optional

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon#5496]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.x,3.x,4.x
* Helidon SE

----------

## Problem Description
While javadoc for Multi.flatMapCompletionStage claims to return optional:
```
     * Transform item with supplied function and flatten resulting {@link java.util.concurrent.CompletionStage} results
     * to downstream. As reactive streams forbids null values, CompletionStage result is mapped to
     * {@link java.util.Optional}.
```
It returns raw value or null which is forbidden in reactive stream

Backports:
- [ ] #5617
- [ ] #5618

**Comment by m0mus** [comment]
Fix the javadoc.
