### ISSUE TITLE
DBClient transaction in conjunction with UCP does not immediately release the connection back to the pool in case of exception within transaction

### ISSUE THREAD

**Issue by AshwinPrabhuB** [helidon-io/helidon#5509]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: Helidon 2.5.x
* Helidon SE or Helidon MP Observed in MP, but should be applicable to SE as well
* JDK version: 17.X
* OS: OS X

----------

## Problem Description
If a custom or JDBC exception is thrown from within DBClient.inTransaction(tx -> <chain-throws-exception>) quickly exhausts the connection pool. The source of the exception is immaterial as long as it is not handled within the Function chain that is passed into inTransaction.

Why throw an exception?
Mostly to signal a failure to the next in the chain of the inTransaction() that something unexpected occurred. The chain could short circuit into its nearest error handler or fail depending on its construct. Worst case, a unhandled JDBC exception could bubble out to inTransaction.

When a series of such exceptions occur in a short duration, it is observed particularly with small pool sizes that the pool get saturated and starved off connections. Subsequent requests for connections timeout and return no connection errors for a short period until the blocked connections are returned to the pool eventually. 

It is not clear why these connections need to be blocked for longer than required in case of an unhandled exception within the transaction. The behavior is different with DBClient.execute where it returns the connections immediately after Function executes exceptionally or normally.

## Steps to reproduce
Just throw some RunTime exceptions within DBClient.inTransaction and have a small connection pool. Doing this back to back will lead to pool exhaustion.

**Comment by arjav-desai** [comment]
We have this test https://github.com/helidon-io/helidon/blob/helidon-2.x/dbclient/jdbc/src/test/java/io/helidon/dbclient/jdbc/JdbcClientTest.java#L52 and it does close the connection i.e. https://github.com/helidon-io/helidon/blob/helidon-2.x/dbclient/jdbc/src/main/java/io/helidon/dbclient/jdbc/JdbcDbClient.java#L261. Can you please share a code snippet for your test?

**Comment by arjav-desai** [comment]
We dont support UCP with DBClient as of now, see https://github.com/helidon-io/helidon/issues/1589, so wondering how have you set that in your usage as well.

**Comment by AshwinPrabhuB** [comment]
```

// Step 1: Prepare my own instance of UCP
PoolDataSource dataSource = // initialize UCP here..


// Step 2: Helidon DBClient creation with connectionPool supported by above pool instance

DbClient dbClient = new io.helidon.dbclient.jdbc.JdbcDbClientProvider()
        .builder()
        .config(Config.create().get("db"))
        .connectionPool(_dataSource::getConnection) 
        .build();
```
Here is the documentation for functional interface for connection pool:
https://helidon.io/docs/v2/apidocs/io.helidon.dbclient.jdbc/io/helidon/dbclient/jdbc/ConnectionPool.html#connection()

In the above example _dataSource::getConnection would throw connection exceptions, so in real code this would be supplied via a wrapped method that handles and logs the connections creation failures.

**Comment by AshwinPrabhuB** [comment]
The issue is not about the connection not being released, rather it is about the connection held up and not closed for many seconds (eons in CPU time) in case of errors in dbclient.intransaction. The same behavior is not exhibited by dbclient.execute, which demonstrates there is some functionality in the transaction flow which is delaying/queueing the connections for longer than it should.

The falloff of this problem is the pool is exhausted instantly, creating a chokepoint in the service sporadically whenever such an event occurs.

**Comment by AshwinPrabhuB** [comment]
Also please include this in 2.5.5 series where the bug was originally reported.
