### ISSUE TITLE
List should be supported in the default config mappers

### ISSUE THREAD

**Issue by trentjeff** [helidon-io/helidon#5579]
See BasicConfigBeanTest

`
        Config cfg = Config.create(
                ConfigSources.create(
                        Map.of("name", "server",
                               "port", "8080",
                               "description", "test",
                               "pwd", "pwd1"
//                               , "cipher-suites", "a,b,c" // no List mapper available --- discuss w/ tlanger
                        ),
`

**Comment by tomas-langer** [comment]
Config supports reading any string as list, splitting it by commas. So this issue I think can be closed, as it is already supported.
We cannot treat comma separated strings as lists by default (e.g. the type of config node will be value), as we cannot "guess" if it is intended to be a simple string or a list (unless the underlying source can do that)
