### ISSUE TITLE
Validate security example

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#5630]
The example: https://github.com/helidon-io/helidon/tree/helidon-3.x/examples/security/basic-auth-with-static-content
uses `/{*}` path, which should evaluate to a wrong regular expression (I think)

Please validate that all the paths are correctly protected (for any resource, including subpaths). If anything fails, it may be good to add test to make sure it works as intended.

**Comment by dalexandrov** [comment]
I have tried the example, tested manually and automated through all of the cases. I found no issues.
