### ISSUE TITLE
4.x: Use `https` in `pom.xml` schemLocation

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#5657]
The schema location in pom file uses (mostly) `http://maven.apache.org/xsd/maven-4.0.0.xsd`. This should be changed to `https` endpoint.

**Comment by Captain1653** [comment]
Should I create separated issues for 2.x and 3.x ?

**Comment by romain-grecourt** [comment]
Yes.

**Comment by Captain1653** [comment]
@tomas-langer This issue is done and can be closed.
