### ISSUE TITLE
[nima][se] IllegalStateException("OutputStream already obtained"), when ErrorHandler uses ServerResponse.outputStream()

### ISSUE THREAD

**Issue by rbygrave** [helidon-io/helidon#5685]
## Environment Details
* Helidon Version:  4.0.0-SNAPSHOT / main
* Helidon SE 
* JDK version:  19.0.1
* OS: Linux

----------

## Problem Description
1. A Handler calls `ServerResponse.outputStream()`
2. Some exception occurs before any content has been sent, there are 0 bytes written 
3. A registered ErrorHandler uses `ServerResponse.outputStream()` in an attempt to write error response content
4. This fails with `IllegalStateException("OutputStream already obtained");`

Thrown at: https://github.com/helidon-io/helidon/blob/main/nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http1/Http1ServerResponse.java#L149-L151

### Option A: 
In ErrorHandlers.handleRequestException() when isSent() is false the "reset" the internal state of Http1ServerResponse such that it is ready for the error handler to set new headers and response content.  Set streamingEntity to false, set outputStream to null, clear the response headers?

https://github.com/helidon-io/helidon/blob/main/nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/http/ErrorHandlers.java#L142-L160
... if isSent() is false **_reset_** the ServerResponse 

### Option B:
Allow multiple calls to `ServerResponse.outputStream()` as long as isSent is false.

### Background: The old world `ServletResponse.reset()`

In the old world `ServletResponse` there are methods: 
- `isCommitted()` to indicate if some response content has been sent which is pretty similar to `isSent()`
- `reset()` to reset headers and any response buffers such that new content can be send (typically an error message).  reset() is only allowed to be called when isCommitted() is false.

Currently, `io.helidon.nima.webserver.http1.Http1ServerResponse` does not have an equivalent to the `ServletResponse.reset()` method.

## Steps to reproduce

I will look to produce an example test case that reproduces this issue and update this issue when I've done that. 
```
git clone git@github.com:rbygrave/nima-error-handler.git
cd nima-error-handler
mvn clean test

```

https://github.com/rbygrave/nima-error-handler/blob/main/src/test/java/org/example/MainTest.java

```java
package org.example;

import io.avaje.http.client.HttpClientContext;
import io.helidon.common.http.Http;
import io.helidon.nima.webserver.WebServer;
import io.helidon.nima.webserver.http.HttpRouting;
import org.junit.jupiter.api.Test;

import java.io.OutputStream;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;

import static org.assertj.core.api.Assertions.assertThat;

class MainTest {

  public static void main(String[] args) {
    int port = new MyServer().port(8081).run();
    System.out.println("Running on port " + port);
    // curl -v http://localhost:8081/bad
  }

  static class MyServer {
    WebServer webServer;
    int port;

    MyServer port(int port) {
      this.port = port;
      return this;
    }

    int run() {
      final var builder = HttpRouting.builder()
        .get("good", (req, res) -> {
          res.status(Http.Status.OK_200);
          res.send("good".getBytes(StandardCharsets.UTF_8));
        })
        .get("bad", (req, res) -> {
          res.status(Http.Status.OK_200);
          OutputStream outputStream = res.outputStream();
          // error occurs before writing content to outputStream
          throw new RuntimeException("Error After res.outputStream() called");
        })
        .error(Exception.class, (req, res, e) -> {
          res.status(Http.Status.I_AM_A_TEAPOT_418);
          res.send("MyErrorMessage".getBytes(StandardCharsets.UTF_8));
        });

      webServer = WebServer.builder()
        .addRouting(builder.build())
        .port(port)
        .start();
      return webServer.port();
    }

    void stop() {
      webServer.stop();
    }
  }

  private static HttpClientContext httpClient(int port) {
    return HttpClientContext.builder()
      .baseUrl("http://localhost:" + port)
      .build();
  }

  @Test
  void good_expect_200AndGoodBody() {
    MyServer myServer = new MyServer();
    try {
      int port = myServer.run();
      var httpClient = httpClient(port);

      HttpResponse<String> goodResponse = httpClient.request().path("good").GET().asString();
      assertThat(goodResponse.statusCode()).isEqualTo(200);
      assertThat(goodResponse.body()).isEqualTo("good");
    } finally {
      myServer.stop();
    }
  }

  @Test
  void bad_expect_418AndErrorHandlerBody() {
    MyServer myServer = new MyServer();
    try {
      int port = myServer.run();
      var httpClient = httpClient(port);

      HttpResponse<String> badResponse = httpClient.request().path("bad").GET().asString();
      // we hope to get our error handler response, but we don't get it due to internal error
      assertThat(badResponse.statusCode()).isEqualTo(418); // Fail: Get 500
      assertThat(badResponse.body()).isEqualTo("MyErrorMessage");
    } finally {
      myServer.stop();
    }
  }
}


```

**Comment by rbygrave** [comment]
PR that fixes the test - https://github.com/helidon-io/helidon/pull/5694

**Comment by tomas-langer** [comment]
This issue is now fixed for cases where `OutputStream` is used, including when user uses try with resources.
It only fails when bytes were actually written over the network (as this writes status and headers). In such a case, the connection is terminated in HTTP/1.1, and RST_STREAM is sent in HTTP/2 to notify the client that this is wrong (such as when we write bytes and then throw an exception before fully writing the response entity).
