### ISSUE TITLE
module-info parsing

### ISSUE THREAD

**Issue by trentjeff** [helidon-io/helidon#5697]

**Comment by trentjeff** [comment]
Currently, Pico Tooling provides a parser for module-info (introduced in #5598).

Ideally we would be using a parser provided by the Java team.  However, the java team does not provide a source-capable parser for module-info.  It provides other options including:
* https://docs.oracle.com/javase/9/docs/api/java/lang/module/ModuleDescriptor.Builder.html - the problem here is it does not expose the stringified version of the builder output, plus it will not be capable of preserving comments / CDATA like info.
* [APT processing via Module](https://docs.oracle.com/en/java/javase/11/docs/api/java.compiler/javax/lang/model/element/ModuleElement.html) - the problem here is it is in binary form, and also not useful for our maven-plugin entry points.

The PoR will be to (a) file an enhancement request on the Java team, and (b) use this task to eventually refactor the implementation so we can avoid having Helidon code parse the module-info directly.

**Comment by romain-grecourt** [comment]
See https://docs.oracle.com/en/java/javase/19/docs/api/java.compiler/javax/lang/model/element/ElementKind.html#MODULE

**Comment by trentjeff** [comment]
@romain-grecourt https://docs.oracle.com/en/java/javase/19/docs/api/java.compiler/javax/lang/model/element/ElementKind.html#MODULE is not good here since it is only dealing with the binary/compiler/APT processing.  We have maven-tooling that needs to work also, and something that we can access, parse and mutate the source form - ideally also preserving comments.

**Comment by trentjeff** [comment]
Mutation happens on a copy.
________________________________
From: Romain Grecourt ***@***.***>
Sent: Thursday, December 15, 2022 6:29:08 PM
To: helidon-io/helidon ***@***.***>
Cc: Jeff Trent ***@***.***>; Assign ***@***.***>
Subject: [External] : Re: [helidon-io/helidon] module-info parsing (Issue #5697)


  *   AFAIK annotation processing is done against source code not binary.
  *   Mutating source seems like a very bad idea.
  *   See the hack I did (here<https://urldefense.com/v3/__https://github.com/helidon-io/helidon-build-tools/blob/3.0.1/cli/codegen/src/main/java/io/helidon/build/cli/codegen/FileHeaderJavacPlugin.java__;!!ACWV5N9M2RV99hQ!NagVa_TuHrluh75KKoiHUXyBoAsLpRVYIUC_L8rpJUtk-I6dYGuWAUUQW05AGfkK4HkI5JmmN0YiH4F31Opdl21RKg$> and here<https://urldefense.com/v3/__https://github.com/helidon-io/helidon-build-tools/blob/3.0.1/cli/impl/pom.xml*L195__;Iw!!ACWV5N9M2RV99hQ!NagVa_TuHrluh75KKoiHUXyBoAsLpRVYIUC_L8rpJUtk-I6dYGuWAUUQW05AGfkK4HkI5JmmN0YiH4F31OoDx06rWw$>) for the helidon cli ; it gets the copyright headers of the processed classes so that we also put it in the corresponding generated code.

**Comment by trentjeff** [comment]
todo: research viability for using https://www.programcreek.com/java-api-examples/?api=com.github.javaparser.ast.modules.ModuleDeclaration

**Comment by tomas-langer** [comment]
This is already implemented for the required use cases.
We have abandoned updates to module info, and we handle all using Helidon Service Registry (with its custom service lookup.
