### ISSUE TITLE
Intermittent failure in CipherSuiteTest

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#5701]
I get the following intermittent error in pipelines (at least 5 times already):
```
Error:  Failures: 
Error:    CipherSuiteTest.testUnsupportedAlgorithm:108 
Expected: an instance of javax.net.ssl.SSLHandshakeException
     but: <java.lang.IllegalStateException: (client reqID: 3) Connection reset by the host> is a java.lang.IllegalStateException
```

Findings after first analysis:
Test fails because the connection is sometimes closed before we receive the SSL Handshake Failure. 
The exception (as can be seen above) claims the connection was reset by host, so the server probably issues a close before the correct SSL error is sent back. I could not find the problem on the server side.
As this is a critical test failure that is blocking our pipelines, I have created a temporary fix that accepts connection close as a valid error. This must be fixed before release.
Could not reproduce on local Linux or MacOS, only fails on pipeline environment (Github Actions)

**Comment by barchetta** [comment]
I see this on the 2.x and 3.x pipelines as well.

**Comment by Verdent** [comment]
CipherSuiteTest reintroduced in Helidon 4 branch by PR #7587 and was rewritten.
