### ISSUE TITLE
OIDC Multi-tenancy Support Documentation

### ISSUE THREAD

**Issue by trentjeff** [helidon-io/helidon#5723]
I made a PR review comment for https://github.com/helidon-io/helidon/pull/5168 but it seems to have gone unaddressed. Issue https://github.com/helidon-io/helidon/issues/4936.

This is a notable big feature and needs documentation.  I'd also even suggest we write a blog on this feature as well.

**Comment by ljamen** [comment]
Please work with @Geetha-Savithriamma to create the documentation.

**Comment by trentjeff** [comment]
@Verdent @m0mus can we get this in for M2?
