### ISSUE TITLE
Support customization of 'logout-uri' in OIDC provider

### ISSUE THREAD

**Issue by tirunagaris** [helidon-io/helidon#5731]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 3.0.1
* Helidon SE or Helidon MP : both
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
Config option is missing for 'logout-uri' in the OIDC provider. Its always defaulted to "/oidc/logout", which is blocking from supporting logout for multiple application instances in k8s.

There needs a fix in `OidcConfig.Builder::build(Config)` for customizing 'logout-uri'

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

**Comment by tirunagaris** [comment]
There is detailed discussion related to this issue in slack group, below is the link
https://gbu-core.slack.com/archives/C9Y1RM1FG/p1671537463664529

**Comment by romain-grecourt** [comment]
@tirunagaris please include the relevant part of the discussion you mentioned.

**Comment by tirunagaris** [comment]
We are using OIDC Provider of Helidon(3.0.1) with OAM (12.2.1.4) as OAuth server with the below mentioned `logout-endpoint-uri` value in application.yaml file, which is the IdP(OAM) provided logout uri that the OidcSupport service is invoking for oidc logout request path (`http://HOSTNAME:PORT/oidc/logout`).
 
>      - oidc:
>                  ...... 
>                  logout-endpoint-uri: http://OAM_HOST:OAM_PORT/oam/server/logout 

We are trying to change the logout request path of application (by default the path is mapped as `http://HOSTNAME:PORT/oidc/logout` when we enable OIDC support).

Observed that this is the value of `logout-uri` of OIDC provider that's mapped to `/oidc/logout` by default and is not configurable.

For matching to the appropriate back-services in the ingress controller, we need to prefix a namespace to the mapping path of our application. (e.g., `http://HOSTNAME:PORT/namespace1/oidc/logout`)

As per Tomas Langer(@tlanger),
_"It seems that we have missed this one from our configuration. There is a customizable logout-uri, but we do not have a config option for it."_

As per Santiago Pericas-Geertsen(@spericas),
_"Yes, please file an issue on Github and will try to fix it ASAP. Seems like a one-liner in OidcConfig.Builder::build(Config)."_

**Comment by tirunagaris** [comment]
Our application release is dependent on this issue fix.
Can this issue be prioritized to release in 3.1.0 patch?
