### ISSUE TITLE
API is throwing MappableException after helidon and jersey upgrade

### ISSUE THREAD

**Issue by userdev12333** [helidon-io/helidon#5775]
We recently upgraded helidon to 2.5.4 and jersey version to 2.35. We are seeing the below exception in one of our APIs. This worked fine with older helidon(2.0.2)/jersey(2.29.1) versions.Not sure if this is caused by the latest upgrade.
Can you please help to resolve this error?

`{"level":"ERROR","logger":"org.glassfish.jersey.server.ServerRuntime$Responder","thread":"jersey-thread-7","ts":1671639547627,"x-request-id":"","msg":"An I/O error has occurred while writing a response message entity to the container output stream.:\norg.glassfish.jersey.server.internal.process.MappableException: java.io.IOException: Bad news: the stream has been closed\n\tat org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:67)\n\tat org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)\n\tat org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116)\n\tat org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:635)\n\tat org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:373)\n\tat org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:363)\n\tat org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:258)\n\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)\n\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:292)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:274)\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:244)\n\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)\n\tat org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)\n\tat org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)\n\tat io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$doAccept$4(JerseySupport.java:335)\n\tat io.helidon.common.context.Contexts.runInContext(Contexts.java:117)\n\tat io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$7(ContextAwareExecutorImpl.java:154)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: java.io.IOException: Bad news: the stream has been closed\n\tat io.helidon.webserver.jersey.ResponseWriter$DataChunkOutputStream.awaitRequest(ResponseWriter.java:327)\n\tat io.helidon.webserver.jersey.ResponseWriter$DataChunkOutputStream.write(ResponseWriter.java:186)\n\tat org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:200)\n\tat org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:276)\n\tat com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2171)\n\tat com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeBytes(UTF8JsonGenerator.java:1260)\n\tat com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeFieldName(UTF8JsonGenerator.java:284)\n\tat com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:726)\n\tat com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)\n\tat com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)`

**Comment by romain-grecourt** [comment]
CC @spericas

**Comment by userdev12333** [comment]
I also see the below warning whenever the mappableexception is encountered. please let me know how to fix it.

{"level":"WARN","logger":"io.helidon.webserver.BareResponseImpl","thread":"jersey-thread-1","ts":1671689369384,"x-request-id":"","msg":"Entity was requested and not fully consumed before a response is sent. This is not supported. Connection will be closed. Please fix your route for POST /av/api/v2/addressclean/","podname":"deployment-av-batch-0"}


Signature of the api is ,
        @POST
	@Path("addressclean")
	@Produces(MediaType.APPLICATION_JSON + "; charset=UTF-8")
	@Consumes(MediaType.APPLICATION_JSON + "; charset=UTF-8")
	@Timed(name="app_kpi",
		absolute = true,
		reusable = true,
		unit=MetricUnits.NANOSECONDS,displayName="test",
		tags = {"api=addressclean"})
	@Tag(name = "Version2")
	@APIResponse(responseCode = "200", description = "Success", content = @Content(schema = @Schema(type=SchemaType.ARRAY, implementation = OutputRecord.class)))
	@APIResponse(responseCode = "403", description = "Forbidden")
	@APIResponse(responseCode = "401", description = "Unauthorized")
	@APIResponse(responseCode = "500", description = "An unexpected error occurred during the request.")
	@Authenticated
	public Vector<OutputRecord> addressclean(@RequestBody(description = "An array of input records to be cleaned.", required = true,
            content = @Content(schema = @Schema(type = SchemaType.ARRAY, implementation = InputRecord.class))) Vector<InputRecord> inputRecords)

**Comment by spericas** [comment]
Also, what are you using as the HTTP client to access this resource?

**Comment by userdev12333** [comment]
Hi ,Please find my response below. 
1)what are you using as the HTTP client to access this resource? -reproducible with all client . We use curl for tests.
2)Have you implemented a JAX-RS message body reader to convert a JSON array into a Vector - No
3)Is it at all possible that the input stream for entity Vector inputRecords is not fully consumed? - We checked the input records size in the beginning of the api. It is intact. In case if it is still the cause for this issue, can you please provide a solution for this.

**Comment by spericas** [comment]
We cannot override/recover from this error. We need to (1) look at your implementation (is your code available?) and (2) understand how the payload is mapped to a `Vector`.

**Comment by spericas** [comment]
After more discussions with @userdev12333, we now know the app is using Jackson and the JAXB annotation `@XmlRootElement` for serialization. I have created a simple sample that attempts to capture the same codepath (using same Java binding types) but, at this stage, it is still not reproducing the problem. Perhaps Poorna or someone else can help us modify this app to show problem.

[issue-5775.zip](https://github.com/helidon-io/helidon/files/10375344/issue-5775.zip)

**Comment by userdev12333** [comment]
For us the issue was coming for the input size of 75k (bulk inputs). Smaller sized inputs are working fine.

**Comment by spericas** [comment]
Here is an updated version of the sample that seems to have problems writing a large JSON array; not sure if it is exactly the same issue reported here, but seems related.

[issue-5775.zip](https://github.com/helidon-io/helidon/files/10386564/issue-5775.zip)

**Comment by userdev12333** [comment]
Ok.thanks.Please let me know if we have an alternate way to handle large inputs or if we should revert to older versions of helidon/jersey.

**Comment by spericas** [comment]
We'll advise shortly. @danielkec is also looking at this.

**Comment by spericas** [comment]
@userdev12333 I have a couple of things for you to try as potential workarounds:

1. Set the following property to change backpressure strategy:
```
server.backpressure-strategy=AUTO_FLUSH
```

 2. If you don't set (1), you can also increase the backpressure buffer size as follows (or a larger value depending on your needs):
```
server.backpressure-buffer-size=10000000
````

**Comment by userdev12333** [comment]
@spericas I tried both the workarounds. But, none of them helped us to resolve the error.Please advise on the next step.

**Comment by spericas** [comment]
@userdev12333 We should schedule a zoom meeting to go over this. The sample application, which seems to duplicate the issue in this report, works just fine with the `AUTO_FLUSH` setting.

**Comment by spericas** [comment]
Additional testing done by @userdev12333 after setting `AUTO_FLUSH` was successful. Closing issue.

**Comment by spericas** [comment]
#5880
