### ISSUE TITLE
4.x: Upgrade MP OpenAPI to 3.1

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#5820]

**Comment by tjquinno** [comment]
It might be challenging to adopt MP OpenAPI 3.1 while still relying on SmallRye OpenAPI.

We need a new release (3.x) of SR OpenAPI to support MP OpenAPI 3.1. That depends on a new major release of the Jandex library (we have been using 2.4.3 and SmallRye now depends on 3.0.5) and there are backward-incompatible changes in the Jandex API. 

We have some of our own code in Helidon which I was able to adapt, but we also have dependencies on other libraries (e.g., hibernate-orm) which depend on the older Jandex API. I am looking for more recent versions of _those_ libraries which use the newer Jandex release but if those do not exist then we might need to withdraw this "low-impact" adoption of MP OpenAPI 3.1 in favor of the larger work to adopt the Swagger library.

**Comment by barchetta** [comment]
Because of the complexities with the Jandex upgrade I am moving this to M1.
