### ISSUE TITLE
Creation of a new Span also creates a new Trace

### ISSUE THREAD

**Issue by sherwoodzern** [helidon-io/helidon#5968]
## Environment Details
* Helidon Version: SE
* JDK version: 19
* OS: Not relevant
* Docker version (if applicable):

----------

## Problem Description

When creating new spans a new trace is created as well. This prevents seeing all desired spans within one trace.
The Span is created as such: 

```java
Span.Builder<?> sb = request.tracer().spanBuilder("myspan");
SpanContext sc = request.spanContext();
sc.asParent(sb);
sb.start();
```

If as above,  instead of using line 2 and line 3: I do the following:

```java
request.spanContext().ifPresent(sb::parent);
```
Then all spans will be included in one Trace. The code should behave the same way; IMO. If an error is being thrown
 when attempting to set the parent for the SB (first example) it is being dropped along the way somewhere.

**Comment by m0mus** [comment]
Adding a doc label to check is this case explained in our docs or not.

**Comment by tomas-langer** [comment]
Could you please clarify?
The following line does not work:
`SpanContext sc = request.spanContext();`
As in Helidon 3 (and considering `request` is `ServerRequest`), the method returns `Optional<SpanContext>`

**Comment by tomas-langer** [comment]
There is a flag set in `Span.Builder.parent()` which is missed in `SpanContext.asParent()`
