### ISSUE TITLE
Unable to use Jaeger Agent 

### ISSUE THREAD

**Issue by sherwoodzern** [helidon-io/helidon#5976]
## Environment Details
* Helidon Version: SE
* JDK version: 19
* OS: Irrelevant
* Docker version (if applicable):

----------

## Problem Description

Jaeger tracing provides an agent sidecar for the collecting of traces. The agent then connects to the
Jaeger collector. The use of the sidecar provides a number of benefits versus connecting directly to
collector. In order to communicate with the agent the Helidon application must use a protocol of UDP.
With the introduction of Helidon 3.x the use of openTelemetry does not support this protocol.

## Steps to reproduce

Deploy Jaeger as a sidecar using annotations - 

```
annotations:
    "sidecar.jaegertracing.io/inject": <either true or the name of Jaeger (kubectl get jaeger)>
```

In the application.yaml set the host to localhost and protocol to UDP. When the application executes 
an exception is thrown stating that the only valid protocol is http or https

**Comment by tomas-langer** [comment]
Current OpenTelemetry Jaeger API used by Helidon is version 1.15 (`io.opentelemetry:opentelemetry-exporter-jaeger`).
The javadoc for endpoint:
```
Sets the Jaeger endpoint to connect to. If unset, defaults to "http://localhost:14250". The endpoint must start with either http:// or https://.
```
This is why such an exception is thrown (udp is not supported as a protocol).

There are some backward incompatible changes that are not part of Helidon APIs, but of the integrated service - in this case Jaeger through OpentTelemetry

**Comment by tomas-langer** [comment]
Jaeger sidecar is not supported due to open telemetry not supporting the UDP protocol.
