### ISSUE TITLE
TckRecoveryTests.testCancelWhenParticipantIsUnavailable pipeline failures

### ISSUE THREAD

**Issue by spericas** [helidon-io/helidon#5985]
Saw it failed twice in pipeline, likely intermittent.

Error:  Failures: 
Error:    TckRecoveryTests.testCancelWhenParticipantIsUnavailable:195->assertMetricCallbackCalled:210 Expecting the metric Compensated callback was called
Expected: a value equal to or greater than <1>
     but: <0> was less than <1>

**Comment by danielkec** [comment]
Fixed with https://github.com/helidon-io/helidon/pull/5965/commits/191df818ff09f20dd0cb69e4feb8bc76f4442462
