### ISSUE TITLE
`ConfigSources.create(Config)` changes list nodes to object nodes

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#6102]
## Environment Details
* Helidon Version: 3.x (and 4.x)
* Helidon SE or Helidon MP SE
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
In `Config` structure created using `ConfigSources(Config)` list nodes are incorrectly converted to object nodes.

Similar to #2427 but apparently not the same.

## Steps to reproduce
Add the following to `YamlConfigParserTest` and run it:

```java
    @Test
    void testCopyWithArray() {
        ConfigParser parser = YamlConfigParser.create();
        ConfigNode.ObjectNode node = parser.parse(toContent("aaa:\n"
                                                                    + "  - bbb\n"
                                                                    + "  - ccc\n"
                                                                    + "  - ddd\n"));

        io.helidon.config.Config original = io.helidon.config.Config.builder()
                .disableKeyResolving()
                .disableValueResolving()
                .disableSystemPropertiesSource()
                .disableEnvironmentVariablesSource()
                .addSource(io.helidon.config.ConfigSources.create(node))
                .build();

        io.helidon.config.Config copy =
                io.helidon.config.Config.builder()
                .disableKeyResolving()
                .disableValueResolving()
                .disableSystemPropertiesSource()
                .disableEnvironmentVariablesSource()
                .addSource(io.helidon.config.ConfigSources.create(original))
                .build();

        assertThat("Node type of copied aaa", 
                   copy.get("aaa").type(), 
                   org.hamcrest.Matchers.is(original.get("aaa").type()));

    }
```
Result:
```
java.lang.AssertionError: Node type of copied aaa
Expected: is <LIST>
     but: was <OBJECT>
```

**Comment by tjquinno** [comment]
The use case that revealed this problem is this:

We want to let users provide, in config, some OpenAPI schema definitions like below:

`configWithSchemasWithRef.yaml`
```yaml
openapi:
  schemas:
    Pet:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
      description: Pet object that needs to be added to the store
      required: true
```
An external API we use expects a `Map<String, String>` which maps each schema name (`Pet`) to a JSON string representing the structure of that schema. 

OpenAPI documents allow users to use `$ref` to point to other declarations, but Helidon's config tries to translate those as config tokens when it first loads the config.

Adding the snippet below to `YamlConfigParserTest` and the yaml file above at `config/yaml/src/test/resources/configWithSchemasWithRef.yaml` and then running the added test triggers a token resolution exception for `ref` as the config tree is built.

```java
    @Test
    void checkSchemaMappingWithRef() {
        Config config = Config.just(ConfigSources.file(
                Paths.get("src/test/resources", "configWithSchemasWithRef.yaml").toString()));
    }
```

Of course, the YAML snippet above might be part of a larger config file so we would not want to disable token replacement for the entire config tree, but the config system seems to attempt token resolution when it builds the config tree, not when individual nodes are traversed, so it's not clear how we can support this use case.

**Comment by tomas-langer** [comment]
This is a bug and an enhancement.
Bug: key resolving was implemented in a way that could throw a concurrent modification exception
Enhancement: add support for `config.key-resolving.fail-on-missing-reference` configuration option. When set to `false`, key resolving will not fail on a token that is not recognized, and the key will contain the `$` symbol.
In the second example, it would be sufficient to add:
```yaml
config:
  key-resolving:
    fail-on-missing-reference: true
```
And the config will be parsed correctly, and the key can be accessed using:
```java
config.get("openapi.schemas.Pet.content.application/json.schema.$ref").asString();
```
and the result would be `#/components/schemas/Pet`

**Comment by tjquinno** [comment]
I see how that can help somewhat. There is always the chance that a config source _would_ resolve the token `ref` which is not what we want to happen in this use case.

Ideally, there would be a way to suppress token replacement in a _part_ of the config tree.

**Comment by tomas-langer** [comment]
I think that should be a separate issue - an enhancement to configure that. 
I cannot imagine the API or configuration options for that. It would be great if you also add that to the issue (e.g. what is the way the customer would set this up?). 
I can also see that such things should be either part of the meta-configuration, or part of the configuration itself (similar to what I have done for allowing unresolved key references, and what we already have for allowing unresolved value references)

**Comment by tomas-langer** [comment]
This issue is now resolved. Backports have separate issues as linked above.
