### ISSUE TITLE
java-dataloader-3.1.0 has an invalid Automatic-Module-Name manifest entry

### ISSUE THREAD

**Issue by aalmiray** [helidon-io/helidon#6133]
## Environment Details
* Helidon Version: 3.1.1
* Helidon SE, Helidon MP
* JDK version: N/A
* OS: N/A
* Docker version (if applicable): N/A

----------

## Problem Description
java-dataloader is a transitive dependency

```
[INFO] +- io.helidon.graphql:helidon-graphql-server:jar:3.1.1:compile
[INFO] |  \- com.graphql-java:graphql-java:jar:17.4:compile
[INFO] |     +- com.graphql-java:java-dataloader:jar:3.1.0:compile
[INFO] |     \- org.antlr:antlr4-runtime:jar:4.9.2:runtime
```

Its manifest defines an invalid automatic module name

```
Caused by: java.lang.module.FindException: Automatic-Module-Name: com.graphql-java: Invalid module name: 'graphql-java' is not a Java identifier
	at java.base/jdk.internal.module.ModulePath.deriveModuleDescriptor(ModulePath.java:505)
	at java.base/jdk.internal.module.ModulePath.readJar(ModulePath.java:644)
```

[v3.2.0](https://github.com/graphql-java/java-dataloader/releases/tag/v3.2.0) fixes this issue. I'd recommend upgrading when ready.

**Comment by barchetta** [comment]
The bad module name looks like it was first fixed in java-dataloader [3.1.1](https://github.com/graphql-java/java-dataloader/blob/v3.1.1/build.gradle)
