### ISSUE TITLE
Broken span hierarchy when using opentelemetry java agent

### ISSUE THREAD

**Issue by buttasam** [helidon-io/helidon#6174]
## Environment Details
* Helidon Version: 3.1.1
* Helidon MP
* JDK version: 17.0.5
* OS: macOS 13.1
* Docker version (if applicable):

----------

## Problem Description
Hi team,
we're fully migrating our codebase from opentracing to opentelemetry and decided to use [open telemetry java agent](https://github.com/open-telemetry/opentelemetry-java-instrumentation). This agent should be a pretty standard and convenient way how to handle tracing because we want to get rid of some third-party dependencies related to opentracing such as [opentracing-contrib/java-kafka-client](https://github.com/opentracing-contrib/java-kafka-client) and we're looking for a replacement. 

I created two very basic microservices based on Helidon, where the first one (`helidon-mp1`) calls the second one (`helidon-mp2`), to see whether the agent works.
The agent seems to be working, but traces look different from traces provided by Helidon without the agent. 

I have attached this project to this issue. The project contains README.md where can be found steps to reproduce.

The main difference is that traces with java agent have a different hierarchy of spans, see these examples:

1) Span `security:atn` should be a child of `security` as you can see on the first image (without agent) but with agent, the spans are on the same level.

Expected (without java agent):

<img width="267" alt="helidon-security-span-without-agent" src="https://user-images.githubusercontent.com/6898290/218517427-117710c5-ca1c-4ad7-bdbe-40eee8a0162d.png">

Actual (with java agent):
<img width="512" alt="helidon-security-span-with-agent" src="https://user-images.githubusercontent.com/6898290/218517423-29979dda-4a50-4fc4-9a54-947c8e6852b6.png">

2) When microservice (`helidon-mp1`) creates custom span (`custom-mp1-span-1`) which creates another nested span (`custom-mp1-span-2`) the hierarchy seems broken similarly as well.

Expected (without java agent):
<img width="501" alt="custom-spans-without-agent" src="https://user-images.githubusercontent.com/6898290/218517418-47254ef4-3c6e-45b6-9ba5-38cbef66f1ef.png">

Actual (with java agent):
<img width="324" alt="custom-spans-with-agent" src="https://user-images.githubusercontent.com/6898290/218517413-491b1cf4-10f1-4c20-861e-7572868524f0.png">

Additional version info:
- Opentelemetry java agent: `1.22.1`
- Jaeger: `1.41`

## Steps to reproduce
[Attached zip file with REAMDE](https://github.com/helidon-io/helidon/files/10724562/helidon-microservices-tracing.zip)

**Comment by trentjeff** [comment]
Note that I asked Samuel to file an issue on this - minimally we may need a documentation issue around this, but it may be more than that since the parenting of the span seems off in the above example.

**Comment by tjquinno** [comment]
_Possibly_ another manifestation of the same issue (no agent involved) from the public [#helidon-users slack channel](https://helidon.slack.com/archives/CCS216A5A/p1676539439153609)

I have attached the user-provided reproducer. See the slack thread for details.

[helidon-template-tracing.zip](https://github.com/helidon-io/helidon/files/11020161/helidon-template-tracing.zip)

**Comment by bogedal** [comment]
@dalexandrov @tjquinno 
Any timeline for this issue?
It currently blocks me from embracing Helidon 3.

**Comment by dalexandrov** [comment]
About to be fixed. PR will be submitted soon. Doing some final tests.
