### ISSUE TITLE
Níma: webclient complete shortcut methods for all HTTP methods

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#6184]
WebClient should have support for all mostly http methods (get, post, put, delete) in the API. We now have a general method that accepts `Http.Method`

Also refactor tests and examples that use the general method for common http methods

**Comment by klustria** [comment]
Is being worked on in PR https://github.com/helidon-io/helidon/pull/6358

**Comment by klustria** [comment]
PR https://github.com/helidon-io/helidon/pull/6358 is completed and merged.
