### ISSUE TITLE
Níma: webserver routing complete shortcut methods for all HTTP methods

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#6185]
We should copy the same shortcut methods we have in reactive Http Rules to Níma `HttpRules`  to support the same user experience.

**Comment by klustria** [comment]
HttpRules  is missing shortcut methods for TRACE and PATCH but has all the other shortcut methods for GET, POST, PUT, DELETE, and HEAD. HEAD, looks like it still needs: `head(Handler... handlers)`

**Comment by klustria** [comment]
This may need to be done as well in HttpRouting.Builder.

**Comment by klustria** [comment]
Completed PR https://github.com/helidon-io/helidon/pull/6404 to resolve this issue.
