### ISSUE TITLE
4.x: Examples structure

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#6187]
Move all reactive examples under `reactive` directory (and module) in `examples`

This task can be done in current repo (structure within `examples/reactive` or in a separate repo (probably `reactive` in repo root).

This is to align each flavor examlpes.

Examples for features that do not belong to a specific flavor will stay in root (such as `config`)

**Comment by ginaesps** [comment]
Hello!! Could you kindly assign me this task? I'll be working on it:)

**Comment by barchetta** [comment]
This has been resolved by #7201 and #7361
