### ISSUE TITLE
JPMS (module system) improvements

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#6188]
We need to make sure our modules are designed correctly:
- correct `requires static` - aligned with correct pom dependency (optional)
- correct `requires transitive` - aligned with public API of the module (all classes that form public API should have `requires transitive`)
- dependency on third party modules (below)

Third party modules tasks
- make sure third party dependencies have correct `module-info.java`
- ask providers of our dependencies to include correct `module-info.java`, if needed, help by submitting PRs against such projects. We should get rid of all module warnings for reactive, Níma, and Pico

Eventually we should be able to remove `-Xlint:-requires-automatic` from any module and compile with no warnings.

If a team member (or an external contributor) decided to start with any of our dependencies, please comment on this PR, so we can create an issue for that specific dependency to track the progress. Thanks!

**Comment by romain-grecourt** [comment]
`-Xlint:module` is very useful to identify issues in module info, we should consider having it enabled at the top-level.
