### ISSUE TITLE
Helidon does not support Baggage for Tracing

### ISSUE THREAD

**Issue by sherwoodzern** [helidon-io/helidon#6190]
## Environment Details
* Helidon Version: 3.1.x
* Helidon SE and Helidon MP
* JDK version: jdk 17+
* OS: any
* Docker version (if applicable): NA

----------

## Problem Description

Open Telemetry provides the functionality to add information across all spans using a Baggage. Sometimes you will want to add the same attribute to many spans within the same trace. These attributes may include variables calculated during your program, or other useful values for correlation or debugging purposes. At present, Helidon does not provide an API to add Baggage. In order to use a Baggage you will need to import the openTelemetry packages. Importing the openTelemetry may cause conflicts with openTelemetry versions that are used between Helidon and current versions of openTelemetry

**Comment by romain-grecourt** [comment]
Can you provide some explanation other than the title ?

**Comment by sherwoodzern** [comment]
I put an entire explanation in the problem description. Did it not show up?

**Comment by romain-grecourt** [comment]
The lines you added are not rendered because they are enclosed between `[//]: # "` and `"`
