### ISSUE TITLE
4.x: programmatically control media providers with Nima WebServer

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#6278]
While working on migrating the Bookstore test application to Nima WebServer I ran into a gap (or maybe it is ignorance on my part).

In 3.x I can add specific media support programmatically:

```
webserverBuilder.addMediaSupport(JsonpSupport.create());
```

I can't find a way to do that with Nima WebServer. Maybe I'm missing something but it seems to rely only on service loading of `MediaSupportProvider`s.  

Note that this is different than Features which have `useSystemServices()` to turn on/off auto loading of services and there are ways to programmatically add a feature using `addFeature`.

**Comment by Tomas-Kraus** [comment]
I'll have a look at this one.
