### ISSUE TITLE
Nima: Validate headers in ClientRequestImpl

### ISSUE THREAD

**Issue by klustria** [helidon-io/helidon#6338]
## Environment Details
* Helidon NIMA

----------

## Problem Description
This is spawned off of issue https://github.com/helidon-io/helidon/issues/5386. Explore adding header validation (configurable) for Client Request similar to Helidon SE WebClient.

**Comment by klustria** [comment]
This will be resolved by PR: https://github.com/helidon-io/helidon/pull/6515

**Comment by danielkec** [comment]
Follow up issue for HTTP/2 client #6547

**Comment by klustria** [comment]
PR https://github.com/helidon-io/helidon/pull/6515 is completed, hence closing this issue.
