### ISSUE TITLE
DOCS: 4.x WebClient SE Guide updates (Nima)

### ISSUE THREAD

**Issue by ljamen** [helidon-io/helidon#6402]
## Problem Description

We need to update docs for 4.x

- [ ] update webclient.adoc for SE
- [ ] update webclient.adoc guide for SE

## Guidelines

- [ ] Make sure any fixes from 3.x are forward ported to 4.x
- [ ] Initial focus is on correctness
- [ ] Record migration impact in this issue

## Migration Impact

Summarize incompatibilities between Helidon 3 and Helidon 4.
Summarize actions customers must take to migrate code
OK to reference external specs or documents (for example MicroProfile specs)

Tim made some comments about the webclient.adoc in this PR. Those change requests need to be reviewed. https://github.com/helidon-io/helidon/pull/6398#discussion_r1132776817

**Comment by klustria** [comment]
Additional Note: There were 2 issues that were filed during the course of working through this issue:
1. https://github.com/helidon-io/helidon/issues/7801
2. https://github.com/helidon-io/helidon/issues/7802
and both had been resolved in PR: https://github.com/helidon-io/helidon/pull/7804
