### ISSUE TITLE
Níma: shortcut methods for media support(s)

### ISSUE THREAD

**Issue by Tomas-Kraus** [helidon-io/helidon#6421]
Issue #6278 follow up.

In reactive, we can configure media support directly on web server builder. This would require a new interface (e.g. `MediaSupport`) to be created by the provider.
So users can register `JsonSupport.create()` instead of creating a new instance of a service loader provider implementation

**Comment by tomas-langer** [comment]
The new approach should support:
- customization of underlying features (custom ObjectMapper for Jackson, JSON-B and JSON-P as well)
- using config to set up the underlying features
- customizing supported media types

The config based approach would ideally work for the service providers as well, if feasible (e.g. if I construct my `MediaContext` from `Config`)
