### ISSUE TITLE
DOCS: 4.x WebClient

### ISSUE THREAD

**Issue by ljamen** [helidon-io/helidon#6456]
## Problem Description

We need to update docs for 4.x

- [x] update webclient.adoc for SE
- [x] update webclient.adoc guide for SE

## Guidelines

- [x] Make sure any fixes from SE 3.x are forward ported to 4.x #7515 
- [x] Make sure any fixes from MP 3.x are forward ported to 4.x
- [x] Initial focus is on correctness
- [ ] Record migration impact in this issue

## Migration Impact

Summarize incompatibilities between Helidon 3 and Helidon 4.
Summarize actions customers must take to migrate code
OK to reference external specs or documents (for example MicroProfile specs)

Tim made some comments about the webclient.adoc in this PR. Those change requests need to be reviewed. https://github.com/helidon-io/helidon/pull/6398#discussion_r1132776817

**Comment by klustria** [comment]
PR https://github.com/helidon-io/helidon/pull/7812 was created to resolve this issue

**Comment by ljamen** [comment]
Keeping issue open to track the webclient guide (SE Guides).

**Comment by klustria** [comment]
WebClient Guide and Documentation are completed with PRs https://github.com/helidon-io/helidon/pull/7812, https://github.com/helidon-io/helidon/pull/7845 and https://github.com/helidon-io/helidon/pull/7847

**Comment by klustria** [comment]
Migration Impact:
1. TLS setup has changed
2. Services setup has changed
3. Cookie management definition has changed
4. Built-in Media support can now be enabled by just adding their dependencies
5. Protocol configuration is a new setting
