### ISSUE TITLE
DOCS: 4.x Scheduling

### ISSUE THREAD

**Issue by ljamen** [helidon-io/helidon#6466]
## Problem Description

We need to update docs for 4.x

- [x] update scheduling.adoc for SE
- [x] update scheduling.adoc for MP
## Guidelines

- [x] Make sure any fixes from SE 3.x are forward ported to 4.x #7515 
- [x] Make sure any fixes from MP 3.x are forward ported to 4.x
- [ ] Initial focus is on correctness
- [x] Record migration impact in this issue

## Migration Impact

Summarize incompatibilities between Helidon 3 and Helidon 4.
Summarize actions customers must take to migrate code
OK to reference external specs or documents (for example MicroProfile specs)

**Comment by danielkec** [comment]
No changes or migration is needed
