### ISSUE TITLE
Validate usage of empty and just methods on Config usage in nima modules

### ISSUE THREAD

**Issue by arjav-desai** [helidon-io/helidon#6478]
While working on #5495 , found there there are some api's in helidon-config's Config class e.g. create, just and empty which are not available on helidon-common-config's Config; and hence can't be easily replaced.

This issue is to validate their usage and see if an alternative can be provided.

**Comment by tomas-langer** [comment]
`Config.just(...)` is only used from test scope

**Comment by tomas-langer** [comment]
Upgrading this issue to validate that `common-config` is used instead of `config` in Helidon modules that use `Config.empty()`
