### ISSUE TITLE
4.x: Configuration annotation processing and docs generation

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#6496]
Currently we process builders that are classes to generate JSON for usage for documentation and IDEs.
We need to update the processor to support new Builder APIs based on interfaces (e.g. the `@ConfigBean` also annotated as `@Configured`)
Also the tooling to generate documentation from the JSON files should be brought into Helidon build tools and the process automated as part of Helidon (either built by developer, or within pipelines as an automated PR)

**Comment by romain-grecourt** [comment]
Fixed with the following pull requests:
- https://github.com/helidon-io/helidon/pull/9053
- https://github.com/helidon-io/helidon/pull/9103
