### ISSUE TITLE
Update asNodeList() on common/Config 

### ISSUE THREAD

**Issue by arjav-desai** [helidon-io/helidon#6502]
While the code to change may not be in repo yet `common/config/src/main/java/io/helidon/common/config/Config.java`

> <C extends Config> ConfigValue<List<C>> asNodeList() throws ConfigException;

its coming as part of common-config pr https://github.com/helidon-io/helidon/pull/6448 and pico pr as well https://github.com/helidon-io/helidon/pull/5750/files#diff-557d7016d9aceb8cd7b08e48eeb87fe488ba13da5c79a3acabc6ed52d3196acbR228

There is a review comment on first PR i.e. https://github.com/helidon-io/helidon/pull/6448#discussion_r1150746165

> I think that this would allow you to assign the result into a list of a arbitrary implementation of Config, eg.:
> ConfigValue<List<MyConfig >> myConfig = commonConfig.asNodeList();
> Which breaks type safety (as the result is most likely going to be somebody else's implementation of config)
> To make this right, we would have to have the C defined on the Config type, but that would create a lot of problems.
> I think this must be changed

**Comment by tomas-langer** [comment]
I am closing this issue as will not fix. 
Although this can create a code that compiles and failes at runtime, you would have to do some custom code to achieve that, which would already require understanding of the problem.
I think we can accept failure in such an edge case, with the benefit of very small impact to our users.
