### ISSUE TITLE
Openapi tools with jsonb as serializationLibrary generate compilation errors for java-helidon-client

### ISSUE THREAD

**Issue by arturbosch** [helidon-io/helidon#6505]
Openapi tools with jsonb as serializationLibrary generate compilation errors for java-helidon-client

## Environment Details
* Helidon Version: 3.2.0
* Helidon SE or Helidon MP: SE
* JDK version: 17.0.6 Temurin
* OS: Fedora 38 Beta
* Docker version (if applicable): No docker.

----------

## Problem Description

I'm trying to generate the server and client with the openapi tools.
The server part works without compilation errors. The client part however does not.

It seems like `JsonbSupport.create(jsonbConfig))` changed to `JsonbSupport.create(JsonbBuilder.create(jsonbConfig)))`.

![Screenshot from 2023-03-28 23-04-19](https://user-images.githubusercontent.com/20924106/228343254-1d39a171-74c8-4b56-b492-d5df49531cf8.png)

Also these two classes are generated which have a dependency on `jakarta.ws.rs` and I'm not sure how to handle them as the example does not generate these: https://github.com/helidon-io/helidon/tree/main/examples/openapi-tools/quickstart-se/se-client/src/main/java/org/openapitools/client/api

![Screenshot from 2023-03-28 23-11-38](https://user-images.githubusercontent.com/20924106/228344030-fea0f857-91d9-4f1c-846a-aa5e4acaefdd.png)

## Steps to reproduce

I'm using the gradle plugin of openapi-tools to generate the client.
Do I miss any configuration values maybe?

```kotlin
import kotlin.io.path.div

plugins {
    id("koala.kotlin.lib")
    alias(libs.plugins.openapi.generator)
}

dependencies {
    implementation(platform("io.helidon:helidon-dependencies:${libs.versions.helidon.get()}"))
    implementation("io.helidon.webclient:helidon-webclient")
    implementation("io.helidon.webserver:helidon-webserver")
    implementation("io.helidon.media:helidon-media-jsonb")
    implementation("io.helidon.config:helidon-config")
}

val v1Spec: String = project.file("../openapi/v1.yaml").toString()
val openApiGeneratedSourceSet = buildDir.toPath() / "generated/openapi"

sourceSets {
    val main by getting
    main.java.srcDir(openApiGeneratedSourceSet / "src/main/java")
}

openApiGenerate {
    generatorName.set("java-helidon-client")
    library.set("se")
    inputSpec.set(v1Spec)
    outputDir.set(openApiGeneratedSourceSet.toString())
    packageName.set("xxx.client")
    ignoreFileOverride.set(project.file("../.openapi-generator-ignore").toString())
    configOptions.set(
        mapOf(
            "dateLibrary" to "java8",
            "serializationLibrary" to "jsonb",
            "fullProject" to "false",
            "apiPackage" to "xxx.api",
            "modelPackage" to "xxx.models",
        )
    )
}

openApiValidate {
    inputSpec.set(v1Spec)
}

tasks.compileKotlin.configure {
    inputs.files(tasks.openApiGenerate.get().outputs)
}

tasks.clean.configure {
    delete(openApiGeneratedSourceSet)
}
```

**Comment by aserkes** [comment]
I could not reproduce the problem related to the dependency on `jakarta.ws.rs`.
I checked the code of the `java-helidon-client` and it looks like that these two classes (`ApiException` and `ApiExceptionMapper`) are generated if `mp` library is used for `java-helidon-client`.

**Comment by arturbosch** [comment]
> I could not reproduce the problem related to the dependency on `jakarta.ws.rs`. I checked the code of the `java-helidon-client` and it looks like that these two classes (`ApiException` and `ApiExceptionMapper`) are generated if `mp` library is used for `java-helidon-client`.

Thanks for fixing the jsonb problem!

It might be that I switched to `mp` to check and forgot to clean it automatically on `gradle clean`. Will check it again later when your PR is released.

**Comment by arturbosch** [comment]
I found another compilation error:
When using `jsonb` as serialization together with openapi's `nullable: true`, a `org.openapitools.jackson.nullable.JsonNullable` import is generated (without a usage).

**Comment by arturbosch** [comment]
> This import is added in java classes when `jackson` is used as a `serializationLibrary`. This error could happen if `fullProject` set to `false` and project is regenerated several times with `serializationLibrary` set to `jackson` or without this parameter at all and then again with `jsonb`. Therefore, it is not a bug.

Hm, I just tried a clean build with my configOptions above and I do get this generated everytime.
I try to setup a small reproducer project later this week.

**Comment by arturbosch** [comment]
I've created a minimal reproducer project.: https://github.com/arturbosch/helidon-openapi-reproducer

Steps:
1. Run `gradle openApiGenerate`
2. Notice that `build/generated/openapi/src/main/java/test/models/MetricDescriptor` has the jackson annotation

I'm using `nullable: true`in my v1.yaml.

**Comment by arturbosch** [comment]
> jackson-databind-nullable

Yes, it is okay to manually add dependencies which I also do with jsonb etc.
What I miss is why 1. a jackson annotation is generated if I use jsonb and 2. why `JacksonNullable` import is generated which is never used.
I do still think that generating an import which is not used a bug here, don't you agree ?
