### ISSUE TITLE
2.x, 3.x Java 20 support

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#6506]
ASM 9.4.0 supports Java 20
ASM 9.5.0 supports Java 21
https://asm.ow2.io/versions.html

# Helidon 2.x

EclipseLink 2.7.12 (depends on ASM 9.4.0)
Hibernate 5.6.15 (depends on ByteBuddy 1.12.18 depends on ASM 9.4.0

# Helidon 3.x

Uses EclipseLink 3.0.3. No newer version of 3.x available -- so upgrade ASM directly?
Hibernate 6.1.7.Final (depends on ByteBuddy 1.12.18 depends on ASM 9.4.0l
plugin.hibernate.enhance 6.1.7.Final

**Comment by ljnelson** [comment]
As of this writing, Hibernate is not ready yet; the mainline depends on Byte Buddy 1.12.18 which uses ASM 9.4: https://github.com/raphw/byte-buddy/blob/byte-buddy-1.12.18/pom.xml#L71

**Comment by ljnelson** [comment]
As of this writing, Eclipselink is ready for Java 20 but not ready yet for Java 21; the mainline depends on ASM 9.4: https://github.com/eclipse-ee4j/eclipselink/blob/8ac1935575d461d3a51672c92a16062645e11bb3/pom.xml#L188
