### ISSUE TITLE
Unable to serve file when `Content-Length` is specified

### ISSUE THREAD

**Issue by martin-sladecek** [helidon-io/helidon#6541]
In some cases, when `Content-Length` is specified, the server request gets stuck and no response is returned.

## Environment Details
* Helidon Version: 3.2.0
* Helidon MP
* JDK version: 17
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description

Sample: 
[sample.zip](https://github.com/helidon-io/helidon/files/11137471/sample.zip)

Using the sample, it is possible to reproduce this in 2 ways:
1. Run the test
2. Run the app and call `/greet` endpoint with curl. The request will be stuck and no response is sent, not even headers.

Alternatively, I've tried `netcat` to send the request manually. Interestingly, when I add 2 newlines after the GET request line, the server starts to send the data. 

## Steps to reproduce
See problem description above.

**Comment by spericas** [comment]
@martin-sladecek  Could you try turning off back pressure in `microprofile-config.properties` as follows?

```
server.backpressure-strategy=UNBOUNDED
```

**Comment by martin-sladecek** [comment]
Hi @spericas, the property seems to work.

**Comment by spericas** [comment]
@martin-sladecek Great, it is a workaround. There's a bug in the default backpressure strategy that I'm looking into.

**Comment by martin-sladecek** [comment]
None of the backpressure strategies work, not just the default one.

**Comment by spericas** [comment]
The other two would require changes to the code, and some explicit flushing (better suited for SE). AUTO_FLUSH is the default one and should work fine in MP.

**Comment by spericas** [comment]
PR #6556
