### ISSUE TITLE
4.x: Interceptors for ConfigDriven and programmatically Provider<> Services

### ISSUE THREAD

**Issue by trentjeff** [helidon-io/helidon#6542]
Whenever anyone wants to "own" the creation of a service instance (i.e., via implementing `Provider<>` or `InjectionPointProvider<>`) they need to be mindful whether the service they are providing should be intercepted. In such circumstances, they should ideally allow Pico to wrap that instance (or provider) with the interceptor-generated source for that service. Note that Config-Driven-Services has the same needs.

This issue will track the work to enable this mechanism and integrate it into Config-Driven-Services.

related to: https://github.com/helidon-io/helidon/issues/6530

**Comment by tomas-langer** [comment]
Now there will be a disabled test (PR #6640) and a few other places that should be fixed by this issue (this not is for tracing, so we do not forget about it)

**Comment by tomas-langer** [comment]
For new `helidon-service-inject`:
- interceptor of services (classes) is done automatically - a subclass is code generated and takes care of interception of everything
- interceptor of services created by `ServicesProvider` (such as config beans) requires code generation of a special type to do interface interception through delegation; this approach then requires the `ServicesProvider` to handle the created instant to appropriate factory to obtain an intercepted instance.

Code that takes care of interception for the second case (which may require custom codegens) - this is not yet in the repository!:
- `ConfigBeanCodegen` - checks if config type is intercepted, and generates appropriate wrapping with factory
- `InterceptionSupport` - public API to check if a type is intercepted, and to code generate required types

Where to see what is generated?
got to `service/tests/inject/config-driven` and see the generated code for `AConfig` in `target/generated-sources`:
- `AConfig__ConfigBean` the config bean
- `AConfig__InterceptedDelegate` the interception handler that delegates to real `AConfig` instance
- `AConfig__InterceptedFactoryDescriptor` - the factory used from config bean

There is a limitation with this approach - we do not support "mixin" - i.e. we only support implementing a single interface. If the service implements multiple interfaces, this will not work. A workaround would be to create a single interface that acts as the contract and extends all service interfaces.

**Comment by tomas-langer** [comment]
Closing as this will be available in `helidon-service-inject`, and `helidon-inject` will be removed.
