### ISSUE TITLE
No longer able to add span baggage in Helidon SE v3

### ISSUE THREAD

**Issue by RickyFrost** [helidon-io/helidon#6557]
## Environment Details
* Helidon Version: 3.0.1
* Helidon SE
* JDK version: 17.0.5
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description
In Helidon SE v2.5.2 we were able to retrieve the "activeSpan" and invoke setBaggageItem and getBaggageItem. In Helidon SE v3.0.1, even if you created the Span inline there are no baggage calls available.

This is a regression caused by the wrapping of the tracing framework with less functional helidon classes. The background is also that the wrapped helidon class is the only available one because that's all we get access to in ServerRequest methods. There used to be opentracing objects available in H2 SE.

p.s. a similar regression is true for the Span::log methods in H2 SE. Even though an equivalent addEvent is available it is up to the service to make the active Span available to any random method that may need it. For ex: exception catch handlers. We used to be able to use GlobalTracer.get().activeSpan() from anywhere. It's impractical to require that type of code to first create a Span just to call addEvent.

## Steps to reproduce
N/A (API shortcoming)

**Comment by dalexandrov** [comment]
Related #6190
