### ISSUE TITLE
Support Jaeger propagator in Helidon Jaeger integration

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#6574]
3.x+

Currently we hardcode propagator to `B3Propagator`, where we used to support more (such as `jaeger`).
We should re-add this support and configuration option to Helidon to support `JaegerPropagator`

This is an omission (e.g. regression in features)

**Comment by bogedal** [comment]
Sounds good @tomas-langer - when fixed I can start rolling out helidon 3 services in the company I work for :)

**Comment by tomas-langer** [comment]
This is now fixed in `main` branch, PR for 3.x is ready as well.
