### ISSUE TITLE
Mobile navigation links to old documentation

### ISSUE THREAD

**Issue by pavelklecansky** [helidon-io/helidon#6601]
## Problem Description
On mobile, the navigation links to old documentation (v2) but main page links to new (v3)
### Mobile navigation
![image](https://user-images.githubusercontent.com/28779692/231536790-a92f80f6-8675-4fee-9245-7e14b699ba67.png)
### Mobile main page
![image](https://user-images.githubusercontent.com/28779692/231537028-ea12cae3-625d-46e2-9fd9-1b1d43533e70.png)

**Comment by romain-grecourt** [comment]
Good catch, this needs to be fixed.

**Comment by romain-grecourt** [comment]
This is now fixed, thanks for reporting the issue.
