### ISSUE TITLE
Update MP Fault Tolerance Docs.  Old instructions no longer apply

### ISSUE THREAD

**Issue by dcoracle** [helidon-io/helidon#6606]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.6.0
* Helidon SE or Helidon MP: MP
* JDK version: 17
* OS: Oracle Linux 9
* Docker version (if applicable): N/A

----------

## Problem Description
Confirmed you _can_ indeed use microprofile-config.properties to set the threadpool size.  application.yaml does _not_ work for me

Update https://helidon.io/docs/v2/#/mp/faulttolerance/01_overview and remove the note about microprofile-config.properties

## Steps to reproduce
add the following to microprofile-config.properties: 
> executor.core-pool-size=32
>scheduled-executor.core-pool-size=32

If you download the JFR, you will see 'ft-mp-1' through until 'ft-mp-32' and 'ft-mp-schedule-1' through until 'ft-mp-schedule-32' in the thread dump

**Comment by spericas** [comment]
Yes, indeed this now works from `microprofile-config.properties`. However, it also works from an `application.yaml` file (maybe you didn't have the correct dependencies for yaml?), so only the note needs to be removed.

**Comment by dcoracle** [comment]
hmm,  I actually placed application.yaml in the classpath similar to how it was in the test code but it didn't work for me.  It's ok though because microprofile-config.properties is a better place anyways :) Closing
