### ISSUE TITLE
4.x: Pico config driven problem

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#6633]
Reproducer: https://github.com/tomas-langer/helidon/tree/ft-on-pico/examples/nima/fault-tolerance
`server.port` is ignored from configuration.
If you put breakpoint in `LoomServer` in injected construcor, you can see that the port is set to `0` in the config bean

**Comment by trentjeff** [comment]
See https://github.com/helidon-io/helidon/pull/6652
