### ISSUE TITLE
Pico: use original parameter names in generated code

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#6646]
The generated source code for interceptors (classes ending with `$$Pico$$Interceptor`) is using indexed parameter names - `p1`, `p2` etc. It would be better for troubleshooting if the parameter names were the original names used in source code (available when using annotation processor). 

Example - generated code
```
    private static final TypedElementName __intercepted__p1 = DefaultTypedElementName.builder()
            .typeName(create(java.lang.String.class))
			.elementName("p1")
            .build();
```
Source code of service:
```
String intercepted(String message, boolean modify, boolean repeat, boolean doReturn)
```

see `TheService` in interceptor testing module.

**Comment by trentjeff** [comment]
The next best thing is to have it available in meta-information somewhere.

**Comment by tomas-langer** [comment]
This is no longer relevant, as `helidon-inject` will be removed, and `helidon-service-inject` uses original parameter names
