### ISSUE TITLE
Nima - WebServer - Add configuration support for EXECUTOR_SHUTDOWN_MILLIS

### ISSUE THREAD

**Issue by rbygrave** [helidon-io/helidon#6649]
## Environment Details
* Helidon Version: 4.0.0-SNAPSHOT
* Helidon SE 
* JDK version: 20
* OS: MacOS
* Docker version (if applicable): NA

----------

## Problem Description
 EXECUTOR_SHUTDOWN_MILLIS is hard coded to 500 and instead should be configurable [with a default of 500].

 Refer https://github.com/helidon-io/helidon/blob/main/nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ServerListener.java#L59

## Suggested change

Extend [ListenerConfiguration](https://github.com/helidon-io/helidon/blob/main/nima/webserver/webserver/src/main/java/io/helidon/nima/webserver/ListenerConfiguration.java) to have a new `gracefulShutdownMillis` configuration property that defaults to 500L but can be set via configuration.

Modify ServerListener to use this `gracefulShutdownMillis` configuration property rather than the hardcoded 500L.

## Alternative suggested change

Use a system property to allow for configuration like:
```java
private static final long EXECUTOR_SHUTDOWN_MILLIS = Long.getLong("nima.gracefulShutdownMillis", 500L);
``` 

## Reason

Some applications desire to have a graceful shutdown that is longer than the currently hardcoded 500 milliseconds.

**Comment by Tomas-Kraus** [comment]
This was already fixed by https://github.com/helidon-io/helidon/pull/6955
