### ISSUE TITLE
4.x: Pico - consider adding a Helidon annotation for Named that accepts a class

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#6657]
We have several types that accept a `@Named` with a name equal to a fully qualified type (such as interceptors).
We may want to introduce customized named annotation that accepts a class instead of a string (for better refactoring and build time validation of values). 
Now we can have a typo in the name, and we will not find out until runtime.

**Comment by ljnelson** [comment]
(Interestingly, this is exactly why CDI effectively deprecated the use of `@Named` except in cases where it cannot be avoided, or legacy JSF stuff, preferring to advise users to create their own definitionally typesafe qualifiers instead.)
