### ISSUE TITLE
Public snapshot builds

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#667]
We need to have our snapshots available as binaries, preferably in a public snapshot repo.
This is very useful to test fixed issues before we do a release.

**Comment by agentgt** [comment]
I am playing around with integrating Nima into another OSS project (Jooby) so having snapshots build would help greatly.

I imagine with Nima being one of the first to utilize Loom first class that others might be interested in easily trying it out.

**Comment by barchetta** [comment]
With #7569 we have the ability to do public snapshot builds on demand.  In practice we have not had much demand for this so for now I think that is sufficient.

**Comment by barchetta** [comment]
We are now publishing SNAPSHOT builds to https://oss.sonatype.org/content/repositories/snapshots/io/helidon/helidon-bom/4.1.0-SNAPSHOT/ every time a PR is merged into Helidon 4 (main).
