### ISSUE TITLE
Add example/doc about configuration of HelidonConnector

### ISSUE THREAD

**Issue by arjav-desai** [helidon-io/helidon#6728]
Currently, we don't have doc/example about setting/configuring HelidonConnector.

When we look at
https://github.com/helidon-io/helidon/blob/helidon-3.x/jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnector.java, the connector has options for configuring followRedirects and readTimeout, but nothing to control keepAlive. HelidonConnector is based-on/used WebClient underneath which supports keepAliveWebClient but I don't see a way to turn that on through the connector.

**Comment by spericas** [comment]
Created #7640 for 4.x (PR #7641). Re-targeting this to 3.x.
