### ISSUE TITLE
Move comparative Pico examples out the repository

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#6751]
There are some Pico examples that exist only to show-case the differences with other Injection frameworks (Guice, HK2).
They are great materials for a blog article, but poor examples.

It's acceptable to host these kind of projects under our personal GitHub space and reference them in Helidon blog articles.

**Comment by trentjeff** [comment]
@barchetta What is your ETA on the new repo?

**Comment by barchetta** [comment]
This issue has been resolved.
