### ISSUE TITLE
WLS 1411/12214 jaxws-wlswss-client Javax Client w/H2

### ISSUE THREAD

**Issue by Geetha-Savithriamma** [helidon-io/helidon#6754]
## Environment Details
* Helidon Version: 2.x
* Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

**Comment by ljamen** [comment]
addressed by PR #6946

**Comment by ljamen** [comment]
Addressed in https://github.com/helidon-io/helidon/pull/6946
