### ISSUE TITLE
Pico Config Improvements

### ISSUE THREAD

**Issue by trentjeff** [helidon-io/helidon#6768]
Config improvements:
Currently we need to set the config through bootstrap. I think we should a concept of two configs:
- [ ] a bootstrap config (by default only uses system properties and env vars) to prepare pico
- [ ] a config that is constructed as a Service in Pico (and can use other services, such as ConfigSource, Mapper etc.) to create the configuration tree for runtime

**Comment by tomas-langer** [comment]
We currently support creating Config as a service in registry. 
It now only supports custom `ConfigSource`

**Comment by tomas-langer** [comment]
The new configuration approach for `helidon-service-inject` supports both configuration created by user and registered through `GlobalConfig` and a configuration created within the service registry.
The "bootstrap" configuration will use either the global config (if present), or a new configuration instance created through `Config.create()`.
The "in-registry" config instance gathers services for the registry itself (such as parsers, filters, sources etc.).
