### ISSUE TITLE
Nima WebClient relativeUris support

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#6803]
See `WebClient.builder().relativeUris(boolean)`

**Comment by klustria** [comment]
Potential fix for this issue is in https://github.com/helidon-io/helidon/pull/6952

**Comment by klustria** [comment]
Created https://github.com/helidon-io/helidon/issues/6962 as a follow-up for additional changes when proxy implementation becomes available. Closing as the relativeUris config has been added.
