### ISSUE TITLE
Update Microprofile Config Change Support Documentation

### ISSUE THREAD

**Issue by dcoracle** [helidon-io/helidon#6817]
## Environment Details
* Helidon Version: 3.2.1
* Helidon SE or Helidon MP: MP
* JDK version: 17
* OS: Oracle Linux 9
* Docker version (if applicable): NA

----------

## Problem Description
The documentation located in https://helidon.io/docs/v3/#/mp/config/introduction with respect to Config Change Support is not useful as it does not provide any example on how to achieve change support

I was able to figure it out via below link but it is outdated and doesn't use the properties listed in the documentation:

https://github.com/verrazzano/examples/blob/arjav-desai/vz-2307/helidon-config/src/main/java/io/helidon/examples/config/Main.java

Please update docs with an updated example

**Comment by arjav-desai** [comment]
The docs have been fixed as part of issue https://github.com/helidon-io/helidon/issues/6518
