### ISSUE TITLE
Helidon Jersey support offloads handler even for AsyncResponse handler

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon#6824]
Thx to @asafm for reporting

## Environment Details
* Helidon Version: 3.x, 2.x
* Helidon MP

Helidon should not offload to new thread for JAX-RS async handler

**Comment by spericas** [comment]
Another way to look at this is to say that `AsyncResponse` shouldn't be used with Helidon at all. It's likely better for Helidon to have thread control instead of Jersey.

**Comment by spericas** [comment]
> I aim for the framework (Helidon) to use async I/O when writing the ready-made response object back to the connection. 

Just to clarify, by "async I/0", you mean "call a method to write response data that does not wait and returns immediately"? This is mostly how it works in Helidon MP, we write data to Netty's event loop, and Netty eventually writes it out . If you want to work closer to Netty, you should use Helidon SE instead. Helidon MP has some other layers of code that makes things a bit more difficult to control.

> Jetty supports something similar, and I believe Netty does as well. Can we re-use Netty, since Helidon, in its current version, relies on Netty to do that?

 See comment about Helidon SE above. Note that we also implement different _backpressure_ algorithms to ensure that an application does not exceed a connection's capacity to deliver the data. In a nutshell, we monitor async writes using Netty and stop sending more data when too many write buffers are in flight.

**Comment by spericas** [comment]
@asafm I'd suggest we close this issue and if necessary open a thread on Slack instead.

**Comment by asafm** [comment]
Ok. Go ahead. See you in Slack

**Comment by asafm** [comment]
@spericas I can't find a Santiago on Slack. Do you go by another name?

**Comment by spericas** [comment]
@asafm Please use the #helidon-users alias. Thanks.
