### ISSUE TITLE
Replace usage of DBClient reactive to blocking in OCI examples

### ISSUE THREAD

**Issue by spericas** [helidon-io/helidon#6890]
In 3.x the ATP OCI example had this:

```java
createDbClient(walletContent)
        .flatMap(dbClient -> dbClient.execute(exec -> exec.query("SELECT 'Hello world!!' FROM DUAL")))
        .first()
        .map(dbRow -> dbRow.column(1).as(String.class))
        .ifEmpty(() -> res.status(404).send())
        .onError(res::send)
        .forSingle(res::send);
```

Requires #6991

However, since #6991 is in progress, let's update the usage to use `.await()` to block.

**Comment by spericas** [comment]
This one relates to other OCI example issues (#6872 and #6873). 

@aserkes I'll assign this one to you as it relates to the others. Feel free to assign it back to me if after moving examples to Nima, we still need to replace DbClient.

**Comment by romain-grecourt** [comment]
We've decided to update DBClient to blocking, thus we should not update all usages of DBClient. In the mean time we can use `.async()` on the `Single` and `Multi` instead of using JDBC directly.

**Comment by spericas** [comment]
@romain-grecourt Roger, title updated.

**Comment by romain-grecourt** [comment]
Fixed in https://github.com/helidon-io/helidon/issues/6859
