### ISSUE TITLE
Helidon MP does not generate a JSON result from a REST resource if the model does not have getters/setters.

### ISSUE THREAD

**Issue by haducloc** [helidon-io/helidon#6917]
## Environment Details
* Helidon Version: Latest version - 3.2.1
* Tested with Helidon MP:   
* JDK version: 17
* OS: Windows 10
* Docker version (if applicable):

## Problem Description

**I have a simple java model:**

    public class User {
         
        private int userId;
    
        public int userId() {
            return userId;
        }
    
        public User userId(int value) {
            this.userId = value;
            return this;
        }
    }

**My REST resourse:**

    @GET
    @Path("/hello")
    @Produces(MediaType.APPLICATION_JSON)
    public User hello() {
        return new User().userId(1000);
    }

Result when I access /hello:   {}.   I expected to see  { userId: 1000 }

As you see. I am NOT following java bean rules. No getters/setters.

If I modify the User to use getters/setters, The result will be { userId: 1000 }.

**The thing is:**

If I use **Jsonb.toJson** directly to serialize the User object, I will see { userId: 1000 }, even if the User object does not have getters or setters. This is exactly what I expect.

**Comment by tvallin** [comment]
Hi @haducloc, 

> If I use Jsonb.toJson directly to serialize the User object, I will see { userId: 1000 }

What version of Jsonb did you use ?

I tried this with the `User` class you provided:
```java
Jsonb jsonb = JsonbBuilder.create();
jsonb.toJson(new User().userId(1000));
```

And the result is `{}`. I used Jsonb `2.0.0` version.

**Comment by haducloc** [comment]
I am sorry for my mistake. When I tested jsonb.toJson() directly. The jsonb was created with a config. Please see my code:

         var config = new JsonbConfig();
        config.withPropertyVisibilityStrategy(new PropertyVisibilityStrategy() {

            @Override
            public boolean isVisible(Field field) { return true; }

            @Override
            public boolean isVisible(Method method) { return false; }
        });

        Jsonb jsonb = JsonbBuilder.create(config);
        var out = new StringWriter();

        jsonb.toJson(new User(), out);

        System.out.println(out.toString());
        // OUT: {"userId":0}

As you see. I had a chance to configure Jsonb to use fields instead getters/setters.

How can I configure Helidon MP to use fields only?

**Comment by tvallin** [comment]
Thanks for providing me additional informations. I think one way to achieve that is to use ContextResolver.

```java
@Provider
public class JsonbContextResolver implements ContextResolver<Jsonb> {

    @Override
    public Jsonb getContext(Class<?> type) {
        JsonbConfig config = new JsonbConfig().withPropertyVisibilityStrategy(new PropertyVisibilityStrategy() {
            @Override
            public boolean isVisible(Field field) { return true; }

            @Override
            public boolean isVisible(Method method) { return false; }
        });

        return JsonbBuilder.create(config);
    }

}
```

**Comment by haducloc** [comment]
It works. Thank you for the solution. But I think serializing fields should be enabled by default. No getters/setters required.

**Comment by haducloc** [comment]
It works. Thank you for the solution. But I think serializing fields should be enabled by default. No getters/setters required.
