### ISSUE TITLE
Address maven 3.9.2 plugin issues

### ISSUE THREAD

**Issue by joeyleeeeeee97** [helidon-io/helidon#6928]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: main
* Helidon SE or Helidon MP
* JDK version: 17
* maven: 3.9.2
* OS: macos
* Docker version (if applicable):

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
[WARNING] Plugin validation issues were detected in 10 plugin(s)
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-jar-plugin:3.0.2
[WARNING]   Declared at location(s):
[WARNING]    * io.helidon.licensing:helidon-licensing:4.0.0-SNAPSHOT (licensing/pom.xml) @ line 77
[WARNING]   Used in module(s):
[WARNING]    * io.helidon.licensing:helidon-licensing:4.0.0-SNAPSHOT (licensing/pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-settings-builder:3.0, org.apache.maven:maven-repository-metadata:3.0, org.apache.maven:maven-artifact:3.0, org.apache.maven:maven-plugin-api:3.0, org.apache.maven:maven-settings:3.0, org.apache.maven:maven-aether-provider:3.0, org.apache.maven:maven-model:3.0, org.apache.maven:maven-core:3.0, org.apache.maven:maven-model-builder:3.0]
[WARNING]
[WARNING]  * org.codehaus.mojo:build-helper-maven-plugin:1.12
[WARNING]   Declared at location(s):
[WARNING]    * io.helidon.common:helidon-common:4.0.0-SNAPSHOT (common/common/pom.xml) @ line 67
[WARNING]   Used in module(s):
[WARNING]    * io.helidon.common:helidon-common:4.0.0-SNAPSHOT (common/common/pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x
[WARNING]    * Plugin mixes multiple Maven versions: [3.0, 2.2.1]
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-compat:3.0, org.apache.maven:maven-model-builder:3.0]
[WARNING]    * Plugin depends on plexus-container-default, which is EOL
[WARNING]
[WARNING]  * org.commonjava.maven.plugins:directory-maven-plugin:1.0
[WARNING]   Declared at location(s):
[WARNING]    * io.helidon:helidon-project:4.0.0-SNAPSHOT (pom.xml) @ line 796
[WARNING]   Used in module(s):
[WARNING]    * io.helidon:helidon-project:4.0.0-SNAPSHOT (pom.xml)
[WARNING]    * io.helidon.licensing:helidon-licensing:4.0.0-SNAPSHOT (licensing/pom.xml)
[WARNING]    * io.helidon.common:helidon-common-project:4.0.0-SNAPSHOT (common/pom.xml)
[WARNING]    * io.helidon.common:helidon-common:4.0.0-SNAPSHOT (common/common/pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-builder-support:3.8.1, org.apache.maven:maven-model-builder:3.8.1, org.apache.maven:maven-core:3.8.1, org.apache.maven:maven-repository-metadata:3.8.1, org.apache.maven:maven-plugin-api:3.8.1, org.apache.maven:maven-resolver-provider:3.8.1, org.apache.maven:maven-settings:3.8.1, org.apache.maven:maven-artifact:3.8.1, org.apache.maven:maven-settings-builder:3.8.1, org.apache.maven:maven-model:3.8.1]
[WARNING]
[WARNING]  * io.helidon.build-tools:helidon-services-plugin:3.0.3
[WARNING]   Declared at location(s):
[WARNING]    * io.helidon:helidon-project:4.0.0-SNAPSHOT (pom.xml) @ line 882
[WARNING]   Used in module(s):
[WARNING]    * io.helidon:helidon-project:4.0.0-SNAPSHOT (pom.xml)
[WARNING]    * io.helidon.licensing:helidon-licensing:4.0.0-SNAPSHOT (licensing/pom.xml)
[WARNING]    * io.helidon.common:helidon-common-project:4.0.0-SNAPSHOT (common/pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-model:3.6.2, org.apache.maven:maven-plugin-api:3.6.2, org.apache.maven:maven-artifact:3.6.2]
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:2.7
[WARNING]   Declared at location(s):
[WARNING]    * io.helidon:helidon-project:4.0.0-SNAPSHOT (pom.xml) @ line 822
[WARNING]    * io.helidon.licensing:helidon-licensing:4.0.0-SNAPSHOT (licensing/pom.xml) @ line 41
[WARNING]    * io.helidon.common:helidon-common:4.0.0-SNAPSHOT (common/common/pom.xml) @ line 46
[WARNING]   Used in module(s):
[WARNING]    * io.helidon:helidon-project:4.0.0-SNAPSHOT (pom.xml)
[WARNING]    * io.helidon.licensing:helidon-licensing:4.0.0-SNAPSHOT (licensing/pom.xml)
[WARNING]    * io.helidon.common:helidon-common-project:4.0.0-SNAPSHOT (common/pom.xml)
[WARNING]    * io.helidon.common:helidon-common:4.0.0-SNAPSHOT (common/common/pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x
[WARNING]    * Plugin depends on plexus-container-default, which is EOL
[WARNING]   Mojo issue(s):
[WARNING]    * Mojo resources:copy-resources (org.apache.maven.plugin.resources.CopyResourcesMojo)
[WARNING]      - Implements `Contextualizable` interface from Plexus Container, which is EOL.
[WARNING]    * Mojo resources:resources (org.apache.maven.plugin.resources.ResourcesMojo)
[WARNING]      - Implements `Contextualizable` interface from Plexus Container, which is EOL.
[WARNING]      - Parameter 'resources' is read-only, must not be used in configuration
[WARNING]    * Mojo resources:testResources (org.apache.maven.plugin.resources.TestResourcesMojo)
[WARNING]      - Implements `Contextualizable` interface from Plexus Container, which is EOL.
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-compiler-plugin:3.10.1
[WARNING]   Declared at location(s):
[WARNING]    * io.helidon:helidon-project:4.0.0-SNAPSHOT (pom.xml) @ line 220
[WARNING]   Used in module(s):
[WARNING]    * io.helidon.licensing:helidon-licensing:4.0.0-SNAPSHOT (licensing/pom.xml)
[WARNING]    * io.helidon.common:helidon-common:4.0.0-SNAPSHOT (common/common/pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-plugin-api:3.2.5, org.apache.maven:maven-model:3.2.5, org.apache.maven:maven-core:3.2.5, org.apache.maven:maven-settings:3.2.5, org.apache.maven:maven-model-builder:3.2.5, org.apache.maven:maven-repository-metadata:3.2.5, org.apache.maven:maven-aether-provider:3.2.5, org.apache.maven:maven-settings-builder:3.2.5, org.apache.maven:maven-artifact:3.2.5]
[WARNING]
[WARNING]  * org.codehaus.mojo:buildnumber-maven-plugin:1.4
[WARNING]   Declared at location(s):
[WARNING]    * io.helidon:helidon-project:4.0.0-SNAPSHOT (pom.xml) @ line 858
[WARNING]   Used in module(s):
[WARNING]    * io.helidon:helidon-project:4.0.0-SNAPSHOT (pom.xml)
[WARNING]    * io.helidon.licensing:helidon-licensing:4.0.0-SNAPSHOT (licensing/pom.xml)
[WARNING]    * io.helidon.common:helidon-common-project:4.0.0-SNAPSHOT (common/pom.xml)
[WARNING]    * io.helidon.common:helidon-common:4.0.0-SNAPSHOT (common/common/pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x
[WARNING]    * Plugin depends on plexus-container-default, which is EOL
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5
[WARNING]   Declared at location(s):
[WARNING]    * io.helidon:helidon-project:4.0.0-SNAPSHOT (pom.xml) @ line 436
[WARNING]   Used in module(s):
[WARNING]    * io.helidon.licensing:helidon-licensing:4.0.0-SNAPSHOT (licensing/pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin mixes multiple Maven versions: [3.0-alpha-2, 3.0]
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-toolchain:3.0-alpha-2, org.apache.maven:maven-artifact:3.0, org.apache.maven:maven-plugin-api:3.0, org.apache.maven:maven-model:3.0]
[WARNING]   Mojo issue(s):
[WARNING]    * Mojo surefire:test (org.apache.maven.plugin.surefire.SurefirePlugin)
[WARNING]      - Parameter 'localRepository' uses deprecated parameter expression '${localRepository}': ArtifactRepository type is deprecated and its use in Mojos should be avoided.
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-install-plugin:3.0.0-M1
[WARNING]   Declared at location(s):
[WARNING]    * io.helidon:helidon-parent:4.0.0-SNAPSHOT (parent/pom.xml) @ line 168
[WARNING]   Used in module(s):
[WARNING]    * io.helidon:helidon-parent:4.0.0-SNAPSHOT (parent/pom.xml)
[WARNING]    * io.helidon:helidon-bom:4.0.0-SNAPSHOT (bom/pom.xml)
[WARNING]    * io.helidon:helidon-dependencies:4.0.0-SNAPSHOT (dependencies/pom.xml)
[WARNING]    * io.helidon.applications:helidon-applications-project:4.0.0-SNAPSHOT (applications/pom.xml)
[WARNING]    * io.helidon.applications:helidon-applications:4.0.0-SNAPSHOT (applications/parent/pom.xml)
[WARNING]    * io.helidon.applications:helidon-nima:4.0.0-SNAPSHOT (applications/nima/pom.xml)
[WARNING]    * io.helidon.applications:helidon-se:4.0.0-SNAPSHOT (applications/se/pom.xml)
[WARNING]    * io.helidon.applications:helidon-mp:4.0.0-SNAPSHOT (applications/mp/pom.xml)
[WARNING]    * io.helidon:helidon-project:4.0.0-SNAPSHOT (pom.xml)
[WARNING]    * io.helidon.licensing:helidon-licensing:4.0.0-SNAPSHOT (licensing/pom.xml)
[WARNING]    * io.helidon.common:helidon-common-project:4.0.0-SNAPSHOT (common/pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-settings-builder:3.0, org.apache.maven:maven-repository-metadata:3.0, org.apache.maven:maven-artifact:3.0, org.apache.maven:maven-plugin-api:3.0, org.apache.maven:maven-settings:3.0, org.apache.maven:maven-aether-provider:3.0, org.apache.maven:maven-model:3.0, org.apache.maven:maven-core:3.0, org.apache.maven:maven-model-builder:3.0]
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1
[WARNING]   Declared at location(s):
[WARNING]    * io.helidon:helidon-project:4.0.0-SNAPSHOT (pom.xml) @ line 777
[WARNING]   Used in module(s):
[WARNING]    * io.helidon:helidon-project:4.0.0-SNAPSHOT (pom.xml)
[WARNING]    * io.helidon.licensing:helidon-licensing:4.0.0-SNAPSHOT (licensing/pom.xml)
[WARNING]    * io.helidon.common:helidon-common-project:4.0.0-SNAPSHOT (common/pom.xml)
[WARNING]    * io.helidon.common:helidon-common:4.0.0-SNAPSHOT (common/common/pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-settings-builder:3.0, org.apache.maven:maven-repository-metadata:3.0, org.apache.maven:maven-artifact:3.0, org.apache.maven:maven-plugin-api:3.0, org.apache.maven:maven-settings:3.0, org.apache.maven:maven-compat:3.0, org.apache.maven:maven-aether-provider:3.0, org.apache.maven:maven-model:3.0, org.apache.maven:maven-core:3.0, org.apache.maven:maven-model-builder:3.0]
[WARNING]    * Plugin depends on plexus-container-default, which is EOL
[WARNING]   Mojo issue(s):
[WARNING]    * Mojo enforcer:enforce (org.apache.maven.plugins.enforcer.EnforceMojo)
[WARNING]      - Implements `Contextualizable` interface from Plexus Container, which is EOL.
[WARNING]
[WARNING]
[WARNING] Fix reported issues by adjusting plugin configuration or by upgrading above listed plugins. If no upgrade available, please notify plugin maintainers about reported issues.
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project helidon-common: Compilation failure -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]

How could I fix this? could the fix be automated in building scripts? 
Thanks

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

mvn install

Only reproduce this in macos.

**Comment by joeyleeeeeee97** [comment]
Also, the README said this requires JDK 17+, but in examples/quickstarts/helidon-standalone-quickstart-se/pom.xml
```
        <maven.compiler.source>20</maven.compiler.source>
        <maven.compiler.target>${maven.compiler.source}</maven.compiler.target>
```

**Comment by spericas** [comment]
Use JDK 20 and --enable-preview to run tests.

**Comment by romain-grecourt** [comment]
The README is out of date, JDK20 is currently required to build Helidon 4.x.
The warnings are related to Maven 3.9.2 ; we will need to fix them in the near future.

You have a compilation error, likely because of the wrong JDK version.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project helidon-common: Compilation failure -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
```

**Comment by Tomas-Kraus** [comment]
Added https://github.com/helidon-io/helidon-build-tools/issues/955 to build tools.
