### ISSUE TITLE
Nima WebClient Builder Config support

### ISSUE THREAD

**Issue by dalexandrov** [helidon-io/helidon#6935]
In 3.x we had this:

```java
Config config = Config.create();
WebClient.builder()
         .config(config.get("client"))
         .build();
```

See the [javadoc](https://helidon.io/docs/v3/apidocs/io.helidon.webclient/io/helidon/webclient/WebClient.Builder.html#config(io.helidon.config.Config))

**Comment by arjav-desai** [comment]
FYI, as part of https://github.com/helidon-io/helidon/pull/7056/files#diff-c91a66d6d5874cef4bc7e0f1348eb8dd8b59b524afad77fb795789d619ff137b, we are adding a method to read config and set value on builder based on that. Though, it may not cover all headers/config possible.
