### ISSUE TITLE
Setting up a config map in HelidonMP

### ISSUE THREAD

**Issue by Ramaiah1992** [helidon-io/helidon#6960]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 3.1.2
* Helidon MP
* JDK version: 17

----------

## Problem Description

 Team, i Have been trying to create config map for one helidon MP project. I have mounted application.yaml file into the config map but still it is not been considered in the pod.
dockerfile:
FROM fccm-dev.dockerhub-phx.oci.oraclecorp.com/java/jdk:17.0.2
LABEL maintainer = "Oracle Financial Services FCCM Team pankaj.chhangwani@oracle.com"

ARG service=helidon-jpa-sample

RUN yum clean all

ADD target/helidon-jpa-sample.jar /app/icpxe/target/helidon-jpa-sample.jar
ADD target/libs/* /app/icpxe/target/libs/

VOLUME /app/icpxe/config

WORKDIR /app/icpxe

RUN  mkdir -p /app/icpxe/logs && mkdir -p /app/icpxe/wallet

VOLUME /app/icpxe/${service}/conf
VOLUME /app/icpxe/logs
VOLUME /app/icpxe/wallet

CMD ["sh", "-c", "java -Dconfig.file=/app/icpxe/${service}/conf/application.yaml -jar  target/helidon-jpa-sample.jar"]
how to configure configmap in HelidonMP

**Comment by arjav-desai** [comment]
We have doc https://helidon.io/docs/latest/#/mp/guides/config section "Integration with Kubernetes" which shows how to do this.
