### ISSUE TITLE
Reflected User Inputs In Error Response

### ISSUE THREAD

**Issue by karthikHelidon** [helidon-io/helidon#6966]
## Environment Details
* Helidon Version:2.6
* Helidon MP
* JDK version: 17
* OS: Windows/Linux
* Docker version (if applicable):

----------

## Problem Description
Got a bug from our security team for reflected user input in error response.
Two cases they noted is 
Case 1:
Invalid content type passed to the rest api where in user input is retruned back in the response.
Case 2:
Retrun of API path /greet in the error response

## Steps to reproduce
curl --location 'http://localhost:8080/greet' \
--header 'Content-Type: ${#context["com.opensymphony.xwork2.dispatcher.HttpServletResponse"].addHeader("X-Ack",7702*9478)}.multipart/form-data'

curl --location --globoff 'http://localhost:8080/greet/javascript%3a/*%3c/script%3e%3cimg/onerror%3d'\''-/%22/-/%20onmouseover%d1/-/[%60*/[]/[(new(Image)).src%3d(/%3b/%2b/255t6qeelp23xlr08hn1uvvnkeqae02stgk87yvnX%3b.oastifycom/).replace(/.%3b/g%2c[])]//'\''src%3d%3e'

**Comment by barchetta** [comment]
I have verified that the output is HTML encoded, but in the abundance of caution we should look into not reflecting the input at all.
