### ISSUE TITLE
Not able to propagate baggage in OpenTracingSpan

### ISSUE THREAD

**Issue by RickyFrost** [helidon-io/helidon#6970]
I'm not able to propagate baggage items when opentracing is used in io.helidon.tracing.

## Environment Details
* Helidon: v3.2.1 SE
* JDK version: 17.0.5
* OS: Oracle Linux 7
* Docker version (if applicable): n/a

----------

## Problem Description
Even though the baggage item I add to the span is retrievable from the span, it doesn't propagate to the remote endpoint. 
 See sample test code below.

## Steps to reproduce
    @Test void baggageCanaryMinimal() {
        final var tracer = io.helidon.tracing.Tracer.global();
        final var span = tracer.spanBuilder("baggageCanaryMinimal").start();
        try {
            // Set baggage and confirm that it's known in the span
            span.baggage("fubar", "1");
            assertEquals("1", span.baggage("fubar").orElseThrow());

            // Inject the span (context) into the consumer
            final var consumer = HeaderConsumer
                .create(new TreeMap<>(String.CASE_INSENSITIVE_ORDER));
            tracer.inject(span.context(), HeaderProvider.empty(), consumer);

            // Confirm that baggage was NOT propagated (the bug)
            final var allKeys = consumer.keys().toString();
            assertTrue(allKeys.contains("fubar") // this fails!
                , () -> "No injected baggage-fubar found in "+allKeys);

        } catch (final Exception x) {
            span.end(x);
        } finally {
            span.end();
        }
    }

**Comment by RickyFrost** [comment]
The reason seems to be that OpenTracingSpan holds a final for the 'context' as it existed at that time in the constructor. So all baggage added to the span is never seen in the outdated context, even though it's retrievable with span.baggage("key") because that call asks the delegate.

But if I add a span.activate() and use Span.current().orElseThrow().context() then it works as expected. The reason is that a new OpenTracingSpan is created by Span.current, so it now uses the most recent context.

**Comment by barchetta** [comment]
This looks related to PR #6692

**Comment by RickyFrost** [comment]
I agree if by related you mean, before 6692 we couldn't put and get baggage at all. Now with this latest finding above you can find baggage on the Span that you added to a OpenTracingSpan. But the bug is that the baggage you can see doesn't get propagated unless you somehow acquire a newly created OpenTracingSpan. And the easiest way to do that is to activate the span, then call Span.current(), and not depend on the context() from the old Span where you actually created it.

**Comment by RickyFrost** [comment]
This issue is NOT fixed when using the dependencies above.
