### ISSUE TITLE
[Doc] Review, fix mistakes and extend Tracing documentation

### ISSUE THREAD

**Issue by dalexandrov** [helidon-io/helidon#7001]
Current Tracing documentation, both for MP and SE, contains inconsistencies and clear mistakes - they have to be fixed.
The documentation has also to be extended with better examples.

**Comment by dalexandrov** [comment]
Migration from Helidon 2.x to Helidon 3.x in the scope of Jaeger should also be mentioned, as it is a subject for misconceptions.

**Comment by AshokVardhanM** [comment]
As part of this JIRA, can you please add information regarding tracing configuration format supported.
