### ISSUE TITLE
[4.0] gRPC server stub examples/docs

### ISSUE THREAD

**Issue by efagerho** [helidon-io/helidon#7005]
There's currently no documentation or working example for writing a gRPC server using the 4.0 Loom interfaces. Copying the integration tests, I managed to get together the following stub:

```java
package io.github.efagerho.loom;

import static io.github.efagerho.loom.grpc.Echo.HelloRequest;
import static io.helidon.nima.grpc.webserver.ResponseHelper.complete;

import com.google.protobuf.Descriptors;
import io.github.efagerho.loom.grpc.Echo;
import io.github.efagerho.loom.grpc.Echo.HelloResponse;
import io.grpc.stub.StreamObserver;
import io.helidon.nima.grpc.webserver.GrpcService;
import io.helidon.nima.grpc.webserver.GrpcService.Routing;

public class LoomServer implements GrpcService {

    @Override
    public Descriptors.FileDescriptor proto() {
        return Echo.getDescriptor();
    }

    @Override
    public void update(Routing router) {
        router.unary("Hello", this::grpcUnary);
    }

    private void grpcUnary(HelloRequest request, StreamObserver<HelloResponse> observer) {
        String name = request.getName();
        complete(observer, HelloResponse.newBuilder().setResponse(String.format("Hello %s", name)).build());
    }

    public static void main(String[] args) {
        /* What here??? */
    }
}
```

How should I start the actual server? It looks like I need to setup an HTTP2 server, but it's not fully clear from the interfaces how to setup the routes etc. so that it executes in a one virtual thread per request way.

**Comment by tomas-langer** [comment]
You can find a full example here:
https://github.com/helidon-io/helidon/tree/main/examples/nima/protocols

It uses multiple protocols with our webserver, including GRPC

Short summary:
- we use the same server to server HTTP and grpc, and it indeed requires HTTP/2 server
- you can add a routing for grpc:
```
WebServer.builder()
      .addRouting(GrpcRouting.builder()
          .unary(Strings.getDescriptor(),
              "StringService",
              "Upper",
              ProtocolsMain::grpcUpper))
     .build()
     .start()
```

**Comment by efagerho** [comment]
Thanks! Hadn't noticed that larger example had gRPC. The following code starts and listens on 8080, but doesn't work: 

```java
package io.github.efagerho.loom;

import static io.helidon.nima.grpc.webserver.ResponseHelper.complete;

import io.github.efagerho.loom.grpc.Echo;
import io.github.efagerho.loom.grpc.HelloRequest;
import io.github.efagerho.loom.grpc.HelloResponse;
import io.grpc.stub.StreamObserver;
import io.helidon.logging.common.LogConfig;
import io.helidon.nima.grpc.webserver.GrpcRouting;
import io.helidon.nima.webserver.WebServer;

public class ServerMain {

    private static void hello(HelloRequest request, StreamObserver<HelloResponse> observer) {
        System.out.println("Handler called");
        String name = request.getName();
        complete(observer, HelloResponse.newBuilder().setResponse(String.format("Hello %s", name)).build());
    }

    public static void main(String[] args) {
        LogConfig.configureRuntime();

        WebServer ws = WebServer
            .builder()
            .port(8080)
            .addRouting(GrpcRouting.builder().unary(Echo.getDescriptor(), "EchoService", "Hello", ServerMain::hello)).build();

        System.out.format("gRPC endpoint configured with tls = %b\n", ws.hasTls());
        ws.start();
    }
}
```

I get the following output and Wireshark shows that it doesn't respond correctly to the HTTP/2 handshake, so something seems to still be missing.

```
2023.06.15 22:01:02.097 Logging at initialization configured using classpath: /logging.properties
2023.06.15 22:01:02.154 Configuration file application.yaml is on classpath, yet there is no parser configured for it
gRPC endpoint configured with tls = false
2023.06.15 22:01:02.270 Helidon NIMA 4.0.0-ALPHA6 has no registered features
Exception in thread "features-thread" java.lang.NullPointerException: Cannot invoke "java.util.Set.forEach(java.util.function.Consumer)" because the return value of "java.util.Map.get(Object)" is null
	at io.helidon.common.features.HelidonFeatures.features(HelidonFeatures.java:217)
	at io.helidon.common.features.HelidonFeatures.lambda$print$0(HelidonFeatures.java:92)
	at java.base/java.lang.Thread.run(Thread.java:1623)
2023.06.15 22:01:02.276 [0x7d9246d9] http://0.0.0.0:8080 bound for socket '@default'
2023.06.15 22:01:02.283 Started all channels in 9 milliseconds. 240 milliseconds since JVM startup. Java 20.0.1+9-29
```

**Comment by tomas-langer** [comment]
`Configuration file application.yaml is on classpath, yet there is no parser configured for it` 
 - please add `helidon-config-yaml` module to dependencies (it used to be there by default, we missed this problem I think)

Do you have the same dependencies as the example does? If you can, it would be easiest to work on a reproducer (if you could zip your whole application directory after running `mvn clean`), so we can try the exact same project on our side

**Comment by efagerho** [comment]
This looks like a Maven problem. If I run the JAR file created by `maven package`, then I see the output:

2023.06.16 09:11:27.895 Helidon NIMA 4.0.0-ALPHA6 features: [WebServer]

On the other hand, if I try to run the project from Intellij, then I get:

2023.06.16 09:11:27.895 Helidon NIMA 4.0.0-ALPHA6 features: [Config, Encoding, Media, WebServer]

In this case the server works. Which dependencies provide the features that are missing in the first case?

**Comment by space88man** [comment]
The link to the gRPC example above no longer works - are there other examples of NIMA-based gRPC service and (loom-based?) client?

**Comment by spericas** [comment]
Closing this old issue after MP server and client implementations were merged. A new follow-up epic will be created for gRPC.

**Comment by spericas** [comment]
New example here:

https://github.com/helidon-io/helidon-examples/tree/dev-4.x/examples/webserver/grpc
