### ISSUE TITLE
Fix serial-config.properties for io.helidon.integrations.db:ojdbc and ensure consistent use

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#7007]
For background see issue #7000, especially the comment from Tomas.

The `serial-config.properties` for `io.helidon.integrations.db:ojdbc` is incomplete. Plus we are inconsistent in our use of `io.helidon.integrations.db:ojdbc` vs `com.oracle.database.jdbc:ojdbc8-production` and handling of `serial-config.properties`.  

To clean this up we need to:

1. Fix `integrations/db/ojdbc/src/main/resources/META-INF/helidon/serial-config.properties` so that it contains: `pattern=oracle.sql.converter.*;oracle.i18n.text.converter.*`
2. Check all examples and archetypes and make sure they depend on `io.helidon.integrations.db:ojdbc` instead of depending on `com.oracle.database.jdbc:ojdbc8-production`. Remove `serial-config.properties` from these examples and archetypes (since it is picked up from the Helidon ojdbc integration).
3. Ensure integration with Oracle DB and proper use of `io.helidon.integrations.db:ojdbc` and what it provides and possible issues concerning deserialization is documented

**Comment by danielkec** [comment]
We have already prepared JEP-209 troubleshooting section for serialization filter doc as part of WLS integration documentation:
![image](https://github.com/helidon-io/helidon/assets/1773630/974368f7-50b7-4bd5-af99-507b0b33aa12)

**Comment by danielkec** [comment]
Fix didn't make it to 4.x
https://github.com/helidon-io/helidon/blob/be27e3007b59f39531ed0c2e48aee4178141b525/integrations/db/ojdbc/src/main/resources/META-INF/helidon/serial-config.properties#L17
