### ISSUE TITLE
Not able to propagate baggage using helidon-tracing-jaeger

### ISSUE THREAD

**Issue by RickyFrost** [helidon-io/helidon#7018]
I'm not able to propagate baggage items when helidon-tracing-jaeger is used.

## Environment Details
* Helidon Version: SE 3.2.1
* JDK version: 17.0.4
* OS: OL7
* Docker version (if applicable): n/a

----------

## Problem Description
Even though the baggage item I add to the span is retrievable from the span (locally), it doesn't propagate to the remote endpoint.
See sample test code below. My prior bug, helidon-6970 was forcing opentracing thru the tracer-resolver and old jaeger-client dependencies. This bug is filed to address the propagation issues in helidon-tracing-jaeger dependency.

## Steps to reproduce
```
@Test void baggageCanary() {
    final String BAGGAGE_KEY = "mykey";
    final String BAGGAGE_VALUE = "myvalue";
    final var tracer = io.helidon.tracing.Tracer.global();
    final var span = tracer.spanBuilder("baggageCanaryMinimal").start();
    try {
        // Set baggage and confirm that it's known in the span
        span.baggage(BAGGAGE_KEY, BAGGAGE_VALUE);
        assertEquals(BAGGAGE_VALUE, span.baggage(BAGGAGE_KEY).orElseThrow());

        // Inject the span (context) into the consumer
        final var consumer = HeaderConsumer
            .create(new TreeMap<>(String.CASE_INSENSITIVE_ORDER));
        tracer.inject(span.context(), HeaderProvider.empty(), consumer);

        // Confirm that baggage was NOT propagated (the bug)
        final var allKeys = consumer.keys().toString();
        assertTrue(allKeys.contains(BAGGAGE_KEY) // this fails!
            , () -> "No injected baggage-"+BAGGAGE_KEY+" found in "+allKeys);

    } catch (final Exception x) {
        span.end(x);
    } finally {
        span.end();
    }
}
```

**Comment by RickyFrost** [comment]
Somewhere along the code path I was expecting to run into:
io.opentelemetry.api.baggage.propagation.W3CBaggagePropagator

**Comment by RickyFrost** [comment]
As a trial on the w3c propagation I added 3 baggage items like below:
span.baggage("first", "1");
span.baggage("second", "2");
span.baggage("third", "3");

And this was the header:
baggage=[third=3]

**Comment by RickyFrost** [comment]
Is w3c propagation for baggage the recommended approach for Helidon3? If not, what is the configuration to get similar propagation of baggage as in Helidon2?

**Comment by RickyFrost** [comment]
For completeness, I tried "jaeger" propagation and got this (same problem):
`uber-trace-id=[01f7571a75f210de6b338709774553fb:40f483ea820218e7:0:1], uberctx-third=[3]`

**Comment by dalexandrov** [comment]
Multiple baggage items support added in PR #7022
