### ISSUE TITLE
4.x: Custom Metrics API

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#7045]
Compliments #4868

(See #7261 which closes this issue by providing the new `MetersProvider` SPI interface coupled with builders for registering meters.)

We need to provide equivalents of `HealthCheck` and `HealthCheckProvider` for metrics.

With health with can do this:
```java
HealthCheck myHealthCheck = () -> HealthCheckResponse.builder()
                                                     .status(HealthCheckResponse.Status.UP)
                                                     .build();
HealthFeature healthFeature = HealthFeature.builder()
                                           .addCheck(myHealthCheck)
                                           .build();
ObserveFeature.builder()
              .addProvider(HealthObserveProvider.create(healthFeature));
```

---

Here is a quick and dirty sketch.

```java
// Assuming the Helidon Metrics API provides a type like this
interface Metric<T> extends Supplier<T> {
    String name();
    MetricType type();
    Optional<String> displayName();
    Optional<String> description();
    Optional<String> unit();
}

// We can have an interface to group metrics per registry
interface Metrics {
    MetricRegistryType registryType();
    List<Metric> metrics();
}

// SPI
interface MetricsProvider {
    List<Metrics> metrics(Config config);
}
```

Example:

```java
Metrics myMetrics = Metrics.builder()
                           .registryType(MetricRegistryType.VENDOR)
                           .metric(CounterSupplier.builder()
                                          .name("my-metric1")
                                          .value(() -> 5))
                           .metric(GaugeSupplier.builder()
                                          .name("my-metric2")
                                          .value(() -> 15))
                           .build();

MetricsFeature metricsFeature = MetricsFeature.builder()
                                              .addMetrics(myMetrics)
                                              .build();
ObserveFeature.create(metricsFeature);
```

Note the `CounterSupplier` and `GaugeSupplier` types to denote that the metrics not accumulating the values but just adapters that use a supplier to fetch the actual value.

This design targets integration module that expose "external" metrics (e.g. Neo4j), where it makes sense to not accumulate or compute a value over time but instead adapt an external metric value.

**Comment by tjquinno** [comment]
Under the current thinking, the proposed Helidon neutral metrics API (to be published for review very shortly) will likely include something like this for a type which resembles a gauge (value can increase or decrease):

```java
// From elsewhere:
interface SomeGaugeLikeType {
    double dblValue();
}

// In the Helidon app or integration:
SomeGaugeLikeType theGauge = ...; 
Gauge<Double> wrappedGauge = Metrics.gauge("myGauge", tagsForMyGauge, theGauge, SomeGaugeLikeType::dblValue);
```

Similarly, for a type which resembles a counter (value should increase only):
```java
interface SomeCounterLikeType {
    double theValue();
}

SomeCounterLikeType theCounter = ...;
Counter wrappedCounter = Metrics.counter("myCounter", tagsForMyCounter, theCounter, SomeCounterLikeType::theValue);
```

Note that the developer will be responsible for _not_ using a "wrapping" counter around a value that can decrease. 

These patterns are closely aligned (although, esp. in the case of counter, not identical) to what, for example, Micrometer supports.

**Comment by tjquinno** [comment]
Some elaboration thanks to a chat with @romain-grecourt 

Ideally, the integration would cause its meters to be made available in a way like this (for example, in https://github.com/helidon-io/helidon/blob/main/examples/integrations/neo4j/src/main/java/io/helidon/examples/integrations/neo4j/Main.java#L76)

```java
ObserveFeature.build()
    .addProvider(MetricsObserveProvider.create(MetricsFeature.builder()
                                              .addMetrics(neo4jMetrics)
                                              .build()))
```

In the similar case in that same method, this is how it's done with health checks. 

We will need to think about this some, though. 

Health checks can be instantiated at will via their constructors or simple factory methods and are therefore simpler objects to deal with in this scenario than are meters. 

Meters are created by registering them in a meter registry. Yes, that's very similar in spirit to invoking a factory method but in metrics we need to know which "factory" to use--which registry (such as application or base or vendor) and to check that the meter is not already registered.

I'm sure we can devise a suitable approach for this but it probably won't follow the exact pattern that works for health.

**Comment by tjquinno** [comment]
The recent merge of the neutral metrics API included an enhancement that might fill this need.

Metrics now uses service loading to find all implementations of the `MetersProvider` interface. That interface declares a method which returns a collection of `Meter.Builder`. The Helidon metrics code then uses all the supplied meter builders to register the corresponding meters automatically.
