### ISSUE TITLE
4.x: interceptors are broken by new builder API

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#7063]
Interceptors are a bit broken - see `InterceptorStackingTest#interceptorStacking`, and `FaultToleranceTest#testGreetNamedFallback` (in examples) - works in IDE, fails in maven with `Error in interceptor chain processing: service provider: GreetEndpoint:ACTIVE`

**Comment by trentjeff** [comment]
Can you comment some more on what is broken in the faulttolerance nima example?  I don't see anything commented on or disabled in `testGreetNamedFallback`
