### ISSUE TITLE
4.x: List injection should not fail on empty list

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#7082]
Currently when we inject a `List<ServiceProvider<SomeType>>`, if there is no provider of `SomeType` available, we get an exception.
The workaround is to manually use `PicoServices.realizedServices()` to lookup all with expected set to `false`

The default behavior I think should be to use empty list if none is found, as this is going to be used for looking up extensions by users (Http services, config sources etc.) that may not be present.

This should be fixed in:
`ConfigProducer` (if already merged)
`LoomServer` - now fails if no service discovered

**Comment by trentjeff** [comment]
I'm debating whether to just "fix this to allow nulls always", or proactively adding `@Injectable` to the API with an attribute `boolean atLeastOne` - thoughts??

**Comment by tomas-langer** [comment]
Please go with the "simple" approach of allowing injection of empty lists.
