### ISSUE TITLE
When will Helidon get support for Gradle?

### ISSUE THREAD

**Issue by aseemsavio** [helidon-io/helidon#7088]
This isn't an issue. I'm curious to know when there will be support for Gradle. Thanks.

**Comment by danielkec** [comment]
https://github.com/helidon-io/helidon/blob/helidon-3.x/examples/quickstarts/helidon-quickstart-mp/build.gradle

**Comment by romain-grecourt** [comment]
See also https://github.com/helidon-io/helidon/issues/1191
