### ISSUE TITLE
Blocking DBClient Part 2

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#7187]
Second phase of blocking DBClient work (post M1):

- [x] Fix examples to handle transactions in try/catch blocks, so the transaction is always either committed or rolled-back
- [x] Enabled disabled tests

**Comment by Tomas-Kraus** [comment]
@barchetta I'd like to do a bit more in this area. I prepared refactored version with few things that was removed by @romain-grecourt  because of time pressure during reactive removal.
I'll start with fixing tests and examples 1st but it would be nice to get those removed things back too.
