### ISSUE TITLE
4.x MediaContext single operator support

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#7205]
* Helidon Version: 4.0.0-ALPHA6
----------

In 3.x we had this:

```java
WebClient client = WebClient.builder()
        .addReader(JsonpSupport.reader())
        .build();
```

**Comment by tomas-langer** [comment]
This seems to be a feature that is not required - it can be easily worked around using a custom media support if needed
(disable discover services, add custom support, or add a support through service loader wiht higher weight than other registered ones).
