### ISSUE TITLE
4.x WebClient Security Digest Authentication

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#7207]
* Helidon Version: 4.0.0-ALPHA6

----------

We need an equivalent to `org.glassfish.jersey.client.authentication.HttpAuthenticationFeature`

This should support passing authentication directly to the client in form of properties.

```java
client.get(uri)
    .property(HTTP_AUTHENTICATION_USERNAME, username)
    .property(HTTP_AUTHENTICATION_PASSWORD, password)
    .request();
```

**Comment by tomas-langer** [comment]
This is supported for BasicAuthentication and Jwt. It cannot be supported for digest authentication, as we do not support outbound security with HTTP Digest.
I will refactor the constants used to have a single set on a shared place (currently duplicated in JwtAuthProvider and HttpBasicAuthProvider)
