### ISSUE TITLE
Support for Forwarded, X-Forwarded-Host, X-Forwarded-Proto headers

### ISSUE THREAD

**Issue by m0mus** [helidon-io/helidon#7244]
Related to #4767

**Comment by dalexandrov** [comment]
According to what I saw in the code, this is already done. @tjquinno would you please confirm, and I will close the issue. Thanks!

**Comment by tjquinno** [comment]
@dalexandrov As we discussed on Zoom yesterday, if @m0mus can clarify how this issue is different from #4767 that would help. Without that, yes, I believe this is a duplicate of #4767.

**Comment by dalexandrov** [comment]
Fixed
