### ISSUE TITLE
4.x SE/Nima static OpenAPI file support via the `/openapi` endpoint

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#7247]
4.x SE/Nima needs to be able to support a static OpenAPI definition file and serve it via the `/openapi` endpoint (via the OpenAPI feature implementation).

**Comment by barchetta** [comment]
This looks to be almost implemented. If I take `examples/quickstarts/helidon-quickstart-se` (which already enables `OpenApiFeature`) and add `src/main/resources/META-INF/openapi.yaml` it works!  But I think there are still some dots to be connected in configuration/builder. Or maybe it is related to my confusion.

I am a bit confused with configuring the static file. Do I  configure a file system path? Or a resource file name to be found on the class path?  I find the documentation unclear:

https://helidon.io/docs/v3/#/se/openapi/openapi

Under "Configuration options" the `static-file` option says "Sets the file system path" yet the default value is `META-INF/openapi.*` which looks like a resource name loaded from the classpath.  I find it confusing that the property is for setting a file system path, yet the default value is a resource name. If that is indeed the case we should clarify that in the docs/javadocs.
