### ISSUE TITLE
Request ID Provider

### ISSUE THREAD

**Issue by trentjeff** [helidon-io/helidon#7248]
Currently request IDs are internally assigned by Helidon.  We need a provider-based way to create an ID so that an integrator can customize their own scheme for assignments. Additionally, this request ID should be a tag that can be used for logging the same requestId.

**Comment by spericas** [comment]
Request IDs are currently generated very early in the processing pipeline, namely in `FowardingHandler`. The current approach simply increments an `AtomicLong`:

```
private static final AtomicLong REQUEST_ID_GENERATOR = new AtomicLong(0);
        
long requestId = REQUEST_ID_GENERATOR.incrementAndGet();
```

Creating an extension point to allow developers to generate their own IDs seems a bit odd at this stage in the pipeline. The creation of new IDs for OCI, and the handling of the `opc-request-id` header is better handled by JAX-RS filters much like most the processing in Helidon. Placing such a filter in a well-defined location (e.g. after auth) would enable developers to taylor the ID generation based on the contextual information available at that time. 

Thus, in regards of this issue, and assuming the use of MP, the extension point for the logic already exists in the form of a `ContainerRequestFilter` so there's nothing else needed in the core. If using a different API in the future (like Nima), we should use whatever filter functionality is available there.

**Comment by trentjeff** [comment]
A couple of comments:
1. Seems fine to me for making this a filter, but as you pointed out we will likely need to do something for non-MP in v4.
2. We would likely need to call the filter prior to auth.
3. How could this integrate into context propagation and the logging/MDC context?

**Comment by spericas** [comment]
Jakarta REST provides normal request filters (after matching, i.e. when the resource method is known based on the request) and pre-matching request filters. It's unclear to me which one would be needed here; assuming no resource information is needed, a pre-matching request filter could be defined as follows:

```
@ConstrainedTo(RuntimeType.SERVER)
@PreMatching
class OpcRequestId implements ContainerRequestFilter, ContainerResponseFilter {

    @Override
    public void filter(ContainerRequestContext requestContext) { ... }

    @Override
    public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext) { ... }
}
```

This sort of filter pattern is used in several Helidon modules today.
