### ISSUE TITLE
4.x: WebClient HTTP 100-Continue

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#7270]
For WebClient, we need to support this (esp. because of redirects when using streaming entity).

- io.helidon.nima.webclient.http1.HttpCallOutputStreamChain.ClientConnectionOutputStream#sendPrologueAndHeader
    - if we send expect continue, we need to do a timeout on read - and just send entity if response does not come
        this is needed for servers that do not support it, and where we would just hang indefinitely (or until timeout)

**Comment by Verdent** [comment]
Fixed by https://github.com/helidon-io/helidon/pull/7366
