### ISSUE TITLE
Interactive debugging in IDE is broken with annotation processing

### ISSUE THREAD

**Issue by trentjeff** [helidon-io/helidon#7312]
It would be convenient to use IntelliJ to interactively run and debug Junit tests.  However, it appears this is broken now on macOs after the new builders refactoring went in.

Useful links from Tim and Romain:
https://medium.com/@joachim.beckers/debugging-an-annotation-processor-using-intellij-idea-in-2018-cde72758b78a.  Used option 1. In step 3 - create a keyboard shortcut which toggles that setting.

**Comment by barchetta** [comment]
This has been greatly improved with the new design and implementation of builders and service registry.
