### ISSUE TITLE
[4.x] Missing Http Status codes for 421...429,431,451

### ISSUE THREAD

**Issue by rob-bygrave** [helidon-io/helidon#7343]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.0-M1
* Helidon SE
* JDK version: 20
* OS:  MacOS

----------

## Problem Description

`io.helidon.common.http.Http.Status` has public static fields for the Http status codes. In the `400` range it stops at `418` and the status codes for `421, 422, 423 ... 429, 431, 451` are missing.  

Refer: https://github.com/helidon-io/helidon/blob/main/common/http/src/main/java/io/helidon/common/http/Http.java#L551

## Suggested fix

Add entries in https://github.com/helidon-io/helidon/blob/main/common/http/src/main/java/io/helidon/common/http/Http.java for the status codes: `421, 422, 423 ... 429, 431, 451`

**Comment by tomas-langer** [comment]
A reasonable list of status codes: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/451

**Comment by rob-bygrave** [comment]
> I am not for including every code listed

FWIW I'm fine with not adding them all. The missing codes I expect to use myself and would really love to see added are **`422, 423, 429`** and maybe **`428`**.

- **422  Unprocessable Content** (Typically a validation error on the input content)
- **423  Locked**
- **429  Too Many Requests**

With these 3 added (plus _maybe_ 428?) I'd be content.


**FYI: Background motivation:**  
There is a performance benefit of using the pre-defined Http.Status values plus some documentation benefit for people reading the code rather than seeing an int value. I have code generation library (annotation processor) that will use the pre-defined Http.Status if they exist.

**Comment by rob-bygrave** [comment]
Reference links that might help via https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml with the status codes and related RFC

- https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.21
- https://www.rfc-editor.org/rfc/rfc4918.html#section-11.3
- https://www.rfc-editor.org/rfc/rfc6585.html#section-4

**Comment by tomas-langer** [comment]
I have added the requested statuses, PR is ready.
