### ISSUE TITLE
[4.x] OCI/CDI Refactor to use oci.yaml

### ISSUE THREAD

**Issue by trentjeff** [helidon-io/helidon#7382]
#7348 introduces `integrations/oci/runtime` as the central mechanism to ascertain any global oci config and auth supplier defined. We should converge to use it in 4.x.

In 3.x, we should do the following:
* backport the runtime to have a shared way of connecting to OCI
* existing CDI integration should check this if there is a valid configuration through the new API (e.g. oci.yaml), and if not, fallback to current 3.x behavior (for backward compatibility)
* in case there is a new MP ConfigSource based on OCI Vault, it should use the new approach (as obviously it cannot load MP config at the time it is being created

Site documentation should be also updated accordingly.

**Comment by arjav-desai** [comment]
We have decided to deprecate runtime (https://github.com/helidon-io/helidon/pull/9184/files) and related annotation processing module.
