### ISSUE TITLE
While downloading file the sha256 changes using helidon 2.6.1

### ISSUE THREAD

**Issue by SkyGlancer** [helidon-io/helidon#7407]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.6.2
* Helidon SE or Helidon MP se
* JDK version: 17
* OS: oracle linux 7
* Docker version (if applicable):

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
While sending a file using StreamingOutput, when we try to download  a large file(some specific file, around 511M) the sha256sum changes(binary file changes). (This is happening after upgrading to 2.6 from 1.x series)

`
	private final long THREAD_SLEEP_TIME = 1000;
	private final long EACH_CHUNK_SIZE = 10485760;
	private final int MEMORY_LIMIT_MB = 1 * 1024 * 1024;

			StreamingOutput fileStream =  new StreamingOutput(){
				@Override
				public void write(java.io.OutputStream output) throws IOException{
					long fileSize = filePathFinal.toFile().length();

					try(FileInputStream inputStream = new FileInputStream(filePathFinal.toFile())){
						do {

							byte[] buffer;
							if(fileSize > EACH_CHUNK_SIZE) {
								buffer = new byte[(int) EACH_CHUNK_SIZE];
							} else {
								buffer = new byte[(int) fileSize];
							}
							int len = inputStream.read(buffer);
							try {
								if (PooledByteBufAllocator.DEFAULT.pinnedHeapMemory() > MEMORY_LIMIT_MB) {
									Thread.sleep(THREAD_SLEEP_TIME);
								}
								if (PooledByteBufAllocator.DEFAULT.pinnedDirectMemory() > MEMORY_LIMIT_MB) {
									Thread.sleep(THREAD_SLEEP_TIME);
								}
							} catch (InterruptedException e) {
						
							}
							output.write(buffer);
							output.flush();
							fileSize = fileSize - len;
						} while(fileSize > 0);
					
					} finally {
					}
				}
			};
			return Response.ok(fileStream, MediaType.APPLICATION_OCTET_STREAM).build();`

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

**Comment by spericas** [comment]
@SkyGlancer You should be using `output.write(buffer, 0, len)`

**Comment by SkyGlancer** [comment]
Hi, I changed the code to output.write(buffer, 0, len) but still no luck

**Comment by spericas** [comment]
That's odd, someone would need to look at this in more detail. How does the file returned compare to the original? Is it of different length? If you could provide a _runnable_ reproducible, it may be easier for someone to evaluate faster.

**Comment by romain-grecourt** [comment]
Reproduced with 2.x and 3.x:

```java
@Path("/download")
public class DownloadResource {

    @GET
    @Path("{fname}")
    @Produces(MediaType.APPLICATION_OCTET_STREAM)
    public Response download(@PathParam("fname") String fname) {
        return Response.ok()
                .entity((StreamingOutput) output -> Files.copy(Paths.get(fname), output))
                .build();
    }
}
```

```bash
dd if=/dev/urandom of=sample.txt bs=100m count=1
```

```bash
for i in $(seq 10) ; do curl http://localhost:8080/api/sample.txt -o /tmp/sample.txt 2> /dev/null; cmp sample.txt /tmp/sample.txt || break ; sleep 1 ; done
```

**Comment by barchetta** [comment]
I was able to reproduce as well.  The failure is intermittent. File size is correct but content differs.  Changing the value of `server.backpressure-strategy=` seems to alter behavior a bit  for me.

With both 2.6.2 and 3.2.2

* `server.backpressure-strategy=AUTO_FLUSH`: fails often
*  `server.backpressure-strategy=UNBOUNDED`: seems to work-around the problem for me (can't reproduce)

But, Romain said setting UNBOUNDED did not work-around the problem for him.

**Comment by SkyGlancer** [comment]
Hi @barchetta What does UNBOUNDED backpressure strategy mean, does it mean that whole file will be loaded in the memory?

**Comment by barchetta** [comment]
@SkyGlancer my understanding is that it means the server's reactive layer will not apply back-pressure to whoever is writing the data, so with a slow (reading) client it can end up buffering  in memory.  Some info here: [BackpressureStrategy](https://helidon.io/docs/v2/apidocs/io.helidon.webserver/io/helidon/webserver/BackpressureStrategy.html). @danielkec might have more insights. 

It looks like your code does some throttling itself.  As a data point, could you try setting UNBOUNDED and see if it changes the symptoms you see?

**Comment by spericas** [comment]
@barchetta Sounds like buffer ordering is somehow not preserved as part of the backpressure logic.

**Comment by SkyGlancer** [comment]
Hi @barchetta @spericas I am able to get around the problem with  "backpressure-strategy": "UNBOUNDED" but we need to evaluate if this is correct. I am worried that it can cause OOM memory issues. Do we know why AUTOFLUSH is not working as expected?

**Comment by spericas** [comment]
@SkyGlancer Using UNBOUNDED is a workaround for now, but we should really understand what is going on with AUTO_FLUSH. I will take another look at it today and report back.
