### ISSUE TITLE
4.x: Update Hibernate version from 6.1.7 to 6.2.X 

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#7448]
Update Hibernate version from 6.1.7 to 6.2.X

As part of this remember to:
1. Remove exclusion of jandex from `hibernate-core` dependency (this was a work-around during upgrade to Jandex 3)
2. Remove force upgrade of `byte-buddy` (this was a work-around for Java 21 support)

Note that there have been a couple attempts at the upgrade:
- #7433
- #7426

**Comment by lscoughlin** [comment]
can we get this added to the 3.x line as well?
