### ISSUE TITLE
HAProxyProtocol support in webserver

### ISSUE THREAD

**Issue by ggsrivas** [helidon-io/helidon#7458]
## Environment Details
* Helidon Version: 3.x
* Helidon SE or Helidon MP: Helidon SE
* JDK version: 17
* OS: OS agnostic
* Docker version (if applicable):

----------

## Problem Description
My Webserver is built using Helidon. I want to enable [HAProxy proxy-protocol](https://www.haproxy.com/blog/use-the-proxy-protocol-to-preserve-a-clients-ip-address) on my Load balancer that will require this webserver to parse the response correctly. but, I don't see support for proxy-protocol in Helidon. 
It would have been helpful if Helidon had support for custom childHandlers for NettyWebServer so, that I could have added this handler myself. See below screenshot,

<img width="1018" alt="Screen Shot 2023-08-25 at 8 53 59 AM" src="https://github.com/helidon-io/helidon/assets/7676582/63542f6c-3c12-49b6-b1e9-86e1401f80af">

This is a feature enhancement request, not a bug. It would be great if this support is added directly in the framework and it can be enabled as a configuration. Support for custom childHandler will also resolve this gap. Please note that this support already exists in Netty but since, there is no way to enable it with Helidon.

references:
Proxy-protocol: https://www.haproxy.com/blog/use-the-proxy-protocol-to-preserve-a-clients-ip-address
Netty proxy protocol: https://netty.io/4.0/api/io/netty/handler/codec/haproxy/HAProxyProxiedProtocol.html

**Comment by spericas** [comment]
@ggsrivas Is the use of HTTP headers to convey client info not a viable alternative in your case?

**Comment by spericas** [comment]
@ggsrivas I put together a prototype based on what you shared with me. For now, it only adds X-Forwarded-For with some client info as an example (it also adds a config flag to enable the protocol). There's a single V1 test.

https://github.com/spericas/helidon/pull/3/files

Please take a look and let me know what you think.

**Comment by ggsrivas** [comment]
The changes look good. Thanks.

**Comment by spericas** [comment]
@ggsrivas Could you comment on which other headers are you expecting? Also on how do you expect OCI's LB data to be available? Thanks.

**Comment by spericas** [comment]
Since we are nearly done supporting this in 4.x (#7829) and there is no longer an immediate requirement to support this in 3.x, I am closing this issue. We can reopen it at later time and use the prototype linked above as a starting point.
