### ISSUE TITLE
4.x: HttpClient first URI segment is omitted if path starts with //

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#7474]
## Environment Details
* Helidon Version: 4.0.0-M1
* Helidon SE 
----------

When the path of a URI starts with `//` the first segment is omitted.
E.g. `http://localhost:8080//foo/bar` will make a request to `/bar` !

This is awkward as it is common to have a trailing slash in a URI (E.g. `http://localhost:8080/`), resolving that URI without normalizing can lead to a path that starts with a double slash.

E.g.

```java
String uri = "http://localhost:8080/"
String baseUri = uri + "/foo/bar";
```

```java
URI uri = URI.create("http://localhost:8080/")
String baseUri1 = uri + "/foo/bar"; // bad
URI baseUri2 = uri.resolve("/foo/bar"); // good
String baseUri3 = uri.normalize() + "/foo/bar"; // good
```

---

Reproducer:

```java
WebServer server = WebServer.builder()
        .routing(r -> r.any("/{+}", (req, res) -> res.send(req.requestedUri().path().toString())))
        .build()
        .start();
try {
    Http1Client client = Http1Client.create();
    String baseUri = "http://localhost:" + server.port();
    System.out.println(client.get(baseUri + "//foo/bar").request(String.class).entity());
    // prints /bar
    System.out.println(client.get(baseUri + "/foo/bar").request(String.class).entity());
    // prints /foo/bar
} finally {
    server.stop();
}
```

---

Note that I ran into this while writing a unit test that retrieved the URI for given socket:
```java
@BeforeAll
static void init(@Socket("backend") URI uri) {
    // uri has a trailing /
}
```

**Comment by tomas-langer** [comment]
We also need to support (from conversation with @romain-grecourt, and other expected cases):
```
WebClient.builder().baseUri("http://localhost:8080//foo/bar")
webclient.get()
 .uri("http://localhost//foo/bar")
```

This is only for the initial leading `/` being duplicated, do not fix anywhere else

**Comment by danielkec** [comment]
@romain-grecourt @tomas-langer This is actually a server issue eg.: `URI.create("//foo/bar").normalize().getPath() --> "/bar"`, do we also want to introduce URI normalization to the client?

**Comment by danielkec** [comment]
Feels like a bug in the `java.net.URI` - [JDK-8316799](https://bugs.openjdk.org/browse/JDK-8316799)

**Comment by danielkec** [comment]
Huh not really a JDK bug, TIL about `net_path` //foo is a net_path as defined by [RFC 2396](https://www.ietf.org/rfc/rfc2396.txt)
```ebnf
absoluteURI = scheme ":" ( hier_part | opaque_part )
hier_part = ( net_path | abs_path ) [ "?" query ]
net_path = "//" authority [ abs_path ]
abs_path = "/" path_segments
opaque_part = uric_no_slash *uric
uric_no_slash = unreserved | escaped | ";" | "?" | ":" | "@" |"&" | "=" | "+" | "$" | ","
```
