### ISSUE TITLE
How do I mock a CDI instance?

### ISSUE THREAD

**Issue by coolboy0961** [helidon-io/helidon#7502]
## Environment Details
* Helidon Version: 3.2.2
* Helidon MP
* JDK version: 17.0.7
* OS: MacOS 13.4.1

----------

## Problem Description
I'm in the process of writing API tests for an API using Helidon MP.
The problem is that I don't have a way to mock some of the CDI instances.
I would like to ask that if Helidon test provides the ability to mock some of the CDI instances and another CDI instances will be created automatically？

Here is the example of api test.You can know exactly what I want to do.
[https://github.com/d-kanai/nuxt-helidon-practice/blob/main/helidon/helidon-quickstart-mp/src/test/java/io/helidon/examples/ quickstart/mp/modules/user/UserApiTest.java](https://github.com/d-kanai/nuxt-helidon-practice/blob/main/helidon/helidon-quickstart-mp/src/test/java/io/helidon/examples/quickstart/mp/modules/user/HelidonUserApiTest.java)

## Steps to reproduce
```
git clone https://github.com/d-kanai/nuxt-helidon-practice.git
cd nuxt-helidon-practice/helidon/helidon-quickstart-mp
mvn test
```
then you can see the following error caused by that the userRepository isn't mocked.
```
Wanted but not invoked:
userRepository.addUser(
    <Capturing argument: User>
);
-> at io.helidon.examples.quickstart.mp.modules.user.UserRepository.addUser(UserRepository.java:11)
Actually, there were zero interactions with this mock.
```

**Comment by klustria** [comment]
Check [Testing Helidon](https://medium.com/helidon/testing-helidon-9df2ea14e22) writeup and see if you can leverage addBean to create a dummy/mocked bean. Also, you can check out this repo: https://github.com/klustria/helidon-mp-ocivault-unittest/blob/master/README.md for some examples of using that approach.

**Comment by coolboy0961** [comment]
I think I found the answer.
I updated the code.
[HelidonUserApiTest.java](https://github.com/d-kanai/nuxt-helidon-practice/blob/main/helidon/helidon-quickstart-mp/src/test/java/io/helidon/examples/quickstart/mp/modules/user/HelidonUserApiTest.java)

By adding @Alternative and @Priority(1), I can just alternative which class I want to mock, and the other CDI instance will be inject normally.
```
    @Alternative //これは代替のクラスであり、通常のUserRepositoryImplクラスの代わりにテストで使用されることを示します。
    @Priority(1) // 同じCDIのInterfaceにInjectクラスが複数ある場合に、このクラスが優先されるようにします。
    static class FakeUserRepositoryImpl implements UserRepository {

        @Override
        public void addUser(User user) {
            System.out.println("FakeUserRepositoryImpl.addUser is called.");
        }
    }
```
