### ISSUE TITLE
Please provide support for "None; Secure" option in io.helidon.common.http.SetCookie.SameSite. The NONE option is no longer useable with Chrome browsers. 

### ISSUE THREAD

**Issue by Reza-1** [helidon-io/helidon#7519]
## Environment Details
* Helidon Version: 3.2.2
* Helidon MP
* JDK version: 17
* OS: N/A
* Docker version (if applicable): N/A

----------

## Problem Description
[The io.helidon.common.http.SetCookie.SameSite ](https://helidon.io/docs/latest/apidocs/io.helidon.common.http/io/helidon/common/http/SetCookie.SameSite.html) is an Enum that provides accepted values for the SameSite attribute when Cookie is being set. Currently it has three options "NONE", "LAX" and "STRICT".
The "NONE" option doesn't work on Chrome browsers anymore because Chrome expects a word "Secure" after the "None" e.g.  **SameSite=None; Secure** for this type of Cookies (this is done so that it can only be used over HTTPS, according to this link https://developers.google.com/search/blog/2020/01/get-ready-for-new-samesitenone-secure )

This restriction by Chrome makes the "NONE" option of io.helidon.common.http.SetCookie unusable, by blocking the Set-Cookie and indicating in Chrome DevTool that "Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`" .  More details can be found here :  https://chromestatus.com/feature/5633521622188032

furthermore an attempt to set the option to "None; Secure" (e.g. SECURITY_PROVIDERS_0_OIDC_COOKIE_SAME_SITE ) causes IllegalArgumentException as expected since that is not a valid Enum option. e.g.
`Exception in thread "main" java.lang.IllegalArgumentException: No enum constant io.helidon.common.http.SetCookie.SameSite.NONE; SECURE
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at io.helidon.common.http.SetCookie$SameSite.valueOf(SetCookie.java:345)
	at io.helidon.security.providers.oidc.common.OidcConfig$Builder.cookieSameSite(OidcConfig.java:1514)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.helidon.config.ConfigValue.ifPresent(ConfigValue.java:227)
	at io.helidon.security.providers.oidc.common.OidcConfig$Builder.config(OidcConfig.java:1115)
	at io.helidon.security.providers.oidc.common.OidcConfig.create(OidcConfig.java:440)
	at io.helidon.security.providers.oidc.OidcProvider$Builder.config(OidcProvider.java:340)
	at io.helidon.security.providers.oidc.OidcProvider.create(OidcProvider.java:110)
	at io.helidon.security.providers.oidc.OidcProviderService.providerInstance(OidcProviderService.java:45)
	at io.helidon.security.Security$Builder.providerFromConfig(Security.java:1139)
	at io.helidon.security.Security$Builder.lambda$fromConfig$1(Security.java:994)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.helidon.security.Security$Builder.lambda$fromConfig$2(Security.java:994)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.helidon.config.ConfigValue.ifPresent(ConfigValue.java:227)
	at io.helidon.security.Security$Builder.fromConfig(Security.java:993)
	at io.helidon.security.Security$Builder.config(Security.java:851)
	at io.helidon.microprofile.security.SecurityCdiExtension.configure(SecurityCdiExtension.java:70)
        .....`

Please update the support for "NONE" option or include a new option for "**None; Secure**" in io.helidon.common.http.SetCookie.SameSite so that this type of Cookie option can continue to work on Chrome browsers.

**Comment by Reza-1** [comment]
please note other browsers are also going to disallow "None" option without being "Secure"

Here is a sample response from Firefox:
Cookie “almp.JSESSIONID” will be soon rejected because it has the “SameSite” attribute set to “None” without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by klustria** [comment]
@Reza-1 , can you please give an example of how you set SameSite in your Helidon code?

**Comment by Reza-1** [comment]
I built a service that uses OIDC similar to https://github.com/helidon-io/helidon/tree/helidon-3.x/examples/microprofile/idcs
and override cookie setting by adding  cookie-same-site for oidc provider in application.yaml e.g.
```
security:
   ....
   providers:
     - oidc:
         ....
         cookie-same-site: "None"
```
https://helidon.io/docs/latest/index.html#/mp/security/providers

**Comment by klustria** [comment]
From the same doc you pointed, check out `cookie-secure`. This flag as described, when set to true, will set the `Secure` attribute in your cookie and will satisfy the requirement of : 
```
If SameSite=None is set, the cookie Secure attribute must also be set (or the cookie will be blocked).
```
So try adding  `cookie-secure: true`  like below.
```
security:
   ....
   providers:
     - oidc:
         ....
         cookie-same-site: "None"
         cookie-secure: true
```

**Comment by klustria** [comment]
Using unit test and  cookieSecure(true) on OidcConfig.builder() (which is equivalent to setting `cookie-secure: true` as mentioned above) , this has been tested that `Secure` attribute is injected into the cookie:

```
    @Test
    void testSameSiteNoneWithSecure() {
        OidcConfig config = OidcConfig.builder()
                // The next 3 parameters need to be set or config builder will fail
                .identityUri(URI.create("https://identity.oracle.com"))
                .clientId("client-id-value")
                .clientSecret("client-secret-value")
                .cookieSameSite("None")
                .cookieSecure(true)
                // Set to false so it will not load metadata
                .oidcMetadataWellKnown(false)
                .build();
        OidcCookieHandler tokenCookieHandler = config.tokenCookieHandler();
        assertThat("Cookie options", tokenCookieHandler.createCookieOptions(), containsString("Secure"));
        assertThat("Cookie options", tokenCookieHandler.createCookieOptions(), containsString("SameSite=None"));
    }
```

**Comment by Reza-1** [comment]
Thanks
