### ISSUE TITLE
Plans for gRPC streams in Helidon Nima?

### ISSUE THREAD

**Issue by edvardfagerholmsc** [helidon-io/helidon#7609]
What are Helidon Nima's plans for handling gRPC streams? The gRPC proto compiler currently does not generate blocking stubs for server side streams, i.e. they only include async code. With virtual threads the "right" API would presumably be to write to the stream with a blocking call.

Currently, Helidon relies on the stubs produced by the official Google proto compiler. Are there any plans to write wrappers around the stubs to provide a more idiomatic API for use with virtual threads?

Has anyone tried to produce any Nima examples with best practices for writing a gRPC streaming application?

**Comment by spericas** [comment]
Tracked by #5418
