### ISSUE TITLE
4.x: standardize use of GlobalConfig by Helidon components

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#7627]
Currently we have some inconsistencies with the use of GlobalConfig by Helidon components. For example WebServer requires the following:

```
        Config config = GlobalConfig.config();
        WebServer server = WebServer.builder()
                .config(config.get("server"))
```

But other components, like `ObserveFeature`, do not require the passing of config. For example the constructor for `ObserveFeature.Builder` uses GlobalConfig by default:

```
private Builder() {
     config(GlobalConfig.config().get("observe"));
}
```

In general I think discovering config by default is a good thing, and I'm not sure why we are not doing it for WebServer.  Some things to consider

1. Make sure all Helidon components that have config use GlobalConfig by default (including WebServer)
2. Discuss if we should provide a way to force Builders  to NOT use GlobalConfig, so that one may truly build from scratch with no interference. 
3. Discuss if we should require the user to always explicitly set GlobalConfig and not implicitly initialize it. Builders could either fail or conditionally process global config if set.

Once we settle on the preferred pattern for initializing config we need to ensure all archetypes and examples show that (see issue #7628).

**Comment by tomas-langer** [comment]
The `GlobalConfig` is intended for components that are initialized automagically 
(such as MetricsRegistry). There are some leftovers from the prototype where we did not support config on APIs. I am not sure we want to pick the config automatically, as our APIs should have the config method and honor it.

**Comment by romain-grecourt** [comment]
`ObserveFeature.builder()` currently calls `ObserveFeature.Builder.config(Config)` with `GlobalConfig.config()`.
I just searched for the usage of `GlobalConfig` in metrics but did not find it.

Can we consider reverting all current SE usages of `GlobalConfig` for consistency ?

**Comment by tomas-langer** [comment]
`GlobalConfig` should be used for componets that require static setup. It should not be used for components that are configured by hand.

**Comment by barchetta** [comment]
See PR #7625 
To Summarize:

* Config must be explicitly passed to components (as is shown above for WebServer)
* The Gobal config can be retrieved using `Config.global()`  (and set with `Config.global(config)`)
* Not setting the global config uses the default config and is therefore the same as `Config.global(Config.create())`
