### ISSUE TITLE
4.x: demonstrate proper use of GlobalConfig in examples and archetypes

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#7628]
This issue depends on issue #7627 to be resolved first. Once it is we need to make sure that documentation, examples and archetypes illustrate the preferred pattern for setting up config. For example:

```
// This loads default config sources including `application.yaml`.  If you want to create custom config sources you can 
// do that here instead of just using the default config.
Config config = Config.create();
GlobalConfig.config(config);
```

With GlobalConfig we no longer need to pass config to the `routing` method found in many examples, nor to the `HttpService` found in many examples. Instead any customer code that needs config can do something like:

```
Config config = GlobalConfig.config().get("myapplication");
```

**Comment by tvallin** [comment]
Close thanks to #7655 and #7664, thanks @barchetta
