### ISSUE TITLE
HttpFeature discovery mechanism

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#7630]
The goal of this issue is to discuss and maybe implement a generic inversion of control for HttpFeature.

As of 4.0.0-M2, only `ObserveFeature` provides a way to discover automatically register HttpFeature in the routing. However there are still some Helidon features that need to be registered manually:

- OpenApiFeature
- SecurityFeature
- AccessLogFeature

This would re-enforce the meaning of features, they are pluggable and can be activated simply by having them on the classpath. 

```java
static void routing(HttpRouting.Builder routing) {
    // user only
    routing.register("/greet", GreetService::new);
}
```

This discovery mechanism could be built-in `HttpRouting.Builder` and enabled by default, with an option to disable the discovery:

```java
static void routing(HttpRouting.Builder routing) {
    routing.useSystemServices(false)  // 3.x style, what you see is what you get
            .register("/greet", GreetService::new)
}
```

---

A filtering mechanism would be needed, e.g. If a user wants to only load the Helidon features dynamically and avoid all others.

An implicit override mechanism, to programmatically customize features that would otherwise be registered dynamically.

E.g.
```java
static void routing(HttpRouting.Builder routing) {
    healthCheck = new TestHealthCheck("message");
    HealthObserver health = HealthObserver.create(healthCheck);
    routing.register("/greet", GreetService::new)
            .addFeature(ObserveFeature.builder()
                           .addObserver(health));
}
```

**Comment by tomas-langer** [comment]
It may be better to switch to using `ServiceRegistry` for this kind of behavior. 
I am already looking into the "filtering" feature (so you can register by hand something that woudl otherwise be service loaded - we do not want it twice)

**Comment by romain-grecourt** [comment]
Couldn't we replace most usage of `HelidonServiceLoader` with `ServiceRegistry` ?

**Comment by tomas-langer** [comment]
I do not want `ServiceRegistry` to be a mandatory requirement fo webserver, as it must use the full inject-runtime, which increases the size for the basic webserver.
Also anybody that wants to use just the webserver would have that dependency. 
We will support this with Helidon declarative, where any `HttpFeature` marked as `@Singleton` will be added to server (this is already working with the inject based main class)
