### ISSUE TITLE
4.x: Javax annotation replacer in TypeInfo

### ISSUE THREAD

**Issue by Verdent** [helidon-io/helidon#7644]
Implement a single point, which will be responsible for finding and replacing all javax annotations. Identified annotations will be replaced with their jakarta equivalent and updated in the `TypeInfo` object.

This will allow us to simplify the code since code generator will be working with just jakarta version of these annotations.

**Comment by tomas-langer** [comment]
See `io.helidon.codegen.spi.AnnotationMapperProvider`. This is already supported for Helidon Codegen
