### ISSUE TITLE
Ability for helidon server to handle ProxyProtocol

### ISSUE THREAD

**Issue by andimullaraj** [helidon-io/helidon#7672]
The Helidon server seems to provide support for assessing the type of connection based on incoming bytes. Based on that, it looks like the developers can potentially implement a ProxyProtocol handler which will consume in plain connection the first proxy-protocol bytes, then upgrade the connection to SSL. I am suggesting this implementation/handler be available in Helidon server.

In particular:
* I am not suggesting that the Helidon server infer if proxy-protocol bytes are received and optionally consume them. Instead, the setting is static for a certain server-port and the bytes should always be there.
* Support for proxy-protocol v1 and v2
* The fetched values should be made available via the connection properties

**Comment by barchetta** [comment]
See also #7458

**Comment by trentjeff** [comment]
See also https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt
