### ISSUE TITLE
4.x: MP quickstart archetype has unnecessary metrics dependencies

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#7700]
* Helidon Version: 4.0.0-RC1
* Helidon MP
----------

## Problem Description

Generate a 4.0.0-RC1 MP quickstart using the CLI and the `pom.xml` has:

```
        <dependency>
            <groupId>io.helidon.metrics</groupId>
            <artifactId>helidon-metrics</artifactId>
            <scope>runtime</scope>
        </dependency>
```
And 
```
        <dependency>
            <groupId>io.helidon.metrics</groupId>
            <artifactId>helidon-metrics</artifactId>
        </dependency>
```
I don't think it should have either of these.

**Comment by tjquinno** [comment]
I believe Joe is correct here.

At one point we planned to use bundles such as `helidon-metrics` but, at least for now, we have moved away from that.

For MP, depending on `helidon-microprofile-metrics` and `org.eclipse.microprofile.metrics:microprofile-metrics-api` should be what we want for API dependencies. The MP QuickStart depends on the full Helidon MP bundle which includes those already.

And (as we've discussed earlier), these need to be present also:

```
        <dependency>
            <groupId>io.helidon.webserver.observe</groupId>
            <artifactId>helidon-webserver-observe-metrics</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.helidon.metrics</groupId>
            <artifactId>helidon-metrics-system-meters</artifactId>
            <scope>runtime</scope>
        </dependency>
```
