### ISSUE TITLE
Config doc example of `onChange` incorrectly returns a `boolean`

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#7716]
## Environment Details
* Helidon Version: 2.x, 3.x
* Helidon SE or Helidon MP SE
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
`Config.onChange` actually accepts a `Consumer<Config>` but the doc page under `Registering Actions` section shows a lambda which returns a `boolean` which does not work.

## Steps to reproduce
Try to use the code example for `onChange` in the doc. It does not compile.

**Comment by Captain1653** [comment]
@romain-grecourt Can you close this issue, please?
