### ISSUE TITLE
4.x: add native-image.properties to archetypes

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#7717]
With the new version of graalVM native-image, we need to register all bean types to be initialized at build time (as they end up in the image heap). 
To support this, we should generated the following file:
`src/main/resources/META-INF/groupId/artifactId/native-image.properties`
with the following content:
```
Args=--initialize-at-build-time=packageName
```

`groupId`: maven groupId
`artifactId`: maven artifactId
`packageName`: package where we generate beans (such as JAX-RS resources), if multiple packages, then the top most package

**Comment by barchetta** [comment]
`native-image.properties` appears to be in the wrong location. See #7824
