### ISSUE TITLE
Helidon 4: METRIC_CONFIG_KEY duplicated?

### ISSUE THREAD

**Issue by hrstoyanov** [helidon-io/helidon#7759]
... in **MetricsConfigBlueprint.java** and **ComponentMetricSettings.Builder.java** , with the same value - "metrics"?

**Comment by barchetta** [comment]
```
grep -r -I --include "*.java" "String METRICS_CONFIG_KEY"
./metrics/api/src/main/java/io/helidon/metrics/api/ComponentMetricsSettings.java:        String METRICS_CONFIG_KEY = "metrics";
./metrics/api/src/main/java/io/helidon/metrics/api/MetricsConfigBlueprint.java:    String METRICS_CONFIG_KEY = "metrics";
```

**Comment by tjquinno** [comment]
Closing this - "works as designed."

Although the two constants happen to have the same value, they are not used for the same purpose.

The one in `ComponentMetricSettings.Builder` designates the config key for metrics settings _within individual components_ which support metrics.

In contrast, the one in `MetricsConfigBlueprint` is the config key for the top-level metrics configuration.

Although unlikely, it is possible that one of these values could change in the future while the other stayed the same. They are used for different purposes.
