### ISSUE TITLE
4.x: Use `System.Logger` instead of JUL where applicable

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#7792]
Revisit all usages of Java Util Logging (JUL) and replace relevant cases with `System.Logger`, so we can remove the dependency on `java.logging` from most of our modules.

The dependency is expected in:
- `helidon-logging-jul` - the integration with JUL
- temporary as a workaround for shutdown hook (I think in webserver), unless already abstracted (or abstract it into our logging implementations)
- examples and test scopes (to correctly log in these cases)

**Comment by jbescos** [comment]
There is one module that the API depends on Logger Level:
https://github.com/helidon-io/helidon/blob/e0a91cb10c1488516e8b14513a4e7a79402d6232/common/reactive/src/main/java/io/helidon/common/reactive/Single.java#L576
