### ISSUE TITLE
4.x: add `helidon-logging-jul` as a test dependency to some modules

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#7799]
Some of the modules now print a long stacktrace as the configured appender is not available (as `helidon-logging-jul` is no longer a transitive dependency coming from config as it used to be (wrongly)).

Check output of maven, and add the module as a test dependency to those modules that print the stacktrace (tests do not fail, just the logging configuraiton).

Search for `HelidonConsoleHandler` in the build output

**Comment by jbescos** [comment]
Running the test I don't see any stack traces in the output console.

**Comment by romain-grecourt** [comment]
> Running the test I don't see any stack traces in the output console.

You probably need to grep for the output files under target/surefire-reports
