### ISSUE TITLE
Memory leak observed while using helidon connector in Async mode

### ISSUE THREAD

**Issue by nairiti-sharma** [helidon-io/helidon#7821]
## Environment Details
* Helidon Version: 2.6.2 and 3.2.2 (it should be valid for all 2.X and 3.X versions)
* JDK version: 17

----------

We are testing a benchmark that uses helidon connector in async mode. Attached is a snapshot showing the way client gets initiated. In this case, a new client gets created with each iteration and it was observed that hash map for Channel Cache doesnt get cleared. There are 2 issues obtained here.
            
1. CHANNEL_CACHE is a map of sets. When we use a single client, there is a single Key (ConnectionIdent) and an associated Set to hold the channels. But, when multiple clients are created, there are multiple Keys and the CHANNEL_CACHE keeps growing. So, the values within the ConnectionIdent obect is changing in the case of new client creation because of which computeIfAbsent is failing the hashCode check resulting in creating a new Key and value (HashSet) getting inserted into the  CHANNEL_CACHE. This accounts for the leak observed as the CHANNEL_CACHE keeps growing.      
      
2. removeChannelFromCache doesnt check if the set is empty, resulting in keys with empty sets. It is recommended to add a check to see if the set is empty or not. If it is empty, it can be nullified.

Though creating a new client for every call is an anti-pattern , it is a common mistake and should not cause a memory leak.
This is valid both for Helidon 2.X and 3.X .

**Comment by nairiti-sharma** [comment]
![PSRClient](https://github.com/helidon-io/helidon/assets/56336090/2ee31b94-bd16-44c4-b1d1-642537aaa5e3)
![HeapDumpHashEntriesPSRTestCase](https://github.com/helidon-io/helidon/assets/56336090/e3817039-3981-462c-a05e-6493965042ff)
![HeapDump1PSRTestCase](https://github.com/helidon-io/helidon/assets/56336090/b1c4d665-172b-42d6-b07e-c3e7736f369e)

**Comment by ChiradeepRamaprasad** [comment]
Comment on Point 2 -

removeChannelFromCache doesn't check if the set is empty, resulting in keys with empty sets. It is recommended to add a check to see if the set is empty or not. If it is empty, the key can be removed.

Example Code: 

removeChannelFromCache -
 
       Set<ChannelRecord> channelSet = CHANNEL_CACHE.get(key);
       if (channelSet != null) {
           // Remove the channel record from the set
           channelSet.remove(new ChannelRecord(channel));
          
           // Check if the set is empty
           if (channelSet.isEmpty()) {
               // If it's empty, remove the entry from CHANNEL_CACHE
               CHANNEL_CACHE.remove(key);
           }
       }
