### ISSUE TITLE
4.x SE `HealthCheckResponse` no longer supports a name

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#7827]
## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP SE
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
The `HealthCheckResponse` interface (and its `record` implementation `HealthCheckResponseImpl`) and the associated builder do not support a name.

The result is that developers cannot create a convenient lambda which returns a health check response that also has a name. Lambda-based responses appear, with details enabled in the output, like this:
```
{
  "status": "UP",
  "checks": [
    {
      "name": "Main$$Lambda/0x00000001320ac800",
      "status": "UP",
      "data": {
        "exampleHealthCheck": "looking-good"
      }
    },
...
}
```

Developers can, of course, write a class which implements `HealthCheck` and apply the name to the check (not the response) but that approach does not allow the convenience of using in-line lambdas.

## Steps to reproduce
Add a health check response in-line something like this:
```
ObserveFeature observe = ObserveFeature.builder()
    .addObserver(HealthObserver.builder()
    .addCheck(() -> HealthCheckResponse.builder()
             .status(readyTime.get() != 0)
             .detail("time", readyTime.get())
             .build(), HealthCheckType.READINESS)
```
You get a name like the example above.

**Comment by tomas-langer** [comment]
The name defaults to the simple name of the class. To get a nice name, you can implement the `HealthCheck` interface, where you can provide custom name, path, and type of the Health check.

**Comment by tomas-langer** [comment]
Maybe we could add another method to HealthObserver.builder(), such as:
```
addCheck(Supplier<HealthCheckresponse> healthCheck, HealthCheckType type, String name)
```
So the user code could be:
```
.addCheck(() -> HealthCheckResponse.builder()
             .status(readyTime.get() != 0)
             .detail("time", readyTime.get())
             .build(), 
             HealthCheckType.READINESS,
            "Nice name")
```
