### ISSUE TITLE
Upgrade to latest Tyrus when available

### ISSUE THREAD

**Issue by spericas** [helidon-io/helidon#7850]
## Problem Description
We need a fix for #7703. Latest Tyrus should be integrated when available.

**Comment by jansupol** [comment]
We have released Tyrus 1.21 and 2.0.5

**Comment by jansupol** [comment]
Tyrus 2.1.4 (EE11) will be released shortly

**Comment by barchetta** [comment]
Current Tyrus versions in Helidon:

* Helidon 4.0.0 (EE 10): Tyrus 2.0.4
* Helidon 3.2.3 (EE 9): Tyrus 2.0.4
* Helidon 2.6.3 (EE 8): Tyrus 1.17

**Comment by spericas** [comment]
@barchetta We should upgrade this for 4.0.1 (or whatever we call the next version)
