### ISSUE TITLE
Custom TCP protocol

### ISSUE THREAD

**Issue by anirbanmu** [helidon-io/helidon#7901]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.0.0
* Helidon SE / Helidon MP

----------

## Problem Description
👋Hello, let me know if I should post this somewhere else since it's not a true issue but rather more of a question. I was wondering if there is any planned support for using Helidon -- I'm specifically wondering about Níma -- with a custom TCP protocol? Or perhaps this is already possible? If already possible any pointers on how to accomplish this would be amazing.

PS -- congrats on the release of 4.0.0!

**Comment by romain-grecourt** [comment]
This is do-able, however there are some rough edges.

You need to implement at least two interfaces:
- [ServerConnectionSelector](https://github.com/helidon-io/helidon/blob/4.0.0/webserver/webserver/src/main/java/io/helidon/webserver/spi/ServerConnectionSelector.java)
- [ServerConnection](https://github.com/helidon-io/helidon/blob/4.0.0/webserver/webserver/src/main/java/io/helidon/webserver/spi/ServerConnection.java)

Ideally you would also define your own [Routing](https://github.com/helidon-io/helidon/blob/4.0.0/webserver/webserver/src/main/java/io/helidon/webserver/Routing.java) to separate handlers and procotol support.

```java
WebServer.builder()
        .addConnectionSelector(new MyServerConnectionSelector())
        .addRouting((MyRouting) (inputStream, outputStream) -> {
            // handler...
        })
        .build()
        .start();
```

`ServerConnectionSelector` detects the protocol and provides a `ServerConnection`. The `ServerConnection` handles the protocol and eventually invokes a specific `Routing`. 

---

A `ServerConnection` only supports specific `Routing` types, though this is not expressed in the contract.
E.g.
- [Http1Connection](https://github.com/helidon-io/helidon/blob/4.0.0/webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1Connection.java#L114) supports `Http1Routing`
- [Http2Connection](https://github.com/helidon-io/helidon/blob/4.0.0/webserver/http2/src/main/java/io/helidon/webserver/http2/Http2Connection.java#L139C45-L139C56) supports `Http2Routing`

You can also implement a [ServerConnectionSelectorProvider](https://github.com/helidon-io/helidon/blob/4.0.0/webserver/webserver/src/main/java/io/helidon/webserver/spi/ServerConnectionSelectorProvider.java) to make the selector discoverable.

See the implementations of selectors for HTTP1 and HTTP2:
- [Http1ConnectionSelector](https://github.com/helidon-io/helidon/blob/4.0.0/webserver/webserver/src/main/java/io/helidon/webserver/http1/Http1ConnectionSelector.java)
- [Http2ConnectionSelector](https://github.com/helidon-io/helidon/blob/4.0.0/webserver/http2/src/main/java/io/helidon/webserver/http2/Http2ConnectionSelector.java)

The key methods to implement are:
-  [`selector#connection`](https://github.com/helidon-io/helidon/blob/4.0.0/webserver/webserver/src/main/java/io/helidon/webserver/spi/ServerConnectionSelector.java#L59):
- [`connection#handle`](https://github.com/helidon-io/helidon/blob/4.0.0/webserver/webserver/src/main/java/io/helidon/webserver/spi/ServerConnection.java#L36)

```java
interface ServerConnectionSelector {
    //...
    ServerConnection connection(ConnectionContext ctx);
}

interface ServerConnection {
    //...
    void handle(Semaphore requestSemaphore) throws InterruptedException;
}
```

`ConnectionContext` gives you handles on [DataReader](https://github.com/helidon-io/helidon/blob/4.0.0/common/buffers/src/main/java/io/helidon/common/buffers/DataReader.java) and [DataWriter](https://github.com/helidon-io/helidon/blob/4.0.0/common/buffers/src/main/java/io/helidon/common/buffers/DataWriter.java).

---

### Example

Here is a dummy example for inspiration.

We could polish this use-case (custom TCP protocol) by providing base classes for InputStream, OutputStream and ServerConnection.

```java
public class Main {

    public static void main(String[] args) {
        // Implement a ConnectionSelector to detect your protocol and provide a ServerConnection
        // Define a Routing type as your user interface
        // Invoke your routing from the ServerConnection
        WebServer.builder()
                .addConnectionSelector(new MyServerConnectionSelector())
                .addRouting((MyRouting) (inputStream, outputStream) -> {
                    // handler...
                })
                .build()
                .start();
    }

    interface MyRouting extends io.helidon.webserver.Routing, io.helidon.common.Builder<MyRouting, MyRouting> {

        MyRouting EMPTY = (is, os) -> {
        };

        void handle(InputStream is, OutputStream os);

        @Override
        default MyRouting build() {
            return this;
        }
    }

    static final class MyServerConnectionSelector implements ServerConnectionSelector {
        @Override
        public int bytesToIdentifyConnection() {
            return 0;
        }

        @Override
        public Support supports(BufferData data) {
            // sniff connection to determine if our custom protocol is supported
            return Support.SUPPORTED;
        }

        @Override
        public Set<String> supportedApplicationProtocols() {
            return Set.of("custom-tcp");
        }

        @Override
        public ServerConnection connection(ConnectionContext ctx) {
            return new MyServerConnection(ctx);
        }
    }

    static final class MyServerConnection implements ServerConnection {

        final DataReader reader;
        final DataWriter writer;
        final MyRouting routing;
        ZonedDateTime lastRequestTimestamp;
        volatile boolean canRun = true;
       volatile Thread myThread;

        MyServerConnection(ConnectionContext ctx) {
            reader = ctx.dataReader();
            writer = ctx.dataWriter();
            routing = ctx.router().routing(MyRouting.class, MyRouting.EMPTY);
            lastRequestTimestamp = DateTime.timestamp();
        }

        @Override
        public void handle(Semaphore requestSemaphore) {
            myThread = Thread.currentThread();
            while (canRun) {
                lastRequestTimestamp = DateTime.timestamp();
                routing.handle(new MyInputStream(reader), new MyOutputStream(writer));
            }
        }

        @Override
        public Duration idleTime() {
            return Duration.between(lastRequestTimestamp, DateTime.timestamp());
        }

        @Override
        public void close(boolean interrupt) {
            canRun = false;
            if (interrupt) {
                // interrupt regardless of current state
                if (myThread != null) {
                    myThread.interrupt();
                }
            }
        }
    }

    private static final class MyInputStream extends InputStream {

       final DataReader reader;
       BufferData currentBuffer;
       boolean finished;

        private MyInputStream(DataReader reader) {
            this.reader = reader;
        }

        @Override
        public int read() {
            if (finished) {
                return -1;
            }
            ensureBuffer(512);
            if (finished || currentBuffer == null) {
                return -1;
            }
            return currentBuffer.read();
        }

        @Override
        public int read(byte[] b, int off, int len) {
            if (finished) {
                return -1;
            }
            ensureBuffer(len);
            if (finished || currentBuffer == null) {
                return -1;
            }
            return currentBuffer.read(b, off, len);
        }

        private void ensureBuffer(int estimate) {
            if (currentBuffer != null && currentBuffer.consumed()) {
                currentBuffer = null;
            }
            if (currentBuffer == null) {
                currentBuffer = reader.readBuffer(estimate);
                if (currentBuffer == null || currentBuffer == BufferData.empty()) {
                    finished = true;
                }
            }
        }
    }

    private static final class MyOutputStream extends OutputStream {
        private final DataWriter writer;
        private boolean closed;

        private MyOutputStream(DataWriter writer) {
            this.writer = writer;
        }

        @Override
        public void write(int b) throws IOException {
            write(BufferData.create(1).write(b));
        }

        @Override
        public void write(byte[] b) throws IOException {
            write(BufferData.create(b));
        }

        @Override
        public void write(byte[] b, int off, int len) throws IOException {
            write(BufferData.create(b, off, len));
        }

        @Override
        public void close() {
            closed = true;
        }

        private void write(BufferData buffer) throws IOException {
            if (closed) {
                throw new IOException("Stream already closed");
            }
            writer.write(buffer);
        }
    }
}
```

**Comment by m0mus** [comment]
Closing as the answer was provided.

**Comment by anirbanmu** [comment]
Thank you @romain-grecourt for the very detailed answer to my question here, I hope to give it a shot soon!

PS - I apologize for the late response to your very timely answer.
