### ISSUE TITLE
4.x: Building the Native Docker image fails

### ISSUE THREAD

**Issue by luzhengyang** [helidon-io/helidon#7912]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.0.0
* Helidon MP
* JDK version: 21
* OS: macOS 13
* Docker version (if applicable):  24.0.6

----------

## Problem Description
[//]: # "`docker build -t helidon-quickstart-mp-native -f Dockerfile.native .` fails"
[//]: # "State if the problem is easily reproducible. It fails every time I run the command above"
[//]: # "Include stack traces or command outputs"
```
19.67 [ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.27:compile (build-native-image) on project helidon-quickstart-mp: Execution of /opt/graalvm-community-java21/bin/native-image @target/tmp/native-image-1030896273986161271.args io.helidon.Main returned non-zero result -> [Help 1]
19.67 [ERROR]
19.67 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
19.67 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
19.67 [ERROR]
19.67 [ERROR] For more information about the errors and possible solutions, please read the following articles:
19.67 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
------
Dockerfile.native:21
--------------------
  19 |     # the pom
  20 |     ADD pom.xml .
  21 | >>> RUN mvn package -Pnative-image -Dnative.image.skip -Dmaven.test.skip -Declipselink.weave.skip
  22 |
  23 |     # Do the Maven build!
--------------------
ERROR: failed to solve: process "/bin/sh -c mvn package -Pnative-image -Dnative.image.skip -Dmaven.test.skip -Declipselink.weave.skip" did not complete successfully: exit code: 1
```

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"
1. Generate the project using the Helidon MP Quickstart Maven archetype 
```
mvn -U archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-mp \
    -DarchetypeVersion=4.0.0 \
    -DgroupId=io.helidon.examples \
    -DartifactId=helidon-quickstart-mp \
    -Dpackage=io.helidon.examples.quickstart.mp
```
2. 
```
cd helidon-quickstart-mp
mvn package
```
3. ```docker build -t helidon-quickstart-mp-native -f Dockerfile.native .```

**Comment by barchetta** [comment]
See also #7180

**Comment by luzhengyang** [comment]
Hi @barchetta,

I'm not sure if #7180 addressed the `Dockerfile.native` in the `helidon-quickstart-mp`.

I can still that it's using the `graalvm-community:21.0.0-ol9`.

https://github.com/helidon-io/helidon/blob/77936c630f36d969fbdb6a06da11a165fbbf70fa/examples/quickstarts/helidon-quickstart-mp/Dockerfile.native#L18
