### ISSUE TITLE
Add text block support to `@AddConfig`

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#7920]
## Environment Details
* Helidon Version: 3.x 4.x
* Helidon MP
----------

## Problem Description

Add support for something similar to `@AddConfig` that uses text block.

E.g. using `@AddConfig`
```java
@HelidonTest
@AddConfig(key = "javax.sql.DataSource.example.dataSourceClassName", value = "org.h2.jdbcx.JdbcDataSource")
@AddConfig(key = "javax.sql.DataSource.example.dataSource.url", value = "jdbc:h2:mem:sample")
@AddConfig(key = "javax.sql.DataSource.example.dataSource.user", value = "sa")
@AddConfig(key = "javax.sql.DataSource.example.dataSource.password", value = "")
class MyTest {
    //...
}
```

E.g. using text blocks:
```java
@HelidonTest
@AddConfig(type = "properties", fragments = """
    javax.sql.DataSource.example.dataSourceClassName = org.h2.jdbcx.JdbcDataSource
    javax.sql.DataSource.example.dataSource.url = jdbc:h2:mem:sample
    javax.sql.DataSource.example.dataSource.user = sa
    javax.sql.DataSource.example.dataSource.password = 
    """)
class MyTest {
    //...
}
```

The key of this feature request is to support text blocks to express test configuration in a test classes. We may decide to update `@AddConfig` or create a new annotation.

**Comment by dansiviter** [comment]
YAML support would be great too:

```java
@AddConfig(type = "yaml", fragments = """
    javax.sql.DataSource.example:
      dataSourceClassName: org.h2.jdbcx.JdbcDataSource
      dataSource:
        url: jdbc:h2:mem:sample
        user: sa
        password: ""
    """
```

**Comment by jbescos** [comment]
Is this worth to do it?, there is already:

`@Configuration(configSources = "yourProperties.properties")`

**Comment by dansiviter** [comment]
@jbescos As this is for tests adding indirection to a property file just makes maintenance and comprehension difficult.

**Comment by danielkec** [comment]
And it will be cool!

**Comment by jbescos** [comment]
My idea is to create a new annotation, because I think adding this into an existing one could be confusing.
`@ConfigBlob` or `@ConfigurationBlob`
```
String: type // Properties, YAML, etc
String: content // The text
```

**Comment by jbescos** [comment]
Already in place
