### ISSUE TITLE
Upgrade to mysql-connector-j 8.2.0 or newer

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#7926]
Upgrade to mysql-connector-j 8.2.0 or newer. Need to do this in:

- [x] 2.x
- [x] 3.x
- [x] 4.x #7988

**Comment by Tomas-Kraus** [comment]
8.2.0 is latest in central

**Comment by Tomas-Kraus** [comment]
PR #7988 for 4.x is ready. Back-ports will follow when this one is approved ad merged.
