### ISSUE TITLE
Supply target request to ClientEndpointConfig.Configurator.beforeRequest() extension point 

### ISSUE THREAD

**Issue by dmutreja** [helidon-io/helidon#7954]
Our use case requires a WebSocket client to sign HTTP request when requesting to upgrade a HTTP connection to WebSocket.  The signed request would custom Authorization header that the server would use to intercept and participate in the handshake process.   (See related issue https://github.com/helidon-io/helidon/issues/7953). 

jakarta.websocket.ClientEndpointConfig.Configurator.beforeRequest() is the recommended (from Helidon team) extension point to achieve that.  jakarta.websocket.ClientEndpointConfig.Configurator.beforeRequest() is defined as 

```

This method is called by the implementation after it has formulated the handshake request that will be used to initiate the connection to the server, but before it has sent any part of the request. This allows the developer to inspect and modify the handshake request headers prior to the start of the handshake interaction.
Params:
headers – the mutable map of handshake request headers the implementation is about to send to start the handshake interaction.
 
public void beforeRequest(Map<String, List<String>> headers) {

 }
```

That is, the extension point only receives the request headers but not the target URL.  Most (all?) request signing implementations would need access to the full request  for generating a signature (that can be added as a custom header).  

 

## Environment Details
* Helidon Version: 3.2.2
* Helidon SE 
* JDK version:  "17.0.7" 2023-04-18 LTS
* OS:
* Docker version (if applicable):

----------

**Comment by jansupol** [comment]
I do not see many possibilities we can support this. The `jakarta.websocket.ClientEndpointConfig.Configurator` is the WebSocket API class and any modifications can be done in Jakarta EE 11, if approved (!), but it would not help with tyrus implementation prior the Jakarta EE 11. 

I would recommend having a separate Configurator instance for each request destination (URI), the instance then would know the URL then. 

On Tyrus level, there is no clean solution to supply the URI into the user provided `ClientEndpointConfig.Configurator` implementation.

**Comment by jansupol** [comment]
The cleanest solution in Tyrus would be to provide a subinterface of `ClientEndpointConfig.Configurator` in Tyrus, that would have a set-up method 
```
/**
 * This method is invoked once before beforeRequest(Map<String, List<String>> headers)
 */
upgradeRequest(UpgradeRequest upgradeRequest);
```
The Tyrus immutable [UpgradeRequest](https://javadoc.io/doc/org.glassfish.tyrus/tyrus-spi/latest/org/glassfish/tyrus/spi/UpgradeRequest.html) contains the URI as well as the `isSecure` method (ws vs. wss protocol distinction)

**Comment by spericas** [comment]
Tyrus was upgraded to 2.1.5. See #8277.
