### ISSUE TITLE
OciExtension (helidon-integrations-oci-sdk-cdi) not detecting injection points like Provider<?> and Instance<?>

### ISSUE THREAD

**Issue by cyrilgeorge-oracle** [helidon-io/helidon#7985]
## Environment Details
- Helidon Version: 3.2.2
- Helidon MP
- JDK version: 17
----------

## Problem Description
`OciExtension` is skipping injection points like `Provider<ObjectStorage>` and `Instance<ObjectStorage>`

## Steps to reproduce
1. add below dependencies to a helidon MP project
```
         <dependency>
            <groupId>io.helidon.integrations.oci.sdk</groupId>
            <artifactId>helidon-integrations-oci-sdk-cdi</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.oci.sdk</groupId>
            <artifactId>oci-java-sdk-objectstorage</artifactId>
        </dependency>
```
Then run below HelidonTest
```
    @Inject
    Instance<ObjectStorage> storage;

    @Test
    void testObjectCreation() {

        var resp = storage.get()
                .getBucket(GetBucketRequest.builder()
                        .bucketName("my_bucket")
                        .namespaceName("my_namespace")
                        .build());
        System.out.println(resp.getBucket().toString());
    }
```
Test will fail with exception `org.jboss.weld.exceptions.UnsatisfiedResolutionException: WELD-001334: Unsatisfied dependencies for type ObjectStorage with qualifiers @Default`

If I replace the injection without the `jakarta.enterprise.inject.Instance` test case will execute with no exception.
Behaviour is same for `jakarta.inject.Provider`

**Comment by ljnelson** [comment]
A workaround should be to add an injection point anywhere else that does not use `Provider` or `Instance`. For example, a "dummy" observer method (that is deliberately never called) in an enabled bean somewhere:
```
private static void neverInvoked(@Observes ObjectStorage ignored) {}
```
The extension should scan for all injection points (including the "dummy" one I've exemplified above) and that scan will identify the need to "make" an `ObjectStorage`, and your `Provider<ObjectStorage>` injection points should also then work.

The proper fix which I'll get to next week is to augment the extension to scan for `Provider` points as well (that will also cover `Instance` points).
