### ISSUE TITLE
4.x: Output with setting contentLength is corrupted

### ISSUE THREAD

**Issue by wojtask9** [helidon-io/helidon#8003]
## Environment Details
* Helidon Version: 4.0
* Helidon SE
* JDK version: 21
* OS: linux
* Docker version (if applicable):

----------

some_file.json
```
{
  "key": "test",
  "name": "zzzzzzz",
  "description": "some description",
  "createDate": "2022-11-25",
  "modifyDate": "2023-03-22",
  "actions": {
    "modify": true,
    "delete": true
  }
}
```

ContentLengthTest.java

```
@ServerTest
public class ContentLengthTest {

    private final static String REQUEST_URL = "/test_content_length";
    private final static Path TEST_RESOURCE = Paths.get("src/test/resources/some_file.json");
    private final WebClient client;
    ContentTest(WebClient client) {
        this.client = client;
    }

    @SetUpServer
    public static void setup(WebServerConfig.Builder serverBuilder) {
        serverBuilder.routing(routing -> routing
                .get(REQUEST_URL, (req, res) -> {
                    long length = 0;
                    OutputStream out = res.outputStream();
                    long size = Files.size(TEST_RESOURCE);
                    try (InputStream in = Files.newInputStream(TEST_RESOURCE)) {
                        length += in.transferTo(out);
                        res.contentLength(length); // COMMENT THIS
                    }

                    if (length != size) {
                        throw new RuntimeException("size differs " + size + " " + length);
                    }
                })
        );
    }

    @Test
    void testClient() throws IOException {
        long size = Files.size(TEST_RESOURCE);
        try (HttpClientResponse response = client.get(REQUEST_URL).request()) {
            String data = response.as(String.class);
            assertThat(data).isEqualTo(Files.readString(TEST_RESOURCE));

        }
    }
}

```

This test fails with output

```
org.opentest4j.AssertionFailedError: 
expected: 
  "{
    "key": "test",
    "name": "zzzzzzz",
    "description": "some description",
    "createDate": "2022-11-25",
    "modifyDate": "2023-03-22",
    "actions": {
      "modify": true,
      "delete": true
    }
  }
  "
 but was: 
  "c5
  {
    "key": "test",
    "name": "zzzzzzz",
    "description": "some description",
    "createDate": "2022-11-25",
    "modifyDate": "2023-03-22",
    "actions": {
      "modify": true,
      "delete": true
    "
```

When we comment line `res.contentLength(length); // COMMENT THIS` then test passes and everything is OK.

Note that with larger files sometimes with `res.contentLenght(lenght)` test passes

**Comment by barchetta** [comment]
I've reproduced this. The bug looks to be that WebServer is doing chunked encoding by default and then does not handle the setting of content length "late".  So you end up with a chunk encoded response that has Content-Length set (c5 is the hex value of the chunk -- evidence of chunked encoding).

 If you do `res.contentLength(size);` before `res.outputStream()` it works correctly.  

I think there are a couple issues  here. I'll have a follow-up comment in a bit.

**Comment by tomas-langer** [comment]
So there are a few problems with your code, that in combination cause the problem. I will check if we can work around the invalid response, but please fix your code.

1. You should add the output stream to the try with resources, as we expect the stream to be closed. If you do it, the code will work
2. You cannot configure a header after sending the bytes using an output stream, unless some internal optimizations kick in (e.g. you should never do that). The reason is that headers must be sent as the first thing in an HTTP response, and entity is sent after it. Once you write the first byte of an entity, you cannot update the headers

So in this case, if you want to use content length, you should first determine the content lenght, set the header, and then send the entity.
If you cannot determine the content lenght in advance, just never set it (server then uses `chunked` content encoding, that works with unknown lenghts).


This would work fine:
```
.get(REQUEST_URL, (req, res) -> {                   
                    try (OutputStream out = res.outputStream(); InputStream in = Files.newInputStream(TEST_RESOURCE)) {
                        length += in.transferTo(out);
                    }
                    long size = Files.size(TEST_RESOURCE);
                    if (length != size) {
                        // this will never reach client, as the response has already been sent
                        throw new RuntimeException("size differs " + size + " " + length);
                    }
                })
```

as would this:
```
.get(REQUEST_URL, (req, res) -> {                   
                    long size = Files.size(TEST_RESOURCE);
                    res.contentLength(size); // must happen before we get the output stream
                    try (OutputStream out = res.outputStream(); InputStream in = Files.newInputStream(TEST_RESOURCE)) {
                        length += in.transferTo(out);
                    }

                    if (length != size) {
                        // this will never reach client, as the response has already been sent
                        throw new RuntimeException("size differs " + size + " " + length);
                    }
                })
```

**Comment by tomas-langer** [comment]
I am updating the code to:
- not allow setting content length on an entity where stream was already requested (throws an exception, this is an illegal action as described above)
- removing content-lenght header if you manage to set it some obscure way (there are was to do that) and logging a warning, so the response is not broken
After these changes, you either get an exception in the service code (in the original example on the line that tries to set content length), or you get a warning. The entity returned (for the cases without exception) will be chunked and there will be no content length
