### ISSUE TITLE
Get call in helidon 2.5.5 hangs when response is greater than 5 mb.

### ISSUE THREAD

**Issue by SkyGlancer** [helidon-io/helidon#8011]
[//]: # "Get call in helidon 2.5.5 hangs when response is greater than 5 mb."
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version:2.5.5
* Helidon SE or Helidon MP: MP
* JDK version:17
* OS:linux
* Docker version (if applicable):

----------

## Problem Description
[//]: # "When response string is greater than 5mb and we use Server.builder, the curl call hangs"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce
[//]: # "git clone git@github.com:oracle/helidon.git
cd helidon
git checkout tags/2.5.5
cd examples/microprofile/hello-world-explicit
change src/main/java/io/helidon/microprofile/example/helloworld/explicit/HelloWorldResource.java 
diff --git a/examples/microprofile/hello-world-explicit/src/main/java/io/helidon/microprofile/example
index 7415426..8430bec 100644
--- a/examples/microprofile/hello-world-explicit/src/main/java/io/helidon/microprofile/example/hellow
+++ b/examples/microprofile/hello-world-explicit/src/main/java/io/helidon/microprofile/example/hellow
@@ -74,7 +74,11 @@ public class HelloWorldResource {
     @GET
     @Produces(MediaType.TEXT_PLAIN)
     public String message() {
-        return "Hello World from application " + applicationName;
+      StringBuilder str = new StringBuilder();
+          for(int i=0; i<6000000; i++) {
+              str.append("a");
+          }
+      return str.toString();
     }
     curl localhost:5000//helloworld hangs
     
     Note: this is working in 2.6.3. we want to check if there are any workarounds for 2.5.5 and why it is happening.
"

[//]: # "Provide sample code/application if relevant"

**Comment by barchetta** [comment]
Please see #5766. It includes a work-around.
