### ISSUE TITLE
Wrong `metrics` endpoint when generation Helidon SE project with starter

### ISSUE THREAD

**Issue by dalexandrov** [helidon-io/helidon#8015]
## Environment Details
* Helidon Version: 4.0.0
* Helidon SE 
* JDK version: 21
* OS: OSX

----------

## Problem Description

When generating Helidon SE project with a starter: https://helidon.io/starter/4.0.0?step=9&app-type=custom&extra=cors&metrics=true 

Readme generates:

```
# Prometheus Format
curl -s -X GET http://localhost:8080/metrics
# TYPE base:gc_g1_young_generation_count gauge
. . .

# JSON Format
curl -H 'Accept: application/json' -X GET http://localhost:8080/metrics
{"base":...
. . .
```

Should be `http://localhost:8080/observe/metrics

**Comment by barchetta** [comment]
I've reproduced with the latest in `main` using the SE quickstart.
