### ISSUE TITLE
Helidon ErrorHandlers class swallows exception object if response can't be reset

### ISSUE THREAD

**Issue by ritzow** [helidon-io/helidon#8021]
Helidon 4.0.0[ io.helidon.webserver.http.ErrorHandlers class line 212](https://github.com/helidon-io/helidon/blob/4.0.0/webserver/webserver/src/main/java/io/helidon/webserver/http/ErrorHandlers.java#L212).

A message is logged indicating the response could not be reset, but the error which caused it is ignored. The log message shpuld probably log the exception object to be handled by the underlying logging provider.

**Comment by jbescos** [comment]
Merged
