### ISSUE TITLE
Bug in JDBC URL for H2 when generating from starter or Helidon CLI

### ISSUE THREAD

**Issue by hyder** [helidon-io/helidon#8048]
# "A slash is missing in the JDBC url when using the H2 database"

## Environment Details
* Helidon Version: 4.0.0
* Helidon SE or Helidon MP: SE
* JDK version: Java(TM) SE Runtime Environment Oracle GraalVM 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)
* OS: WSL on Windows
* Docker version (if applicable): NA

----------

## Problem Description
The currently generated url for H2 is url: "jdbc:h2:tcp://localhost:9092/~test". 

This is incorrect and results in the application unable to connect to the H2 database. 
The correct URL is "jdbc:h2:tcp://localhost:9092/~/test"

## Steps to reproduce
- Generate a project using either the CLI or the starter and select H2 as database.
- Start the application. This will result in failed connections.
- Add the missing slash before the database name. The application will now start properly

**Comment by tvallin** [comment]
This issue is fixed by #7877 and will be part of 4.0.1 release.
