### ISSUE TITLE
Helidon Tracing configuration Paths

### ISSUE THREAD

**Issue by boris-senapt** [helidon-io/helidon#8148]
When adding Tracing and HealthChecks a Helidon 4.X appplication, traces are logged for health checks by default and cannot be disabled in configuration.

## Environment Details
* Helidon Version: 4.0.1
* Helidon SE
* JDK version: Zulu21.30+15-CA (build 21.0.1+12-LTS, mixed mode, sharing)
* OS: macOS Sonoma 14.2
* Docker version (if applicable): N/A

----------

In `io.helidon.webserver.observe.tracing.TracingObserverConfig.BuilderBase#pathConfigs` the paths for `/metrics/*` and `/health/*` are by default disables - but in 4.X the path for the `ObserveFeature` was updated to `/observe/*` - so health becomes `/observe/health/*`.

This means that when deploying an Helidon 4.X application to Kubernetes we get a lot of traces from the health checks running.

Further, trying to disable this path by providing a `path` config in `application.yaml` does not work. [The documentation](https://helidon.io/docs/v4/#/se/tracing#_configuration) suggests the configuration key `tracing.paths` - but this doesn't seem to do anything. [The code](https://github.com/helidon-io/helidon/blob/50dd6c042f54bb5ee271c5b2ec360ff1ff969a44/webserver/observe/tracing/src/main/java/io/helidon/webserver/observe/tracing/TracingObserverConfigBlueprint.java#L80) seems to suggest the key `path-configs` 

```yaml
tracing:
  path-configs:
    - path: /observe/*
      traced-config: DISABLE
```

But that results in

> Exception in thread "main" io.helidon.config.ConfigMappingException: Mapping of value stored under key 'tracing.path-configs.0' to type 'interface io.helidon.webserver.observe.tracing.PathTracingConfig' has failed: No mapper configured

## Steps to reproduce

Create a Helidon 4.X application with both Tracing and HealthChecks enabled. Call `/observe/health` and see that a trace is logged. Try and disable in the config according to the documentation and also by looking at `TracingObserverConfig` (generated from blueprint).

**Comment by tjquinno** [comment]
Thanks for the thorough description and reproducer.

There are a number of bugs wrapped up in this.

1. In fact, we intend to automatically disable tracing for the Helidon built-in services by default. But the code incorrectly does not include the new `/observe` prefix when it sets up the paths for the metrics, health, and openapi services. So you should not even have to turn off tracing for those services yourself.
2. IMO, the config key should be as in the doc--`paths`--not `path-configs` as you correctly surmised from the code. 
3. Regardless of the config key, the config mapping is not set up properly as the exception describes.
