### ISSUE TITLE
Helidon SE Quickstart guides health and metrics endpoints not working

### ISSUE THREAD

**Issue by apixandru** [helidon-io/helidon#8158]
The SE Quickstart guide says that /metrics and /health are default endpoints.

https://helidon.io/docs/v4/#/se/guides/quickstart

None of these actually work, the metrics endpoint appears to be registered as /observe/metrics 

```
$ curl -H 'Accept: application/json' -X GET http://localhost:8080/metrics
Endpoint not found$

```

It appears that that's registered as /observe/metrics
```
$ curl -H 'Accept: application/json' -X GET http://localhost:8080/observe/metrics
{"vendor":{"requests.count":9},"base":{"gc.total;name=G1 Young Generation":1,"cpu.systemLoadAverage":0.806640625,"classloader.loadedClasses.count":3689.0,"thread.count":19.0,"classloader.unloadedClasses.total":0,"jvm.uptime":129606.0,"gc.time;name=G1 Young Generation":0,"memory.committedHeap":528482304,"thread.max.count":20.0,"cpu.availableProcessors":16.0,"classloader.loadedClasses.total":3689,"thread.daemon.count":17.0,"memory.maxHeap":8338276352,"memory.usedHeap":3.298728E+7}}$ 
```

Likewise, the /health endpoint
```
$ curl -H 'Accept: application/json' -X GET http://localhost:8080/health
Endpoint not found
```
This one also appears to be /observe/health but it doesn't respond with anything useful
```
$curl -H 'Accept: application/json' -X GET http://localhost:8080/observe/health
$
```
I'm assuming that it should respond similarly to helidon mp
```
$ curl -H 'Accept: application/json' -X GET http://localhost:8080/health
{"status":"UP","checks":[]}$
```

The difference between the observe endpoints is that the se config defines the health check as being "health" but mp defines it as "/health"

The config in MP is built by the HealthCdiExtension.

```
        builder.details(true)
                .endpoint("/health") // absolute URI to align with MP
                .config(config);
```

Whereas the config in SE is built by HealthObserverProvider
```
        return HealthObserverConfig.builder()
                .config(config)
                .name(name)
                .build();
```
Adding .endpoint("/health") here seems to solve the registration issue but it's still not responding.
Adding .details(true) returns some details
```
$ curl -H 'Accept: application/json' -X GET http://localhost:8080/health
{"status":"UP","checks":[{"name":"diskSpace","status":"UP","data":{"total":"467.89 GB","percentFree":"88.91%","totalBytes":502392610816,"free":"416.02 GB","freeBytes":446698061824}},{"name":"heapMemory","status":"UP","data":{"total":"504.00 MB","percentFree":"99.66%","max":"7.77 GB","totalBytes":528482304,"maxBytes":8338276352,"free":"476.77 MB","freeBytes":499924904}},{"name":"deadlock","status":"UP"}]}
```

**Comment by barchetta** [comment]
Yes, this is a documentation bug.

As you discovered the health and metrics endpoints in SE are now under "observe".   Also, by default the health endpoint in SE returns a 204 with no content since this is most appropriate for its primary use case (as a k8s health check).
