### ISSUE TITLE
Adding `@Inject` to a resource method parameter causes the method to be invoked even if it does not match the request path or HTTP method

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#8177]
## Environment Details
* Helidon Version: 4.0.1
* Helidon SE or Helidon MP MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description

(Note - this same problem seems to affect 3.x)

Using `@Inject` on a resource class method causes that method to be invoked at least once on _every_ request routed to the resource class, _whether or not_ the method's `@Path` setting or  HTTP method annotation (`@GET`, `@HEAD`, etc.) matches the incoming request.

If the `@Inject`ed method declares a`@ConfigProperty` parameter then the method is invoked one extra time, but if it has no parameters at all the method is invoked _two_ extra times.

I found this when trying to `@Inject` a config property into a resource method as a parameter. I do not have results for trying to inject other sorts of things.

Workaround: Inject into the constructor of the resource class instead of the individual methods and save the values as instance fields which the methods can refer to.

## Steps to reproduce
1. `helidon init` for an MP QuickStart app. Take all the other defaults.
2. Add the code below to the `GreetResource` class.
3. Build the app normally (`mvn clean package`) then run it using `app_note="My Note" java -jar target/quickstart-mp.jar`
4. `curl http://localhost:8080/greet`.
   
   The server output shows incorrect invocations of the `@Inject`ed methods with `head()` invoked twice.
   ```
   Invoked head with no injected parameter
   Invoked other with value My Note
   Invoked note with value My Note
   Invoked head with no injected parameter
   ```
5. `curl http://localhost:8080/greet/note` which _should_ respond with the value of the `app.note` config property. Instead the response is empty. The server output this time shows the same incorrect method calls as before except this time there are _two_ invocations of `note`. The second one _does not_ see the injected config property value and so prints an empty string and puts an empty string in the response:
   
   ```
   Invoked head with no injected parameter
   Invoked other with value My Note
   Invoked note with value My Note
   Invoked head with no injected parameter
   Invoked note with value 
   ```
   
Here is the Java code to add to `GreetResource` to illustrate this problem:

```java
    @GET
    @Path("/note")
    @Produces(MediaType.TEXT_PLAIN)
    @Inject
    public String note(@ConfigProperty(name = "app.note", defaultValue = "noNote") String note) {
        System.err.println("Invoked note with value " + note);
        return note;
    }

    @GET
    @Path("/other")
    @Produces(MediaType.TEXT_PLAIN)
    @Inject
    public String other(@ConfigProperty(name = "app.note", defaultValue = "noNote") String note) {
        System.err.println("Invoked other with value " + note);
        return note;
    }

    @HEAD
    @Path("/head")
    @Inject
    public String head() {
        System.err.println("Invoked head that does not declare a parameter");
        return "Done";
    }
```

**Comment by ljnelson** [comment]
(Not up to speed on any of the root causes, context, deeper issues, etc. but wanted to add this in case it is helpful.)

In _any_ CDI application, if you put `@Inject` on a method, it becomes an [initializer method](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0#initializer_methods) with corresponding rules about its invocation by the CDI container. When you mix this with JAX-RS, it can be surprising for sure.

**Comment by tjquinno** [comment]
That could well explain what I'm seeing.

So maybe this is simply pilot error on my part in misusing/not understanding the implications of `@Inject` on methods. (I guess I'm used to seeing other annotations explicitly flagging init methods, like `@PostConstruct`). 

I'll go back to my example and make sure that doing the `@Inject` on the constructor instead (and only there) works and, if so, I'll probably close this as PEBCAK.

**Comment by tjquinno** [comment]
This was definitely due to me misusing `@Inject` on the resource methods.

The `GreetService` constructor already has `@Inject`. I added a `@ConfigProperty` parameter to the constructor, saved the value in an instance field, and then changed the resource methods to use that and all is well.

**Comment by ljnelson** [comment]
Right; I mean the flow will be:
* {waves hands vaguely} a request comes into the JAX-RS implementation
* Jersey realizes a given resource has to be instantiated and delegates to the DI system in effect for that instantiation (the DI system is CDI in this case, not, say, HK2)
* CDI takes over the instantiation and follows its rules. One of those rules is to run initializer methods immediately after invoking the constructor.
* The resource class is now instantiated and Jersey resumes control and figures out what resource method to invoke, etc. etc.

**Comment by tjquinno** [comment]
Yes, that's all consistent with what I saw. The initial invocations of the methods with `@Inject`--as part of constructing the object--_did_ see the correctly-injected config property. The later calls, responding to a request, did not. That matches up with your description, as does why it works to do the injection in the annotated constructor and store the values in instance fields.
