### ISSUE TITLE
Example READMEs still reference JDK11

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#8182]
Some of the Helidon 4 example READMEs reference JDK11. We should probably remove "With JDK11+" and in general not reference a specific JDK version.

```
$ /usr/bin/grep -ri -I --include "*.md" "JDK11"
./metrics/exemplar/README.md:With JDK11+
./metrics/kpi/README.md:With JDK11+
./jbatch/README.md:With JDK11+
./integrations/micrometer/se/README.md:With JDK11+
./integrations/micrometer/mp/README.md:With JDK11+
./webserver/multiport/README.md:With JDK11+
./cors/README.md:With JDK11+
./microprofile/messaging-sse/README.md:With JDK11+
./microprofile/multiport/README.md:With JDK11+
./microprofile/bean-validation/README.md:With JDK11+
```

**Comment by senivam** [comment]
Questions:

the full part where a JDK is mentioned typically looks like:
```
## Build and run

With JDKxxx

mvn package
java -jar target/helidon-<...>.jar
```

Should the text ``with JDKxxx`` just be removed without any replacement?
Should all references to any JDK be removed? 
Shall it be done only in the new (meanwhile private) repository for examples?
Shall it be done for the ``dev-3.x`` branch either (in the new private repository)?

**Comment by barchetta** [comment]
My thoughts

1. Remove without any replacement. We don't want to state general pre-reqs over-and-over in the examples
2. If you want to update other example READMEs to remove the (correct) JDK pre-req that is fine.
3. First priority is to fix it in 4.x (`main`)
4. To fix in 3.x, yes you can do it as part of the example repository work
