### ISSUE TITLE
Mobile navigation links to old documentation

### ISSUE THREAD

**Issue by pavelklecansky** [helidon-io/helidon#8185]
## Problem Description
On mobile, the navigation links to old documentation (v3) but main page links to new (v4)
## Mobile navigation
![Screenshot_20231231_165855_Chrome](https://github.com/helidon-io/helidon/assets/28779692/6a7cec41-1f84-4006-9bc5-118d7098681f)
## Mobile main page
![Screenshot_20231231_170158_Chrome](https://github.com/helidon-io/helidon/assets/28779692/6ffefe31-e0fe-4856-95bf-3e896a15a638)

**Comment by romain-grecourt** [comment]
This is fixed now. Thank you for reporting this issue.
