### ISSUE TITLE
Registering a custom MediaTypeDetector ?

### ISSUE THREAD

**Issue by chrysophylax** [helidon-io/helidon#8204]
Registering a custom MediaTypeDetector

## Environment Details
* Helidon Version: 4.0.2
* Helidon SE 
* JDK version: 21.0.1-graalce
* OS: linux 6.x
* Docker version (if applicable): n/a

----------

## Problem Description
I'm not sure how to register a custom MediaTypeDetector. I wrote a class in my regular program package implementing `io.helidon.common.media.type.spi.MediaTypeDetector` and overriding detectExtensionType and detectType(Path). 

When I try to discover a mediatype using `io.helidon.common.media.type.MediaTypes.detectType(myPathObject)` in a HttpService handler nothing happens. None of the code I have written seems to be executed. I assume I have to register this in some service loader but I am not sure how to do it. 

The documentation for [MediaTypes](https://helidon.io/docs/v4/apidocs/io.helidon.common.media.type/io/helidon/common/media/type/MediaTypes.html) states that MediaTypeDetector services are queried in priority order which well, suggests I have to register mine somewhere with a priority. Where do I do this? 

## Steps to reproduce
1. Write a custom class implementing MediaTypeDetector.  Have it print hello world on every overriden method and return a MediaType of, say, APPLICATION_OCTET_STREAM. 
2. Attempt to detect mediatype using MediaTypes.detectType.
3.  ??? no dice !

**Comment by chrysophylax** [comment]
Looking at https://github.com/helidon-io/helidon/blob/main/common/media-type/src/main/java/io/helidon/common/media/type/Detectors.java it seems this class is directly used by MediaTypes and is not amenable to expansion. There is no way to add something to the `DETECTORS` list at compile-time.

**Comment by ljnelson** [comment]
Indeed you cannot add to the `DETECTORS` list at _compile_ time, but it is built at runtime, and the services that comprise it are loaded here:

https://github.com/helidon-io/helidon/blob/4.0.2/common/media-type/src/main/java/io/helidon/common/media/type/Detectors.java#L35-L39

It sounds like maybe you are not familiar with [Java's `ServiceLoader`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/ServiceLoader.html) (apologies if you are)? The `HelidonServiceLoader` (https://github.com/helidon-io/helidon/blob/4.0.2/common/common/src/main/java/io/helidon/common/HelidonServiceLoader.java#L31-L77) sort of does the same thing and here is in charge of finding detectors.

**Comment by chrysophylax** [comment]
Hi, thanks for pointing me in a righter direction.  You're right that I'm not really familiar with Java's ServiceLoader.

What I'm not really grokking is how I can convince  the HelidonServiceLoader to wire my CustomDetector class ( _implements MediaTypeDetector, Weighted_) so that `MediaTypes.detectType` will also consider my implementation.

Do I have to chuck things in a module or JAR for things to be loaded? I currently only have it as a class in the same package.

**Comment by chrysophylax** [comment]
Ahh - I went and read a bit more. I created a META-INF/services entry and it now correctly loads the service. 

Thanks for the pointers and help!
