### ISSUE TITLE
Build Docs error : helidon-common: Compilation failure

### ISSUE THREAD

**Issue by ytakahas-oracle** [helidon-io/helidon#8226]
Hi,

I'm trying to build docs for translation, but I got the following error.  
Would you suggest how to solve the matter?

Thanks.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.583 s
[INFO] Finished at: 2024-01-10T16:04:26+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project helidon-common: Compilation failure
[ERROR] error: invalid flag: -proc:full
```
...

I'm using the following maven and java versions:
```
$ mvn -version
Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)
Maven home: /opt/apache-maven
Java version: 17.0.9, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.15.133.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"
```

**Comment by romain-grecourt** [comment]
The main branch is used for the 4.x codeline currently which requires JDK21.
Also the steps in the README apply to the docs directory.

I.e.
```bash
# do a full build first
mvn install -DskipTests

# then build the docs
cd docs
mvn package -Pjavadocs
```

**Comment by ytakahas-oracle** [comment]
Thanks, some things have been built with JDK21.
But nothing is displayed on the browser, because the paths are described in absolute paths, like:
```
  <script src="/components/mainView.js"></script>
  <script src="/components/docView.js"></script>
  <script src="/components/defaultView.js"></script>
```
I need to publish translated version for v4 in relative path, like v3:
`https://oracle-japan-oss-docs.github.io/helidon/docs/v3/#/about/introduction
`
If you could instruct how to solve it, it would be great.

Also,  javadoc was not build with the following messages, but it is ok, since they could be retrieved by wget:
`[WARNING] The requested profile "javadocs" could not be activated because it does not exist.`

**Comment by ytakahas-oracle** [comment]
Thanks, Thibault san.

**Comment by romain-grecourt** [comment]
V4 docs as they are require a server, they cannot be served with a simple static server like GitHub pages as-is.
You will need to edit the generated files to support history mode and edit the paths to not be absolute.

I.e. the inverse of these changes: https://github.com/helidon-io/helidon-build-tools/pull/1001/files#diff-e82ec35b1c225780e0235fd50a8a36bc236086b79a9fdc49c88b617987fd4be0R82

**Comment by ytakahas-oracle** [comment]
Thanks,  I'll edit them as suggested.
