### ISSUE TITLE
question about ServerResponse and headers

### ISSUE THREAD

**Issue by imrafaelmerino** [helidon-io/helidon#8234]
Hello,

I have a ServerResponse and a header containing a list of values represented with a List. Is there a straightforward way to set these headers in the response? The current approach seems a bit convoluted:

```java
ServerResponse sr = ...;
Map<String, List<String>> headers = ...;
for (var header : headers.entrySet()) {
    sr.header(header.getKey(), header.getValue().toArray(new String[0]));
}
```

The limitation lies in the fact that there is only a method `header(String key, String... values)`, requiring the conversion of a list into an array, which might not be the most efficient solution.

Additionally, I've had difficulty finding detailed documentation about headers. With various classes and caches involved, the inner workings are not entirely clear to me.

Thank you in advance!

**Comment by romain-grecourt** [comment]
I'm guessing you are using 4.x.

You need to use `HeaderValues` to create instances of `Header` and set them on the response using `Response.header(Header)`.

E.g.

```java
Map<String, List<String>> myHeaders = Map.of("foo", List.of("bar1", "bar2"));
myHeaders.forEach((k, v) -> response.header(HeaderValues.create(k, v)));
```
