### ISSUE TITLE
4.x: About `next()` that existed in ServerRequest until Series 3

### ISSUE THREAD

**Issue by ShunichirouKamino** [helidon-io/helidon#8283]
## Environment Details
* Helidon Version: 4.x
* Helidon SE
* JDK version: 21
* OS: any
* Docker version (if applicable): any

----------
With 4.x, Vertual Threads were adopted and asynchronous enhancements were made.
I have been using `ServerRequest.next()` to intentionally hook the handler myself, but what would be the preferred implementation for such cases in the future? (For example, use `ServerResponse.next()`?)
The following is the code for 3.x.

```java
public final class AnyHookResource extends Service {

    // omission

    @Override
    public final void update(final Routing.Rules rules) {
        rules.any((req, res) -> {
           // any process

            req.next();
        });
    }

    // omission

}

**Comment by romain-grecourt** [comment]
Yes, use `ServerResponse.next()` in 4.x to replace usages of `ServerRequest.next()` in 3.x.
`ServerRequest.next(Throwable)` can be replaced with just `throw`.

**Comment by ShunichirouKamino** [comment]
@romain-grecourt 
Thanks for the quick reply. Close and there is no problem.
I am impressed with the rapid support for Virtual Thread!
