### ISSUE TITLE
[4.x] Improve examples test coverage

### ISSUE THREAD

**Issue by tvallin** [helidon-io/helidon#8337]
## Environment Details
* Helidon Version: 4.0.5
* Helidon SE or Helidon MP
* JDK version: 21
* OS:
* Docker version (if applicable):

----------

## Problem Description

A few examples does not have test or limited test coverage: 
  - DbClient JDBC does not have tests
  - DbClient Pokemons test only its service with in-memory h2
  - Tracing example is not tested

We need to improve test coverage to make sure example are working.

**Comment by barchetta** [comment]
See also #1705
