### ISSUE TITLE
ResponseProcessing Failed to convert a response into an exception

### ISSUE THREAD

**Issue by hyder** [helidon-io/helidon#8348]
## Environment Details
* Helidon Version: 4.0.5
* Helidon MP
* JDK version: Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.1+12.1
* OS: Ubuntu 
* Docker version (if applicable):

----------

## Problem Description
When returning a Response with 204, but some content is returned anyway, tests fail with the error:  ResponseProcessing Failed to convert a response into an exception

[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce
https://github.com/helidon-io/helidon-cloudbank/pull/1/files#diff-e30cbc5f82170a6be47936061f1eb6c9e8218618ba2fbdea8a358fea776ad68aR71 

[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

**Comment by tomas-langer** [comment]
When no content status is used and entity sent, the connection gets broken and the next request on that connection fails with invalid status (`-1`).
This may be reproducible in SE as well.
