### ISSUE TITLE
init_script.sql causes error with Oracle Database

### ISSUE THREAD

**Issue by hyder** [helidon-io/helidon#8373]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.0.5
* Helidon SE or Helidon MP: MP
* JDK version: 21
* OS: Ubuntu
* Docker version (if applicable):

----------

## Problem Description
init_script.sql  are generated with a `;` at the end e.g.

```
INSERT INTO CUSTOMERS (id, name, email) VALUES (1, 'user1', 'user1@cloudbank.helidon');
```
 This causes an error with the Oracle Database: 

```
Caused by: Error : 933, Position : 90, Sql = INSERT INTO CUSTOMERS (id, name, email) VALUES (1, 'user1', 'user1@my.email');, OriginalSql = INSERT INTO CUSTOMERS (id, name, email) VALUES (1, 'user1', 'user1@my.email');, Error Msg = ORA-00933: SQL command not properly ended
```

[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

**Comment by tvallin** [comment]
Hi,
I tried to reproduce your issue but I couldn't. Can you share a reproducer ?

**Comment by hyder** [comment]
Sorry I've updated the issue. There should be a semi-colon at the end. It's just what was generated when creating a new project e.g. the following is the generated SQL for pokemon:

```
INSERT INTO POKEMONTYPE VALUES (1, 'Normal');
INSERT INTO POKEMONTYPE VALUES (2, 'Fighting');
INSERT INTO POKEMONTYPE VALUES (3, 'Flying');
INSERT INTO POKEMONTYPE VALUES (4, 'Poison');
INSERT INTO POKEMONTYPE VALUES (5, 'Ground');
INSERT INTO POKEMONTYPE VALUES (6, 'Rock');
INSERT INTO POKEMONTYPE VALUES (7, 'Bug');
INSERT INTO POKEMONTYPE VALUES (8, 'Ghost');
INSERT INTO POKEMONTYPE VALUES (9, 'Steel');
INSERT INTO POKEMONTYPE VALUES (10, 'Fire');
INSERT INTO POKEMONTYPE VALUES (11, 'Water');
INSERT INTO POKEMONTYPE VALUES (12, 'Grass');
INSERT INTO POKEMONTYPE VALUES (13, 'Electric');
INSERT INTO POKEMONTYPE VALUES (14, 'Psychic');
INSERT INTO POKEMONTYPE VALUES (15, 'Ice');
INSERT INTO POKEMONTYPE VALUES (16, 'Dragon');
INSERT INTO POKEMONTYPE VALUES (17, 'Dark');
INSERT INTO POKEMONTYPE VALUES (18, 'Fairy');

INSERT INTO POKEMON VALUES (1, 'Bulbasaur', 12);
INSERT INTO POKEMON VALUES (2, 'Charmander', 10);
INSERT INTO POKEMON VALUES (3, 'Squirtle', 11);
INSERT INTO POKEMON VALUES (4, 'Caterpie', 7);
INSERT INTO POKEMON VALUES (5, 'Weedle', 7);
INSERT INTO POKEMON VALUES (6, 'Pidgey', 3);
```

The `;` causes the error.
