### ISSUE TITLE
Some mocked OCI interfaces need to be updated every time OCI makes a backwards-incompatible release

### ISSUE THREAD

**Issue by ljnelson** [helidon-io/helidon#8377]
Here is an arbitrary example:

https://github.com/helidon-io/helidon/blob/16ca27b5da8151a1e7241f76993ad75874ac71e3/integrations/oci/metrics/cdi/src/test/java/io/helidon/integrations/oci/metrics/cdi/OciMetricsCdiExtensionTest.java#L186

The `Monitoring` interface gained a few methods, which is a backwards-incompatible change. Currently, we solve this problem by manually adding "no-op" methods as appropriate.

Instead, for mock implementations of business interfaces such as these, we should use something like `java.lang.reflect.Proxy` or Mockito or something to implement only the parts we truly need to test.

**Comment by klustria** [comment]
I think I have an idea on what to do with this, hence moving to Sprint Scope.

**Comment by klustria** [comment]
Resolved via PR https://github.com/helidon-io/helidon/pull/8474.
