### ISSUE TITLE
Linear Scalabity issue with Quick start hello greet program in Helidon SE 4.0.2

### ISSUE THREAD

**Issue by MohanramGovindarasu** [helidon-io/helidon#8390]
## Environment Details
* Helidon Version: 4.0.2
* Helidon SE or Helidon MP : Helidon SE 
* JDK version: 21
* OS: Linux
* Docker version (if applicable): NA

----------

## Problem Description
We are not seeing linear scalability with the basic Hello greet program in Helidon SE 4.0.2 version 

Hardware : Linux based 16 OCPU and 240 GB RAM (Dev2OCI tenancy)
Resource usage: CPU was under 50 % and Memory was under 30 GB

## Steps to reproduce
1. Did scalability runs with concurrent threads from 1 to 100. 
2. Captured JFR with the below startup commands:
3. java -jar -Xmx30g -Xms30g -XX:StartFlightRecording:jdk.VirtualThreadStart#enabled=true,jdk.VirtualThread
End#enabled=true,jdk.VirtualThreadPinned#enabled=true helidon-quickstart-se.jar
4. TPS details are attached for reference
5. My observation was it is neither vertically scaling nor horizontally scaling even with HAProxy LB at this stage
6. Based on @ Mark Deng  request repeated the runs after restarting the machine. TPS has not changed much, still it is not linear. Attached the JFR's with *_run2 for 50 and 100 users to the same zip

[Hello greet code.zip](https://github.com/helidon-io/helidon/files/14307147/Hello.greet.code.zip)
[Hello greet TPS details.xls](https://github.com/helidon-io/helidon/files/14353694/Hello.greet.TPS.details.xls)
[JFR for 50 and 100 users.zip](https://github.com/helidon-io/helidon/files/14318566/JFR.for.50.and.100.users.zip)

**Comment by spericas** [comment]
Please include information about:

1. HW setup: client and server running on different machines?
2. Network setup: local network, localhost?
3. Load generator: including its configuration
4. JDK version

**Comment by MohanramGovindarasu** [comment]
1.HW setup: client and server running on different machines? 

Ans: Client and server running on same machine..  but it actually doesnt matter, even if it is running on different machine, observation is the same.

2.Network setup: local network, localhost?

Ans: I am using Linux VM: 
Linux based 16 OCPU and 240 GB RAM (Dev2OCI tenancy)
<img width="491" alt="image" src="https://github.com/helidon-io/helidon/assets/155984722/44a43664-4bd3-4a79-8fdb-d7e5fa5b5c37">


3.Load generator: including its configuration
Ans: Work is used as a client.

Without LB:
./wrk -d 180       -c 100       -t 100       --latency       --timeout 8s       -H 'Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'  -H 'Connection: keep-alive'   http://phoenix395763.appsdev.fusionappsdphx1.oraclevcn.com:8080/simple-greet
Running 3m test @ http://phoenix395763.appsdev.fusionappsdphx1.oraclevcn.com:8080/simple-greet


With LB: HA Proxy LB is used listening to port 80

 [mohgovin@phoenix395763 wrk_tool]$ ./wrk -d 180       -c 50       -t 50       --latency       --timeout 8s       -H 'Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'  -H 'Connection: keep-alive'   http://phoenix395763.appsdev.fusionappsdphx1.oraclevcn.com/simple-greet
 
4. JDK version: JDK 21

**Comment by romain-grecourt** [comment]
Can you please stop exposing internal host names on GitHub.

**Comment by MohanramGovindarasu** [comment]
> Can you please stop exposing internal host names on GitHub.

Done

**Comment by MohanramGovindarasu** [comment]
Do

> > Can you please stop exposing internal host names on GitHub.
> 
> Done

**Comment by MohanramGovindarasu** [comment]
Closed by mistake, reopened again. @spericas @romain-grecourt . please add the necessary tags for the same

**Comment by spericas** [comment]
@MohanramGovindarasu The attached zip file only contains binaries, no sources. I'm going to assume the code is the same as our quickstart SE example. Please advise if that is not the case.

**Comment by MohanramGovindarasu** [comment]
> @MohanramGovindarasu The attached zip file only contains binaries, no sources. I'm going to assume the code is the same as our quickstart SE example. Please advise if that is not the case.

Thats right.! I will attach the source code as well to this bug tomorrow.

**Comment by spericas** [comment]
I've analyzed the use case, and also discussed it with @nairiti-sharma, and we agreed that linear growth cannot be expected as described in this scenario:

1. Running the client and the server on the same machine _does_ matter; to expect the server not to be affected by the cores taken by the client threads is not realistic.
2. Linear scalability should happen until the number of cores is saturated, but not after that (and provided there are enough network resources, naturally).
3. Peak throughput isn't normally achieved when the number of connections equals the number of threads in `wrk`. Normally, many more connections per thread are needed, given that it is an I/O-bound test --the proportion is typically at least 4:1.

Let's continue any further discussion on the channel.

**Comment by MohanramGovindarasu** [comment]
> I've analyzed the use case, and also discussed it with @nairiti-sharma, and we agreed that linear growth cannot be expected as described in this scenario:
> 
> 1. Running the client and the server on the same machine _does_ matter; to expect the server not to be affected by the cores taken by the client threads is not realistic.
> 2. Linear scalability should happen until the number of cores is saturated, but not after that (and provided there are enough network resources, naturally).
> 3. Peak throughput isn't normally achieved when the number of connections equals the number of threads in `wrk`. Normally, many more connections per thread are needed, given that it is an I/O-bound test --the proportion is typically at least 4:1.
> 
> Let's continue any further discussion on the channel.



> I've analyzed the use case, and also discussed it with @nairiti-sharma, and we agreed that linear growth cannot be expected as described in this scenario:
> 
> 1. Running the client and the server on the same machine _does_ matter; to expect the server not to be affected by the cores taken by the client threads is not realistic.
> 2. Linear scalability should happen until the number of cores is saturated, but not after that (and provided there are enough network resources, naturally).
> 3. Peak throughput isn't normally achieved when the number of connections equals the number of threads in `wrk`. Normally, many more connections per thread are needed, given that it is an I/O-bound test --the proportion is typically at least 4:1.
> 
> Let's continue any further discussion on the channel.



> I've analyzed the use case, and also discussed it with @nairiti-sharma, and we agreed that linear growth cannot be expected as described in this scenario:
> 
> 1. Running the client and the server on the same machine _does_ matter; to expect the server not to be affected by the cores taken by the client threads is not realistic.

 [MohanramGovindarasu] : Even if we move client and server to different VM's the results are the same, linear scalability is still restricted by number of the OCPU of the VM. We have logged bug on this context - https://github.com/helidon-io/helidon/issues/8432 

> 2. Linear scalability should happen until the number of cores is saturated, but not after that (and provided there are enough network resources, naturally).

 [MohanramGovindarasu] : Why the helidon framework is restricted by the number of OCPU on the hardware ? With VT uptake in Helidon 4.0, are we saying VT is limited by the kernel threads ? Please correct me if i am wrong here . 

> 3. Peak throughput isn't normally achieved when the number of connections equals the number of threads in `wrk`. Normally, many more connections per thread are needed, given that it is an I/O-bound test --the proportion is typically at least 4:1.
> Will review this internally and get back

> Let's continue any further discussion on the channel.

**Comment by MohanramGovindarasu** [comment]
> > @MohanramGovindarasu The attached zip file only contains binaries, no sources. I'm going to assume the code is the same as our quickstart SE example. Please advise if that is not the case.
> 
> @spericas Thats right.! I will attach the source code as well to this bug tomorrow.

I have attached the source code for your reference.
