### ISSUE TITLE
Jakarta Beans Validation version: 3.0, 3.2 or 4.0?

### ISSUE THREAD

**Issue by hyder** [helidon-io/helidon#8392]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.0.5
* Helidon MP
* JDK version: 21
* OS: 
* Docker version (if applicable):

----------

## Problem Description
When creating a new project, we notice that Helidon is still using Jakarta Beans 3.0:

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="https://jakarta.ee/xml/ns/jakartaee"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee
                           https://jakarta.ee/xml/ns/jakartaee/beans_3_0.xsd"
        version="3.0"
        bean-discovery-mode="annotated">
</beans>
```
Given there are later versions of the Beans specs (3.2, 4.0), should we upgrade to later versions and should the mp archetype also update its version?

[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce
Generate a new Helidon MP project and inspect the beans.xml

**Comment by barchetta** [comment]
For reference, the last time we updated: #3697

**Comment by ljnelson** [comment]
Note that the specification in question is CDI, not Jakarta Validation.
