### ISSUE TITLE
[4.x] Optionally expose Helidon tracing spans as Java Flight Recorder events

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#8393]
## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
See also #8352 

Users have requested that Helidon expose Helidon tracing spans as Java Flight Recorder events.

**Comment by vasanth-bhat** [comment]
Emitting the telemetry Spans as events into JFR helps co-relating the execution of the code associated with JVM level events like GC,  socket reads, monitor waits and also associate them with other data from JFR such as sample method profiles, thread cpu usage etc.   This is very useful for diagnosis where the slowness maybe related to underlying JVM events, or for cases where no child spans are created.  The Span  events in JFR  helps to establish the boundary of request execution on the threads involved .

**Comment by vasanth-bhat** [comment]
Helidon Version : 4.x 
Helidon SE & Helidon MP
JDK 21+
OS  :  Linux on x64 and aarch64

**Comment by tjquinno** [comment]
Some separate discussions suggest strongly that a general-purpose, Helidon-provided approach for mapping span event so JFR events would not be workable. The details of how to do such a mapping seem too dependent on each specific use case.

I am closing this issue as a result while noting that I have updated the PR #8619 for related issue #8352 to include a test which serves as an example for one way to do such a mapping. We will probably want a true example, rather than just a test, to illustrate this.
