### ISSUE TITLE
Helidon MP metrics with annotation doesn't show up in application metrics end point "/metrics/application"

### ISSUE THREAD

**Issue by zhubinaustin** [helidon-io/helidon#8398]
[//]: # I added @Counted for a method call, but it didn't show up at "/metrics/application" as expected. The registered application metrics work fine.

# Environment Details
Helidon version: 3.2.5     -- I have another project with 2.6.5 which works fine.
Helidon MP
Java 17
mvn 3.9.2
microprofile-metrics-api: 4.0
----------

# Problem Description
For instance:
    private final MetricRegistry registry =
            RegistryFactory.getInstance().getRegistry(MetricRegistry.Type.APPLICATION);
    private final Counter counter1 = registry.counter("please.test");

    @Counted(name="annotatedTest")
    @Timed(name = "metricsTimer", unit = MetricUnits.MILLISECONDS)
    public void MetricsAnnotationTest() {
        counter1.inc();
    }

From curl /metrics/application, I got:
{
  "please.test": 1
}

Thanks!
----------

**Comment by tjquinno** [comment]
@zhubinaustin If you change your code according to my previous comment and still see problems please share here a small project which reproduces the problem.

**Comment by zhubinaustin** [comment]
Thanks for the tips. I'm working on other tasks, will try when I get a chance.

**Comment by tjquinno** [comment]
We have many tests and examples in Helidon which work when the annotated method is in a bean and is invoked via an injected reference. With that in mind and after a week of inactivity here I will close this issue. 

Please re-open it if you find a reproducer that shows the problem.
