### ISSUE TITLE
Close DBClient

### ISSUE THREAD

**Issue by boris-senapt** [helidon-io/helidon#8402]
I cannot see a way to `close()` a `DBClient`. 

I have a `JDBCClient` backed by a Hikari pool and I'm running tests. After about 15 tests I get

```
FATAL: sorry, too many clients already
```

## Environment Details
* Helidon Version: 4.0.5
* Helidon SE
* JDK version:  Zulu21.30+15-CA (build 21.0.1+12-LTS)
* OS: Sonoma 14.3.1
* Docker version (if applicable): N/A

----------

## Problem Description

Whenever a `DBClient` is created, when using JDBC with Hikari it creates a connection pool. There is no way to shut down the `DBClient` afterwards so these connections stay open. After a number of tests - 15 in my case - Postgres refuses new connections.

To workaround I can force the database to restart (I use `TestContainers`) but that does make the tests slower.

**Comment by sdyura** [comment]
HikariDataSource has a `close()` method, but HikariConnectionPool that holds the HikariDataSource does not, and never closes it
