### ISSUE TITLE
WebSocket does not close if status code is missing.

### ISSUE THREAD

**Issue by multimike** [helidon-io/helidon#8407]
## Environment Details
* Helidon Version: 4.0.5
* Helidon SE
* JDK version: Temurin 21
* OS: MacOS 13.6.2

----------

## Problem Description
It is common to close WebSockets using empty payload. I.e. without sending status and reason.
Helion wrongly expects (at least) a two byte status code in the payload.

The expected behaviour would be to assume code 1000 ("normal") if no code is present in the WS frame.

## Steps to reproduce

- Create a simple WS server:

```
public class HttpServer {

    public static void main(String[] args) {
        WsListener wsListener = new WsListener() {
            @Override
            public void onOpen(WsSession session) {
                System.out.println("WS Open");
            }

            @Override
            public void onClose(WsSession session, int status, String reason) {
                System.out.println("WS Close");
            }
        };

        WsRouting.Builder wsRouting = WsRouting.builder()
                .endpoint("/ws", wsListener);

        WebServer server = WebServer.builder()
                .port(8080)
                .addRouting(wsRouting)
                .build();

        server.start();
    }

}
```
- Use a WS client (for example: [websocketking](https://websocketking.com/)) to connect to it.
- Watch "WS Open" messages pop in, but no "WS Close".

Changing on the JS side from `webSocket.close()` to `webSocket.close(1000)` resolves the issue.

**Comment by spericas** [comment]
https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.1
