### ISSUE TITLE
Scalabity issue observed in Helidon SE 4.0.2 for Party Management product

### ISSUE THREAD

**Issue by MohanramGovindarasu** [helidon-io/helidon#8432]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details

Helidon Version: 4.0.2
Helidon SE or Helidon MP : Helidon SE
JDK version: 21
OS: Linux
Docker version (if applicable): NA

-----------------------------------------------------------------

## Problem Description

IMO we are not able to vertically scale (by increasing the number of CPU cores 8/16/24) nor horizontally scale even with HAProxy LB beyond number of OCPU in Helidon SE 4.0.2 version

Hardware : 

1. Linux based 8 OCPU and 120 GB RAM (Dev2OCI tenancy)
2. Linux based 16 OCPU and 240 GB RAM (Dev2OCI tenancy)
3. Linux based 24 OCPU and 330 GB RAM (Dev2OCI tenancy)

## Steps to reproduce
1. Did scalability runs with concurrent threads from 1 to 1000 .
2. Config steup: 
Testing tool - Work(Client Testing tool),Redis cache and Party Management jar all running on different VM(All VM's belong to same AD.)
3. Captured JFR with the below startup commands:
```shell
java -Xmx30g -Xms30g -XX:StartFlightRecording:jdk.VirtualThreadStart#enabled=true,jdk.VirtualThreadEnd#enabled=true,jdk.VirtualThreadPinned#enabled=true -jar partyMgmt-with-dependency.jar
```

**JFR details are attached for reference for 50 users run in 8/16/24 OCPU boxes with the same Party Management jar.**
[CacheRead_8_16_24_OCPU JFR's_50users.zip](https://github.com/helidon-io/helidon/files/14435325/CacheRead_8_16_24_OCPU.JFR.s_50users.zip)

5. Resource usage: CPU didnt cross 70 % and Memory was under 30 GB on the above boxes
 
[8_16_24_OCPU reference for CPU and memory.zip](https://github.com/helidon-io/helidon/files/14433798/8_16_24_OCPU.reference.for.CPU.and.memory.zip)

6. TPS details are attached for reference. 
[Vertical Scaling TPS analysis.xls](https://github.com/helidon-io/helidon/files/14433490/Vertical.Scaling.TPS.analysis.xls)

**Comment by spericas** [comment]
Discussion about this benchmark will be moved to Slack. Once the real problem is identified (and if _it is actually_ in Helidon) a new issue will be opened.
