### ISSUE TITLE
2.x: MP quickstart fails to start: Error: Could not find or load main class

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#8464]
## Environment Details
* Helidon Version: 2.6.6-SNAPSHOT
* Helidon MP
* JDK version:
java 11.0.11 2021-04-20 LTS
GraalVM 21.3.0 Java 11 CE (Java Version 11.0.13+7-jvmci-21.3-b05)

----------

## Problem Description
If you build quickstart-mp that is generated from the Helidon archetype the resulting application jar won't run:

```
java -jar target/quickstart-mp.jar
Error: Could not find or load main class me.jdipol.mp.quickstart
Caused by: java.lang.ClassNotFoundException: me.jdipol.mp.quickstart
```

This is working with Helidon 2.6.5

## Steps to reproduce

Build the archetype in the helidon-2.x branch and run:

```
helidon init --reset --reset --url file:///path/to/helidon-2.x-repo/archetypes/catalog/target/cli-data
# Select MP, quickstart and accept other defaults
mvn clean install 
java -jar target/quickstart-mp.jar
```

Note: to run the helidon CLI this way you'll want the change in PR #8463

**Comment by barchetta** [comment]
This might be related to #8332

**Comment by tvallin** [comment]
fixed by https://github.com/helidon-io/helidon/pull/8465
