### ISSUE TITLE
StaticContentService Not Working with Java Modules

### ISSUE THREAD

**Issue by crgardner** [helidon-io/helidon#8483]
## Environment Details
* Helidon Version: 4.0.5
* Helidon SE
* JDK version: openjdk version "21.0.2" 2024-01-16 LTS
* OS: Fedora 37
* Docker version (if applicable): NA

----------

## Problem Description
Generated starter project with static content and Java modules returns 404 NOT FOUND for when requesting the static content. If I remove the module-info.java, making the application non-explcitly modular, Helidon finds the static content and returns it.

The following code was generated from the Helidon starter. The onlyh thin different is I removed the "/" redirect to "/ui" to see if that made any difference (it didn't):

```java
  static void routing(HttpRouting.Builder routing) {
        routing
               .register("/greet", new GreetService())
               .get("/simple-greet", (req, res) -> res.send("Hello World!"))

                .register("/ui", StaticContentService.builder("WEB")
                        .welcomeFileName("index.html")
                        .build())
                .register("/api", new FileService());
    }
``` 
This problem happens consistently with module-info.java. With no module-info.java, index.html is returned consistently.

Does StaticContentService need to be updated to find files differently than the classpath and file system when modules are used?

## Steps to reproduce
1. Generate a starter project with static content (the file upload example)
2. Start the application.
3. Navigate to the root or /ui URL.
4. Receive 404.

**Comment by romain-grecourt** [comment]
Add this to your module-info:

```java
opens WEB;
```

This is a bug in the archetype, the module-info generated should be functional.

**Comment by wojtask9** [comment]
Also this info "should" be also in documentation. When you use "jpms" StaticContent" not all paths are available like in classic classpath
