### ISSUE TITLE
HikariCP properties set but not read in datasource

### ISSUE THREAD

**Issue by ulisse1996** [helidon-io/helidon#8499]
## Environment Details
* Helidon Version: 4.0.6
* Helidon SE or Helidon MP: MP
* JDK version: Zulu 21.0.2
* OS: Arch Linux
* Docker version (if applicable):

----------

## Problem Description
When HikariCP is used with the [HikariCPBackedDataSourceExtension](https://github.com/helidon-io/helidon/blob/03579c44013fe94b54f020ade7c69da5b699e965/integrations/cdi/datasource-hikaricp/src/main/java/io/helidon/integrations/datasource/hikaricp/cdi/HikariCPBackedDataSourceExtension.java#L132), seems that HikariCP just receive properties in the constructor but don't use them to generate the connection pool, resulting in exception on jdbc connections creation.
My **microprofile-config.properties** contains the following lines:

```ini
javax.sql.DataSource.main.dataSource.jdbc.url = jdbc:postgresql:/host:5432/schema
javax.sql.DataSource.main.dataSource.username = postgres
javax.sql.DataSource.main.dataSource.password = changeMe
javax.sql.DataSource.main.dataSource.maxSize = 20
javax.sql.DataSource.main.dataSource.currentSchema = mySchema
```
The current workaround used is to make use of the useful event fired on CDI before the DataSource creation
```java
@ApplicationScoped
public class MainDatasourceEventListener {

    void enhanceConfig(@Observes HikariConfig config) {
        // Seems that hikari config is not correctly initialized, so we can override some properties
        Properties properties = config.getDataSourceProperties();
        config.setUsername(getOneOf(properties, "user", "username"));
        config.setPassword(getOneOf(properties, "password", "pass"));
        config.setJdbcUrl(getOneOf(properties, "url", "jdbcUrl", "jdbc.url"));
        config.setSchema("schema");
    }

    private String getOneOf(Properties properties, String... names) {
        for (String name : names) {
            if (properties.containsKey(name)) {
                return properties.getProperty(name);
            }
        }
        return null;
    }
}
```

I think we can set these properties without using the constructor as HikariConfig right now just set them in datasourceProperties without changing the current configuration instance
```java
public static void setTargetFromProperties(Object target, Properties properties) {
        if (target != null && properties != null) {
            List<Method> methods = Arrays.asList(target.getClass().getMethods());
            properties.forEach((key, value) -> {
                if (target instanceof HikariConfig && key.toString().startsWith("dataSource.")) {
                    ((HikariConfig)target).addDataSourceProperty(key.toString().substring("dataSource.".length()), value);
                } else {
                    setProperty(target, key.toString(), value, methods);
                }

            });
        }
    }
```

## Steps to reproduce
- Create a new project using MP
- Add dependencies for HikariCP without using JPA dependency
- Add a connection for the specific database
- Check that connecting to the datasource result in an exception for invalid jdbcUrl

**Comment by ljnelson** [comment]
I believe you will find this is user error. Any property prefixed with `.dataSource.` will be forwarded to the data source [as defined in the HikariCP documentation](https://github.com/brettwooldridge/HikariCP/blob/dev/README.md#rocket-initialization) (scroll down to "Example property file"). Your example should therefore probably be (untested):
```
javax.sql.DataSource.main.dataSourceClassName = org.postgresql.ds.PGSimpleDataSource
javax.sql.DataSource.main.dataSource.url = jdbc:postgresql:/host:5432/schema
javax.sql.DataSource.main.dataSource.user = postgres
javax.sql.DataSource.main.dataSource.password = changeMe
javax.sql.DataSource.main.maximumPoolSize = 20
javax.sql.DataSource.main.dataSource.currentSchema = mySchema
```
See also:
* https://github.com/brettwooldridge/HikariCP/blob/dev/README.md#essentials 
* https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
* https://github.com/helidon-io/helidon/wiki/FAQ#what-value-should-i-use-for-my-connection-pools-property-that-designates-my-datasource-class-name
