### ISSUE TITLE
4.x - ApplicationPath is not a bean defining annotation

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#8502]
## Environment Details
* Helidon Version: 4.0.6
* Helidon MP
----------

## Problem Description

`@Path` is a bean defining annotation but `@ApplicationPath` is not. When creating a JaxRs application annotated only with `@ApplicationPath` but not with `@ApplicationScope` it is discarded.

This can lead to incorrect behavior:
- if the path specified is not `/`
- if there are multiple applications each with a different path and different resource classes

Both `@Path` and `@Provider` are declared as bean defining annotations, most likely for convenience.

Is it an oversight that `@ApplicationPath` is not included ?

## Steps to reproduce

```java
public class Main {
    public static void main(String[] args) {
        io.helidon.Main.main(args);
    }

    @ApplicationPath("/")
    public static class App1 extends Application {

        @Override
        public Set<Class<?>> getClasses() {
            return Set.of(Resource.class);
        }

        @Path("/app1")
        public static class Resource {

            @GET
            public String get() {
                return "OK";
            }
        }
    }

    @ApplicationPath("/foo")
    public static class App2 extends Application {

        @Override
        public Set<Class<?>> getClasses() {
            return Set.of(Resource.class);
        }

        @Path("/app2")
        public static class Resource {

            @GET
            public String get() {
                return "OK";
            }
        }
    }
}
```

```shell
curl  http://localhost:8080/app2
OK
curl  http://localhost:8080/foo/app2
Not Found
```

**Comment by tomas-langer** [comment]
`ApplicationPath` cannot be a bean defining annotation, as it is not required on an application. If we made it BDA, some applications would be picked up, some would be ignored, and that is quite a bad behavior.
In general application class without a BDA should be ignored (and it should be `@ApplicationScoped`, as nothing else makes sense)

**Comment by romain-grecourt** [comment]
We have agreed on making `@ApplicationPath` a BDA, and warning about applications not annotated with `@ApplicationScoped`.

We should also investigate using the Jandex index to detect application classes with no annotations.

**Comment by tjquinno** [comment]
Some background that might be useful... 

The Helidon OpenAPI implementation layers on the SmallRye OpenAPI library. 

Helidon's MP OpenAPI code finds out what applications Helidon has discovered (by invoking Helidon's `JaxRsCdiExtension#applicationsToRun`).

Helidon then asks the SmallRye library to create a separate OpenAPI model for each separate application. Helidon then merges the separate OpenAPI models into a single one (using a SmallRye utility operation)  which gives rise to the single OpenAPI document output at the `/openapi` endpoint.

**Comment by dasTanmoy0096** [comment]
For some reason, @ApplicationPath("/") is not getting picked up a Bean Defining annotation in version 4.3.4. That should not be the case, right?

**Comment by spericas** [comment]
@dasTanmoy0096 It should not. Please provide a small reproducible if you see that behavior. Feel free to open a new issue.
