### ISSUE TITLE
Can't find any example of using WebClient with collection response

### ISSUE THREAD

**Issue by RassulYunussov** [helidon-io/helidon#8511]
In essence I would like to obtain the same scenario as we have for a single element but with typed collections.

If we have something like this for a single element
```
WebClient webClient = WebClient.builder()
            .baseUri("http://localhost:8084")
            .build();

Product product = webClient.get()
                            .path("/product")
                            .requestEntity(Product.class);
```

How should it be for ```List<Product>```?

Considering usage of helidon-http-media-jackson

**Comment by ljnelson** [comment]
Is this a question (in which case maybe ask it on StackOverflow or in the discussions area), or are you reporting a bug (in which case could you say what the bug is)?

**Comment by RassulYunussov** [comment]
It is a question.

**Comment by ljnelson** [comment]
Converting to discussion instead of issue, as that's what discussions are for.
