### ISSUE TITLE
Http Status 500 with "Accepted by If-None-Match header" is returned when serving unchanged static content

### ISSUE THREAD

**Issue by 1tchy** [helidon-io/helidon#8543]
## Environment Details
* Helidon Version: 4.0.6
* Helidon MP
* JDK version: 21.0.2
* OS: OSX

----------

## Problem Description
- When loading static content with a matching E-Tag, a HTTP-Status 500 ("Internal Server Error") is returned instead of 304 ("Not Modified") and the response contains "Accepted by If-None-Match header".
- It did work as expected in 4.0.5 and does not work anymore in 4.0.6, probably due to #8357.
- The following error is being logged: "Attempt to send status 500 Internal Server Error with entity. Server responded with Internal Server Error. Please fix your routing, this is not allowed by HTTP specification, such responses MUST NOT contain an entity."

## Steps to reproduce
- Create a project which serves a static file with helidon-webserver-static-content.
- Load the file in your favourite browser, this shows the file
- Reload the file in your favourite browser, this returns error 500 and the message "Accepted by If-None-Match header" is being shown instead of the files content

**Comment by mikarinneoracle** [comment]
Also getting this error 4.0.6

**Comment by Rinbo** [comment]
This is still an issue in 4.0.11
