### ISSUE TITLE
4.x: Make HttpRouting an interface

### ISSUE THREAD

**Issue by VerKWer** [helidon-io/helidon#8572]
## Environment Details
* Helidon Version: 4.0.6
* Helidon SE

----------

## Problem Description
This is more of an improvement proposal but does address an actual issue as well (though probably not one that people will encounter in practice). Currently `HttpRoute` is an interface, whereas `HttpRouting` isn't (it's a final class). It would be good to be consistent and make both interfaces, as it allows for more configurability, and almost everything else that can be specified in a `WebServer` builder is an interface.

### Use Case
Being able to implement your own `HttpRouting` type can be useful when moving an existing service to Helidon; for example if there already is custom routing logic for it.

### Issue to Solve Along the Way
As for the actual issue (one might call it a bug) I encountered while working on this: other routing classes (such as `GrpcRouting`) aren't final, which one might understand as Helidon supporting custom implementations. However, if one does so, requests aren't properly routed anymore. The reason for this is that the `RouterImpl` indexes `Routing` instances by their class and its `routing` method is always called with a fixed class. Therefore, when trying to use a custom implementation, it wouldn't be found.

This issue needs to be addressed if one wants to make `HttpRouting` an interface. As a side-effect it would fix the "bug" just described, allowing the `RouterImpl` to handle custom implementations of other routing types.

### Compatibility
This change should be (mostly) backwards compatible. Currently, the `HttpRouting` class is final (so no existing code can break because it subclasses `HttpRouting`) and its constructor is private (so no existing code can break because the constructor won't exist anymore).

### Other Considerations
Even with `HttpRouting` becoming an interface, it wouldn't be straightforward to use a custom implementation. The `WebServer.Builder.routing` method takes a `HttpRouting.Builder`; providing a `HttpRouting` instance directly isn't possible. So, to use a custom routing implementation, one would also have to also create a custom `HttpRouting.Builder`, whose `build` method returns an instance of the custom routing implementation. This isn't great but also not a big deal as most users won't be doing this. Anyway, improving this is out of scope of this issue.

**Comment by tomas-langer** [comment]
Thank you for your contribution!
