### ISSUE TITLE
`Span.current()` does not return `Optional.empty()` if there is no current span, contrary to the documented contract (OTel)

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#8573]
## Environment Details
* Helidon Version: 3.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
The Helidon tracing API documents that `Span.current()` will return `Optional.empty()` if there is no current span.

But, for OpenTelemetry (and, therefore, Jaeger) `Span.current()` always returns a value. If there was no current span it returns an `Optional` of a no-op span (trace and span IDs = 0).

## Steps to reproduce
With the Helidion OTel dependency in the project, invoke `Span.current()` before creating and activating a span. You get an `Optional` of a valid (but no-op) span.

**Comment by RickyFrost** [comment]
The above happens in the product for an untraced path when serverRequest.spanContext() is called, for example /health

**Comment by RickyFrost** [comment]
tracing:
  # Don't need to trace these paths...
  paths:
    - path: /dontTraceMe
      enabled: false
