### ISSUE TITLE
Add support for simple annotation to run any method on a platform thread

### ISSUE THREAD

**Issue by spericas** [helidon-io/helidon#8638]
## Problem Description

Related to issue #8591, but rather than requiring the use of the FT module (and all that implies), this issue is about a simple annotation that can be used in any MP bean to offload the execution of a method onto a platform thread. One proposed name is `@AsyncPlatform`.

**Comment by ljnelson** [comment]
You might also look into CDI's built-in asynchronous event support which may be a simpler way to do this, complete with things like [executor customization etc.](https://jakarta.ee/specifications/cdi/4.0/apidocs/jakarta.cdi/jakarta/enterprise/event/event#fireAsync(U,jakarta.enterprise.event.NotificationOptions)). (Weld itself may have this facility built-in as well; cannot remember.)

**Comment by spericas** [comment]
#8643
