### ISSUE TITLE
Health check response no longer orders the data details

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#8645]
## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
In 3.x, the details in a health check response were ordered by the name of the detail. 

That is no longer the case in 4.x.

**Comment by RickyFrost** [comment]
This affects our automated tests, where we now have to wrap the details in TreeMap before comparison. But most important, it affects readability where we have to copy the result and do "jq -S" on it. But that puts the name and status below the details. This should be an easy fix :-)
