### ISSUE TITLE
4.x Add next() for io.helidon.webserver.http.ServerRequest

### ISSUE THREAD

**Issue by essapp** [helidon-io/helidon#8711]
## Environment Details
* Helidon Version:4.x
* Helidon SE or Helidon MP
* JDK version:21.x
* OS:mac
* Docker version (if applicable):

----------

## Problem Description
3.x ServerRequest has next().continue request processing on the next registered handler.

**Comment by romain-grecourt** [comment]
The method has move to [ServerResponse.next()](https://helidon.io/docs/4.0.7/apidocs/io.helidon.webserver/io/helidon/webserver/http/ServerResponse.html#next())

**Comment by essapp** [comment]
My code:
  @Override
  public void routing(HttpRules rules) {
    rules
        .any((req, res) -> {
          req.headers().contentType().ifPresent(mt -> {
            if (!mt.equals(MediaTypes.APPLICATION_JSON)) {
              sendUndefinedMediaType(res, mt.toString());
            } else {
              req.next();
            }
          });
        })
        .route(Http1Route.route(DELETE, "/", new DelData()::execute))
        .any((req, res) -> sendNotFound(res, "404"));
  }
What should I do after using ServerResponse.next()?

**Comment by romain-grecourt** [comment]
> What should I do after using ServerResponse.next()?

Nothing, you simply return, that part hasn't changed.
