### ISSUE TITLE
`config-metadata.json` lacks configKey for ConfiguredProviders

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#8776]
## Environment Details
* Helidon Version: 4.0.8

----------

## Problem Description

[ConfiguredProvider](https://github.com/helidon-io/helidon/blob/4.0.8/common/config/src/main/java/io/helidon/common/config/ConfiguredProvider.java) defines a method `configKey()`. This key is not reflected anywhere in `config-metadata.json`

For example [Http1ProtocolConfigProvider](https://github.com/helidon-io/helidon/blob/4.0.8/webclient/http1/src/main/java/io/helidon/webclient/http1/Http1ProtocolConfigProvider.java) has a configKey of `http_1_1`. But the corresponding entry in config-metadata.json lacks that information:

```
  {
                "annotatedType": "io.helidon.webserver.http1.Http1Config",
                "type": "io.helidon.webserver.http1.Http1Config",
                "producers": [
                    "io.helidon.webserver.http1.Http1Config#create(io.helidon.common.config.Config)",
                    "io.helidon.webserver.http1.Http1Config#builder()"
                ],
                "provides": [
                    "io.helidon.webserver.spi.ProtocolConfig"
                ],
                "options": [
                 . . .
                ]
  }
```

## Background

My assumption is that `config-metadata.json` provides the schema for module configuration. It should be possible to derive a skeleton `application.yaml` using only the information provided in `config-metadata.json` files.  Currently that is not possible due to missing `configKey`

**Comment by tomas-langer** [comment]
This should fix the problem:
```
@Prototype.Configured(root = false, value = "http_1_1")
```

**Comment by tomas-langer** [comment]
We should also add a validation that if the following annotations coexist:
```
@Prototype.Configured
@Prototype.Provides(ProtocolConfig.class)
```
an error is reported, as such a combination is expected to have a configuration key.
