### ISSUE TITLE
Role Mapper - sensitive data in oidc-config

### ISSUE THREAD

**Issue by arnmohan** [helidon-io/helidon#8777]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 3.2.8
* Helidon SE or Helidon MP: Helidon MP
* JDK version: JDK 17

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

Role Mapper is currently using IDCS client secret from oidc-config which is sensitive data . 

oidc-config:
            client-id: "client-id"
            client-secret: " ***** "
            identity-uri: "IDCS identity server address"

We need to ensure sensitive data in OIDC config could potentially come from Vault (i.e., if oidc-config is an OCID to vault-secret then resolve it from OCI)

**Comment by arjav-desai** [comment]
You can encrypt config values, please see section "encryption" under https://helidon.io/docs/latest/mp/config/introduction

**Comment by arnmohan** [comment]
security.config:
  # Set to true for production - if set to true, clear text passwords will cause failure
  require-encryption: false
  # The "master" password for AES decryption. For production, set this via system property or environment variable.
  **aes.insecure-passphrase: "myMasterPasswordForEncryption"**
  # See documentation of pki-util
  rsa:
    keystore:
      # load from classpath
      **resource.resource-path: ".ssh/keystore.p12"**
      # If keystore is used, alias to use from the keystore (in this example, it is "1")
      key.alias: "1"
      # Password of keystore
      passphrase: "helidon".                                


In this example, do we need a file to keep the encryption key ? if so where do we store file
