### ISSUE TITLE
Some metrics configuration options default are not documented

### ISSUE THREAD

**Issue by hyder** [helidon-io/helidon#8805]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.0.8
* Helidon SE or Helidon MP
* JDK version: N/A
* OS: N/A
* Docker version (if applicable): N/A

----------

## Problem Description
Helidon metrics configuration are available but the default values for some of those are not documented: https://helidon.io/docs/v4/mp/metrics/metrics

[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

**Comment by tomas-langer** [comment]
This may be fixed by https://github.com/helidon-io/helidon/pull/8852 - I have regenerated all the config reference documentations.
