### ISSUE TITLE
Consider replacing usages of ConcurrentHashMap

### ISSUE THREAD

**Issue by spericas** [helidon-io/helidon#8836]
## Problem Description

`ConcurrentHashMap` is implemented using `synchronized` blocks. We recently found an issue that was causing some of our tests to hang due to the use of this class (see #8813). We should consider replacing usages of this class for our own maps and locks to avoid these problems. 

A quick search shows 110 matches in our codebase, many of which are in tests.

**Comment by ljnelson** [comment]
Related: https://mail.openjdk.org/pipermail/loom-dev/2024-May/006632.html

**Comment by spericas** [comment]
Created issues for each of the places that require additional analysis. Issues #8966, #8967, #8968, #8969, #8970, #8971, #8972, #7973. All issues have been assigned.
