### ISSUE TITLE
Add the ability to get the ip address of the client in websocket

### ISSUE THREAD

**Issue by essapp** [helidon-io/helidon#8856]
## Environment Details
* Helidon Version:4.0.9
* Helidon SE
* JDK version:21
* OS:mac
* Docker version (if applicable):

----------

## Problem Description
In actual use, often need to get the ip address of the client, in the websocket server development.

**Comment by essapp** [comment]
> One option would be to make the `SocketContext` available from the `WsSession`, and then:
> 
> ```java
> WsSession ws = ...
> PeerInfo peer = ws.socketContext().remotePeer();
> ```
> 
> Are you using the Proxy Protocol in your app?

Yes, you might.

**Comment by spericas** [comment]
> > One option would be to make the `SocketContext` available from the `WsSession`, and then:
> > ```java
> > WsSession ws = ...
> > PeerInfo peer = ws.socketContext().remotePeer();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Are you using the Proxy Protocol in your app?
> 
> Yes, I might, thanks!

If using https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt then there's already support for it (it just needs to be enabled by turning it on the listener) and you get host and port info in the request headers `X-Forwarded-For` and `X-Forwarded-Port` (automatically added by Helidon). Note that the proxy protocol _preamble_ is not optional, if enabled, then it must be present. If that's what you need, then it's already in 4.0.9.

**Comment by essapp** [comment]
> > > One option would be to make the `SocketContext` available from the `WsSession`, and then:
> > > ```java
> > > WsSession ws = ...
> > > PeerInfo peer = ws.socketContext().remotePeer();
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Are you using the Proxy Protocol in your app?
> > 
> > 
> > Yes, I might, thanks!
> 
> If using https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt then there's already support for it (it just needs to be enabled by turning it on the listener) and you get host and port info in the request headers `X-Forwarded-For` and `X-Forwarded-Port` (automatically added by Helidon). Note that the proxy protocol _preamble_ is not optional, if enabled, then it must be present. If that's what you need, then it's already in 4.0.9.

OK,thanks!
