### ISSUE TITLE
3.x: Micrometer documentation mentions deprecated `MicrometerMeterRegistry`

### ISSUE THREAD

**Issue by tvallin** [helidon-io/helidon#8940]
## Environment Details
* Helidon Version: 3.2.8
* Helidon SE
* JDK version: 17
* OS: n/a
* Docker version (if applicable): n/a

----------

## Problem Description

Micrometer metrics documentation mentions `MicrometerMeterRegistry`, it is deprecated and removed.

## Steps to reproduce

See https://helidon.io/docs/v3/se/metrics/micrometer#_create_and_update_meters_in_your_application_service

**Comment by tjquinno** [comment]
This is a doc typo. In the 3.x source Helidon's `MicrometerSupport#registry` method actually returns a `MeterRegistry` (not the type `MicrometerMeterRegistry`).

https://github.com/helidon-io/helidon/blob/224714191e89ff0f4785202fb23b0aa27b49dbcf/integrations/micrometer/micrometer/src/main/java/io/helidon/integrations/micrometer/MicrometerSupport.java#L87-L95
