### ISSUE TITLE
Doc update needed: Supported APIs wiki page

### ISSUE THREAD

**Issue by david-cabelus-oracle** [helidon-io/helidon#8949]
## Environment Details
* Helidon Version: 4

----------

## Problem Description
The wiki page at https://github.com/helidon-io/helidon/wiki/Supported-APIs lists APIs for Helidon 3, 2.5, and 1.4. There is no column for 4.0 APIs

Note that if this information is contained in the official documentation, we should point to the appropriate doc pages from this wiki.

**Comment by barchetta** [comment]
Done
