### ISSUE TITLE
After using the database to build the application, the test times error

### ISSUE THREAD

**Issue by essapp** [helidon-io/helidon#8954]
## Environment Details
* Helidon Version:4.0.10
* Helidon SE or Helidon MP:SE
* JDK version:21
* OS:MAC
* Docker version (if applicable):

----------

## Problem Description
<img width="592" alt="image" src="https://github.com/helidon-io/helidon/assets/92622299/a3d058d1-c63a-42a7-b2c5-a16e0fa638ba">

## Steps to reproduce
![image](https://github.com/helidon-io/helidon/assets/92622299/a80c8f4a-6f34-4b96-8352-336021ffda3b)

Because of field name capitalization issues.

**Comment by tvallin** [comment]
The issue cannot be reproduced:
- I generated a project using the maven command you provided
- `mvn install` to build the project
- The tests are passing

Please provide more information to reproduce your error.

**Comment by essapp** [comment]
> The issue cannot be reproduced:
> 
> * I generated a project using the maven command you provided
> * `mvn install` to build the project
> * The tests are passing
> 
> Please provide more information to reproduce your error.

Reproducing the environment:
https://github.com/essapp/server

**Comment by tvallin** [comment]
I see, so I recommend you to use helidon CLI or our starter project (https://helidon.io/starter/4.0.10?step=4&app-type=database) to generate your sample app. So you can select oracle DB and avoid these issues. You can take a look at our example as well : https://github.com/helidon-io/helidon/tree/main/examples/dbclient

**Comment by essapp** [comment]
> I see, so I recommend you to use helidon CLI or our starter project (https://helidon.io/starter/4.0.10?step=4&app-type=database) to generate your sample app. So you can select oracle DB and avoid these issues. You can take a look at our example as well : https://github.com/helidon-io/helidon/tree/main/examples/dbclient

I just saw the solution in :https://github.com/helidon-io/helidon/blob/main/examples/dbclient/jdbc/src/test/java/io/helidon/examples/dbclient/jdbc/AbstractPokemonServiceTest.java
private String getName(JsonObject json) {
        return json.containsKey("name")
                ? json.getString("name")
                : json.getString("NAME");
    }
