### ISSUE TITLE
Build observe using 'server.features.observe' in main,but it doesn't exist config in application.yaml

### ISSUE THREAD

**Issue by essapp** [helidon-io/helidon#8955]
## Environment Details
* Helidon Version:4.0.10
* Helidon SE or Helidon MP:SE
* JDK version:21
* OS:MAC
* Docker version (if applicable):

----------

## Problem Description
main.java:
  ObserveFeature observe = ObserveFeature.builder()
                  .config(config.get("server.features.observe"))
                  .addObserver(HealthObserver.builder()
                  .addCheck(DbClientHealthCheck.create(dbClient, config.get("db.health-check")))
                  .build())
                  .build();
applicationyaml:
  server:
    port: 8080
    host: 0.0.0.0
  
  app:
      greeting: "Hello"

## Steps to reproduce
Reproducing the environment:
https://github.com/essapp/server

**Comment by tvallin** [comment]
Thanks for catching this.

This property can be used to customized observability : https://helidon.io/docs/v4/se/observability
