### ISSUE TITLE
Review ConcurrentHashMap usage in helidon-integration-cdi-jpa

### ISSUE THREAD

**Issue by spericas** [helidon-io/helidon#8966]
## Problem Description
Thread pinning can occur if the mapping function passed to any of the `compute` methods in `ConcurrentHashMap` results in any I/O. The internal implementation of `ConcurrentHashMap` will hold a lock while the VT is parked, causing the pinning. 

Note that I/O in the mapping function can be indirect: for example, using config or a service loader. Please verify that the following calls will never need I/O to complete:

```
JtaAdaptingDataSourceProvider:168
JtaAdaptingDataSourceProvider:180
```

If required, re-implement the map using a traditional reentrant lock and a hash map.

**Comment by ljnelson** [comment]
In this case, there is no IO work taking place inside the computing lambda. I recommend leaving the code as it is.
