### ISSUE TITLE
4.x: Consider better class name than Object in metadata Hson

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#9075]
Current we use `Hson.Object` for object abstraction in output (similar to JsonObject).
This may create confusion if somebody does an import of the type, as it would get confused with `java.lang.Object`.

As this is designed for metadata handling within Helidon, we control our destiny, but still this may be useful (if we come up with a great alternative).

**Comment by romain-grecourt** [comment]
How about `Hson.Struct` ?
