### ISSUE TITLE
4.1.0 - Exclude generated descriptors from javadocs

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#9076]
## Environment Details
* Helidon Version: 4.1.0-SNAPSHOT

----------

## Problem Description

4.1.0 introduces new generated sources, which must be public. However those sources are not user APIs and only exist to wire things up.

Such generated sources often include a `__` in their file name.

E.g.

![Screenshot 2024-07-31 at 3 11 19 PM](https://github.com/user-attachments/assets/dd949866-3cdd-4fd6-847d-1ae7addce9f0)

We need to refine the javadoc configuration to exclude these generated sources from the javadoc.
E.g. using an exclude pattern like `**/*__*.java`.

## Steps to reproduce

```shell
mvn package -DskipTests -Pjavadoc -pl integrations/oci/authentication/instance
```

**Comment by tomas-langer** [comment]
This also requires update to the `docs/pom.xml`, as it has its own definition of javadoc, and still generated the files even when disabled in root pom.

**Comment by tomas-langer** [comment]
Depends on https://github.com/helidon-io/helidon-build-tools/pull/1059 to fully support this
