### ISSUE TITLE
4.x: webserver/protocols example fails to build on Oracle Linux Server release 7.7

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#9126]
## Environment Details
* Helidon Version: 4.1.0
* Helidon SE
* JDK version: java 21 2023-09-19 LTS
* OS:  Oracle Linux Server release 7.7

----------

## Problem Description

When using Helidon 4.1.0 the example `webserver/protocols` fails to build on Oracle Linux Server 7.7 with the error:
```
helidon-examples/examples/webserver/protocols/target/protoc-plugins/protoc-gen-grpc-java-1.65.1-linux-x86_64.exe: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by helidon-examples/examples/webserver/protocols/target/protoc-plugins/protoc-gen-grpc-java-1.65.1-linux-x86_64.exe)
```

This works with Helidon 4.0.11.

It looks like more recent versions of GCC require a newer version of libstdc++, so this is likely an environmental issue that can be solved with an upgrade.  It would be good to know if this is supported on Oracle Linux 7 and if so what version of libstdc++ is required.

## Steps to reproduce

On an Oracle Linux 7.7 machine:

1.  git clone git@github.com:helidon-io/helidon-examples.git
2. git checkout dev-4.x
3. cd examples/webserver/protocols
4. Change parent version of pom.xml to `<version>4.1.0</version>`
5. mvn clean install

**Comment by spericas** [comment]
Fixed by PR #9162.
