### ISSUE TITLE
4.x: release script is not closing staging repository plus other release issues

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#9127]
During 4.1.0 development the release script was broken and some non-deployable modules were introduced. Most of the issues were fixed while doing the 4.1.0 release, but one remains: the ossrh staging repository is left open after the artifact deployment.

Things we need to do:

1. Forward port [the release fixes](https://github.com/helidon-io/helidon/commits/4.1.0/) from the 4.1.0 tag to main. These include fixes to the release.sh script as well as updates to a few modules to satisfy ossrh staging requirements (javadocs).
2. Fix the release.sh script to close the staging repository.

**Comment by romain-grecourt** [comment]
Fixed in #9210
