### ISSUE TITLE
2.x/3.x: Support ability to timeout idle connections

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#9163]
## Environment Details
* Helidon Version: 2.6.7
* Helidon SE 

----------

## Problem Description

In Helidon 4 the WebServer supports [`idle-connection-timeout`](https://helidon.io/docs/v4/config/io_helidon_webserver_WebServer) that controls how long it should wait before closing a connection that has no traffic on it.

Helidon 2 and 3 (which are Netty based) do not appear to have such capability.  To implement this might require using Netty's [`IdleStateHandler `](https://netty.io/4.0/api/io/netty/handler/timeout/IdleStateHandler.html)

**Comment by ggsrivas** [comment]
HI Team,
We are facing this issue on our service. The open socket count keeps going up and stops accepting new connection in 7-8 days. We are forced to restart the service to clean those open connections. This is affecting our customer as the API as inaccessible when this happens. Any ETA for this fix?

**Comment by spericas** [comment]
Fixed in 2.x and 3.x

**Comment by ggsrivas** [comment]
@spericas should we expect a 2.6.9 release soon with this fix? I don't see that tag on Github.

**Comment by spericas** [comment]
> @spericas should we expect a 2.6.9 release soon with this fix? I don't see that tag on Github.

@barchetta ?

**Comment by barchetta** [comment]
It will be soon, but I do not have an ETA at the moment. I am making a build change so that we can produce a 2.6.9-SNAPSHOT build that you can test with.

**Comment by spericas** [comment]
> @ggsrivas It will be soon, but I do not have an ETA at the moment. I am making a build change so that we can produce a 2.6.9-SNAPSHOT build that you can test with. I will notify you once that is ready.

That's actually a great idea, trying out a SNAPSHOT version to verify this works in your environment.

**Comment by barchetta** [comment]
@ggsrivas 2.6.9-SNAPSHOT with the fix is available at: https://oss.sonatype.org/content/repositories/snapshots/io/helidon/
