### ISSUE TITLE
Improvements observed with larger buffer sizes and chunked encoding

### ISSUE THREAD

**Issue by nairiti-sharma** [helidon-io/helidon#9189]
We observed 6X response time degradation on an API that fetches >7KB response with chunked encoding.

* Helidon Version: 4.0.11
* Helidon SE or Helidon MP : SE
* JDK version: GraalVM on JDK21
* OS: Linux
* Docker version (if applicable): NA

----------

## Problem Description
On H3, there was no setting specific to byte buffer and it was left at the default value (https://github.com/netty/netty/blob/netty-4.1.108.Final/transport/src/main/java/io/netty/channel/socket/nio/NioSocketChannel.java )

On H4, there is a default of 512B which is causing the performance degradation. 

In the JFR we could see that the number of Socket Writes with H4 are 2 times more than H3, even when throughput of H3 is 4 times more than H4. 

When we increased this value to 8KB (-Dserver.write-buffer-size=8192), performance is at par with H3.

H3 : RT  - 4.02ms
H4 (Default) : RT - 24ms
H4 with write-buffer-size - 1KB : RT - 5.37ms
H4 with write-buffer-size - 8KB : RT - 4.23ms

## Steps to reproduce
Any response that has size greater than 7KB and "Transfer-Encoding: chunked" , would reproduce this issue.

![H3JFR](https://github.com/user-attachments/assets/d8a0dd1e-ef51-4c2a-a0fc-97fc3fb5e41c)
![H4JFR](https://github.com/user-attachments/assets/173a7e86-615d-4821-ac4c-bb7148ac3399)

**Comment by spericas** [comment]
@nairiti-sharma Let's consider a buffer size of 2-4K as a potential new default. Apps can always increase this if necessary.

**Comment by nairiti-sharma** [comment]
These are the final numbers
H3 : RT - 3.87ms
H4 (Default) : RT - 28.5ms
H4 with write-buffer-size - 1KB : RT - 5.37ms
H4 with write-buffer-size - 4KB : RT - 5.24ms
H4 with write-buffer-size - 8KB : RT - 3.94ms

Setting 4K by default should work well. Services can tune this further as per their requirement.
