### ISSUE TITLE
Outdated micrometer dependency clashing with more recent libraries

### ISSUE THREAD

**Issue by DavideRossi** [helidon-io/helidon#9208]
## Environment Details
* Helidon Version: MP 4.1.0
* JDK version: 21
* OS: Linux
----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
I'm having runtime issues using libraries (e.g. jena-fuseki) that depend on micrometer (Prometheus).
`mvn dependency:tree` shows that Helidon 4.1.0 depends on `io.micrometer:micrometer-core:jar:1.11.3` which is "old" (current version is 1.13.3) and clashes when using other libraries depending on more recent versions (the micrometer guys like to break the APIs across minor versions).

**Comment by tjquinno** [comment]
Reopening; need to update the Micrometer Prometheus dependency also.
