### ISSUE TITLE
Update IDCS configuration guide

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#9227]
## Environment Details
* Helidon Version: 4 (and all previous, as this is a change in IDCS)
* Helidon MP (most likely SE as well, as this is IDCS side of the setup)
----------

The UI of IDCS was updated, and our setup guide is no longer valid.

https://docs.oracle.com/en/cloud/paas/identity-cloud/uaids/oracle-identity-cloud-service.html#GUID-BC4769EE-258A-4B53-AED5-6BA9888C8275

Example that is wrong:
https://github.com/helidon-io/helidon-examples/tree/helidon-4.x/examples/microprofile/idcs

**Comment by tvallin** [comment]
Fixed by https://github.com/helidon-io/helidon-examples/pull/94
