### ISSUE TITLE
There is no Logging Formatter that will handle JSON for JUL

### ISSUE THREAD

**Issue by klustria** [helidon-io/helidon#9259]
## Environment Details
* Helidon Version: All
* Helidon SE or Helidon MP: Both

----------

## Problem Description
Currently, there is no appropriate Formatter for JSON with JUL. The alternative is to use SimpleFormatter like this: 

```
java.util.logging.SimpleFormatter.format={"ts":"%1tQ","timestamp":"%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS.%1$tL","level":"%4$s","logger":"%3$s","thread":"!thread!","msg":"%1$tQ - %5$s%6$s"}%n
```

but will break in instances where the message has multi-lines. The goal of this request is to  find a suitable approach that will handle this.

**Comment by tomas-langer** [comment]
The solution as I am working on it right now:
- there will be a new `io.helidon.logging.jul.HelidonJsonFormatter` that can be used (both with `HelidonConsoleHandler` and with the JUL `ConsoleHandler`).
- it will "guess" JSON structure if configured using simple formatter (i.e. it can act as a replacement for JUL's `SimpleFormatter`, may not provide the best results in this case, if some unusual format options are used (esp. for date and time)
- you can configure `io.helidon.logging.jul.HelidonJsonFormatter.fields` to construct the JSON object

Example of configuration (this is the default if no format or fields specified):
```
date:%1$tY.%1$tm.%1$td,time:%1$tH:%1$tM:%1$tS,level:%4$s,message:%5$s,exception:%6$s,thread:!thread!,logger:%3$s
```

Example of output message (as a single line, always):
```json
{
    "date":"2024.09.18",
    "time":"17:46:17",
    "level":"INFO",
    "message":"Creating Zipkin Tracer for 'helidon-se' configured with: http://localhost:7076/zipkin/api/v2/spans",
    "thread":"Thread[#1,main,5,main]",
    "logger":"io.helidon.tracing.providers.zipkin.ZipkinTracerBuilder"
}
```

**Comment by tomas-langer** [comment]
And example of `logging.properties`:
```properties
handlers=io.helidon.logging.jul.HelidonConsoleHandler
# Use JSON formatter with default format
io.helidon.logging.jul.HelidonConsoleHandler.formatter=io.helidon.logging.jul.HelidonJsonFormatter

.level=INFO
```

**Comment by talios** [comment]
When using SLF4j's `logger.addKeyValue("x","y).log()` will this still encode `x=y` in the `message`, or as separate JSON properties?   The later would be awesome if possible.

I'm not if that's possible to do tho, as I suspect SLF4j is just doing the lowest common logging strategy here.
