### ISSUE TITLE
ClientProperties not honoured while using HelidonConnectorProvider

### ISSUE THREAD

**Issue by pradeepraob** [helidon-io/helidon#9261]
## Environment Details
* Helidon Version: 4.1.0
* Helidon SE
* JDK version: Java 21
* OS: Oracle Linux
* Docker version (if applicable):

----------

## Problem Description
We are using HelidonConnectorProvider while creating a Client and sending requests.
Our remote server isn't responding to 'Expect: 100-continue' header for request with payloads
Such requests are timing out

`ClientConfig cc = new ClientConfig()
            .connectorProvider(HelidonConnectorProvider.create())
            .property(ClientProperties.FOLLOW_REDIRECTS, Boolean.TRUE)
            .property(ClientProperties.CONNECT_TIMEOUT, connectTimeoutMsecs)
            .property(ClientProperties.READ_TIMEOUT, queryTimeoutMsecs)

Client client = ClientBuilder.newClient(cc);`

So we tried putting following property, but still requests are sent with same header - 'Expect: 100-continue'

Tried setting it both on ClientConfig and Client but in vain

`ClientProperties.EXPECT_100_CONTINUE to false`

In debug process, found that HelidonConnector is ignoring any property starting with 'jersey' in the process of 'Map a Jersey request to a Helidon HTTP request.'

https://github.com/helidon-io/helidon/blob/5bd8681d69278e910645dd71f32e6a021647cd80/jersey/connector/src/main/java/io/helidon/jersey/connector/HelidonConnector.java#L139C8-L139C55

Expected behaviour is that HelidonConnectorProvider should honour provided ClientProperties

## Steps to reproduce
Use above sample code to create a client (internally HelidonConnectorProvider will create WebClient I guess) and use it to send PUT request with some payload, we will see 'Expect: 100-continue' header and if server doesn't respect it, it would timeout.
(I think MockServer doesn't respect this header.)

**Comment by spericas** [comment]
@pradeepraob See PR #9332
