### ISSUE TITLE
Prototype Metro intregration with WebServer

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#928]
Prototype Metro integration with the WebServer.

While not a part of Microprofile, Metro provides a SOAP / JAXWS implementation that can be nice to have in order to bridge the gap with legacy JavaEE application and help transitioning to Helidon.

**Comment by m0mus** [comment]
Draft prototype is here: https://github.com/lukasj/metro-helidon
It needs review.

**Comment by m0mus** [comment]
Assigned folks, please review what Lukas has done.

**Comment by romain-grecourt** [comment]
The link is dead.

**Comment by m0mus** [comment]
@romain-grecourt It's a private repository. I've asked Lukas to give you access.

**Comment by romain-grecourt** [comment]
The metro support for Helidon has been implemented in metro.
See:
- https://medium.com/helidon/soap-with-helidon-51bb2dc3189e
- https://github.com/eclipse-ee4j/metro-jax-ws/tree/3.0.2/jaxws-ri/extras/helidon-integration

**Comment by lukasj** [comment]
for helidon 3.1+ there is https://github.com/lukasj/helidon-soap-ws
