### ISSUE TITLE
Upgrade database dependencies to latest version (23ai)

### ISSUE THREAD

**Issue by hyder** [helidon-io/helidon#9367]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
Helidon currently packages the dependencies for 21c for the Oracle Database driver: https://helidon.io/docs/v4/mp/persistence#DS-Oracle-Driver-Maven-Coordinates

This is a enhancement request to update the dependencies included in 

```
<dependency>
    <groupId>io.helidon.integrations.db</groupId>
    <artifactId>ojdbc</artifactId>
    <scope>runtime</scope> 
</dependency>
```
 to 23ai.

**Comment by barchetta** [comment]
See #9351
