### ISSUE TITLE
Failure of custom config source is not failing config.create()

### ISSUE THREAD

**Issue by nikhilmittap** [helidon-io/helidon#9383]
I've noticed a change in behavior within the Helidon config module in the 4.1.0-SNAPSHOT version.
We have a custom configuration source, and until now, when this source failed, it would throw an exception which causes the creation of config object fail leading to a server startup failure. This is expected behavior for us, and this is a mandatory config source.
However, in the 4.1.0-SNAPSHOT  version I observed a different behavior, when this source fails or any config source fails, config.create will not fail and server is starting and ready to take requests.

## Environment Details
* Helidon Version: 4.1.0-SNAPSHOT
* Helidon SE 

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce
1. Run the attached quickstart SE application without any changes, you will see application running and it prints  app.greeting value: I am from custom config source: idcs-config-provider  and application started successfully.
2. Now add an env variable throwError=true  and rerun the application. this makes the custom config source fails -> creation of config fails -> server startup fails. So far it's expected behavior
3. Now change the Helidon config lib version to 4.1.0-SNAPSHOT and rerun your application and make sure the env variable throwError=true  is set. now you will notice, though the custom config source fails, config.create will not fail and server starts happily and ready to take requests.

[helidon-quickstart-se.zip](https://github.com/user-attachments/files/17365569/helidon-quickstart-se.zip)

**Comment by spericas** [comment]
Possibly related to PR #9233

**Comment by spericas** [comment]
@nikhilmittap Could you try throwing an `Error` instead of an `Exception`?

**Comment by nikhilmittap** [comment]
@spericas It's working as expected when throwing an Error instead of an Exception. Is this the way you recommend us going forward?

**Comment by spericas** [comment]
> @spericas It's working as expected when throwing an Error instead of an Exception. Is this the way you recommend us going forward?

Yes, if your intention is to abort the application, throwing an `Error` indicates the presence of an _abnormal condition_ that shouldn't be recovered from.

**Comment by tomas-langer** [comment]
I think this is a regression on our side, and we should fix the regression (maybe using a specific exception type for failure of meta-configuration in SE).
User errors should fail config setup as desired by the customer here.

I think this is a bug and we should refactor our previous fix.

**Comment by nikhilmittap** [comment]
Got it, let us know when the fix is available to test again.

**Comment by barchetta** [comment]
@nikhilmittap can you verify if this issue occurs in Helidon 4.1.2? I suspect it does not.
