### ISSUE TITLE
Config$Key.unescapeName() performance optimizations

### ISSUE THREAD

**Issue by brian-maulding** [helidon-io/helidon#9430]
## Environment Details
* Helidon Version: 3.x and 4.x
* Helidon SE and MP
* JDK version: 21
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description
Profiles of an application that frequently queries Config data shows significant time in io.helidon.config.Config$Key.unescapeName().  String.replaceAll() is used for simple string replacement (no regex) resulting in Pattern compilation and regex evaluation:
```
escapedName.replaceAll("~1", ".")
                    .replaceAll("~0", "~")
```

Using String.replace() will improve performance:
```
escapedName.replace("~1", ".")
                    .replace("~0", "~")
```

**Comment by tomas-langer** [comment]
This is correct, there is no need to use regular expression here, a simple string lookup is sufficient.
