### ISSUE TITLE
`grpcurl` returns error when accessing users's app and Helidon's gRPC example app

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#9449]
## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
Two users in the public Slack channel https://helidon.slack.com/archives/CCS216A5A/p1730149692724299 reported having problems using the `grpcurl` utility with a Helidon gRPC app.

One reported that the `grpcurl` `list` subcommand returned an error. It turns out that Helidon's gRPC implementation does not support that operation.

But another user reported problems accessing the gRPC endpoint in his app and then in the Helidon example app.

## Steps to reproduce
1. Build and run the Helidon gRPC example app. The tests, which include using the Helidon WebClient to access the server, work correctly.
2. Run `grpcurl -d '{"text":"hi"}' --insecure -vv   localhost:8080 StringService/Upper` 

The result is
```list
Error invoking method "StringService/Upper": rpc error: code = Internal desc = failed to query for service descriptor "StringService": malformed header: missing HTTP status; malformed header: missing HTTP content-type
```

**Comment by spericas** [comment]
@tjquinno The following command works, specifying the proto file:

```
>> grpcurl -d '{ "text": "hello" }' -vv -proto src/main/proto/strings.proto -insecure localhost:8080 StringService/Upper

Resolved method descriptor:
rpc Upper ( .StringMessage ) returns ( .StringMessage );

Request metadata to send:
(empty)

Response headers received:
content-type: application/grpc

Estimated response size: 7 bytes

Response contents:
{
  "text": "HELLO"
}

Response trailers received:
(empty)
Sent 1 request and received 1 response
Timing Data: 45.130541ms
  Dial: 42.511583ms
    TLS Setup: 6.125µs
    BlockingDial: 42.479667ms
  InvokeRPC: 1.708834ms

```

**Comment by DaveO-Home** [comment]
@spericas @tjquinno 
This should work without the local proto file. I've done the same `grpcurl query` with other frameworks that work without the proto parameter. For remote clients, the proto needs to be resolved on the server.

**Comment by spericas** [comment]
@DaveO-Home Understood, we don't have query support at this time. We should convert this issue into a feature request for that.

**Comment by DaveO-Home** [comment]
@spericas Are you saying that `helidon grpc` only supports a `java` client running on the server?

**Comment by DaveO-Home** [comment]
Added issue: #9452

**Comment by spericas** [comment]
> @spericas Are you saying that `helidon grpc` only supports a `java` client running on the server? It's interesting that my `javascript` client can execute a request but `helidon grpc` fails to respond.

Is your Javascript client assuming dynamic resolution of the proto file? I see that you created another issue, we can continue the discussion there then.
