### ISSUE TITLE
MicroProfile Rest Client - Support wildcard in URL/URI properties key 

### ISSUE THREAD

**Issue by tvallin** [helidon-io/helidon#9536]
## Environment Details
* Helidon Version: 4.x
* Helidon MP
* JDK version: 21
* OS: n/a
* Docker version (if applicable): n/a

----------

## Problem Description

Currently, Helidon users can set URL by setting `$restClient/mp-rest/url` property where `restClient` is the client alias or the class name.

[The spec](https://download.eclipse.org/microprofile/microprofile-rest-client-3.0/microprofile-rest-client-spec-3.0.html#mpconfig) mentions `*/mp-rest/url` property to set the client `baseUrl` and we currently don't support it.
It is not required so this issue is an enhancement proposal.

_(Same applies for URI)_

## Steps to reproduce

Example of how it could looks like from the MP quickstart:

Add a rest client

```java
@Path("/greet")
@RegisterRestClient(configKey="client", baseUri = "http://localhost:8080")
public interface MyRestClient {

    @GET
    GreetingMessage getDefaultMessage();
}
```

Add this test class 

```java
@HelidonTest
@AddConfig(key = "*/mp-rest/url", value = "http://localhost:8000")
public class MpRestClientConfigTest {

    @Inject
    @RestClient
    MyRestClient client;

    @Test
    void test() {
        client.getDefaultMessage();
    }

}
```

**Comment by spericas** [comment]
The spec seems to mention the use of "*" in an informal not formal context, simply to refer to _any prefix_ (in fact it is just mentioned twice in that paragraph). The requirement to support this in Config does not make sense and seems like a misinterpretation.

**Comment by tomas-langer** [comment]
The requested change would cause ALL endpoints in the whole system to call `localhost:8080`. And even though this may be desired for some scenarios, the concept of a configuration key that starts with asterisk is not something we want to implement and support.

You can use references in config, so if all of your clients point to the same service (or a small number of services), you can always do this based on references:

```
target-service.uri=http://localhost:8080
com.example.MyRestClient/mp-rest/url=${target-service.uri}
```

will do the trick without hacks with global overrides
