### ISSUE TITLE
OTEL Context not being propagated to @Asynchronous component

### ISSUE THREAD

**Issue by jvissers** [helidon-io/helidon#9538]
## Environment Details
* Helidon Version: 4.1.4
* Helidon MP
* OpenJDK 64-Bit Server VM (build 23+37-2369, mixed mode, sharing)
* OS: Ubuntu 24.04.1 LTS
----------

## Problem Description
We want to propagate OpenTelemetry context to an `@Asynchronous` component, but it looks like no context is propagated. `Span.current()` reports `Optional.empty()`.

**Comment by danielkec** [comment]
Confirmed, MP Async has one default Helidon context unaware executor which can't be configured in MP.
https://github.com/helidon-io/helidon/blob/c4860f15cc8c34b5a741e7b6d171973570452a7e/fault-tolerance/fault-tolerance/src/main/java/io/helidon/faulttolerance/FaultTolerance.java#L56-L60
