### ISSUE TITLE
HTTP2 FlowControl Window depleted

### ISSUE THREAD

**Issue by AlfredoG87** [helidon-io/helidon#9589]
Given several minutes streaming data to a client, Helidon 4.x Http2 Outbound Flow Control always ends up with a negative `remainingWindowSize` and the thread will remain trapped in an infinite loop waiting for `WINDOW_UPDATE`s from the client

This happens on an outbound grpc stream, for easy replication we modified one of your examples for a gRPC WebServer with the following [changes](https://github.com/AlfredoG87/helidon-examples/commit/99f071b73be38fef0b3260d1f0191f418c0c19c2).

1. The Split stream will stream the first word indefinitively.
2. We commented out the test for such method, since we changed the behaviour of the method to showcase the bug.

You can see the full source code here --> https://github.com/AlfredoG87/helidon-examples/tree/helidon-4.x/examples/webserver/grpc

## Environment Details
* Helidon Version: 4.1.4
* Helidon SE 
* JDK version: 21
* OS: MacOs

----------

## Problem Description

The WebServer (gRPC) stops streaming after a short amount of time.

Does not appears to happen always in the same way, sometimes it takes longer to happen, but does always happens, only precondition is for outbound stream messages to be large and sustained.

You can see a video showing how the window size becomes negative, never recovers and the server stops streaming on the attached video.

https://github.com/user-attachments/assets/3afd9493-d9ce-4515-acfc-9f1d1be5395f

![image](https://github.com/user-attachments/assets/bdc28d9f-072e-4c42-9bd9-c90d58b0d999)

## Steps to reproduce

Fork the following project: https://github.com/AlfredoG87/helidon-examples/tree/helidon-4.x/examples/webserver/grpc

Or apply the following [commit](https://github.com/AlfredoG87/helidon-examples/commit/99f071b73be38fef0b3260d1f0191f418c0c19c2) or changes to your own copy of `helidon-examples` repo. 

Run application, consume `Split` method with at least 2 words as input, the first one a large amount of lenght.

**Comment by danielkec** [comment]
Hi, @AlfredoG87, can you please share what client you have used for the step:
`consume Split method with at least 2 words as input, the first one a large amount of lenght.` ?

**Comment by AlfredoG87** [comment]
> Hi, @AlfredoG87, can you please share what client you have used for the step: `consume Split method with at least 2 words as input, the first one a large amount of lenght.` ?

In the video shared you can see I used `Postman` however we have also encountered this issue with `grpcurl` and `netty shade`

**Comment by danielkec** [comment]
Sorry I can't download the video

**Comment by AlfredoG87** [comment]
> Sorry I can't download the video

np, let me know if you know any more info. should be really straight forward to replicate. do you want me to convert the video to a gif or something else?

**Comment by danielkec** [comment]
I can reproduce it now with postman, thx for the video. Good news is that it is already fixed by #9520 (splitting large frames) issue. Bad news is it is not released yet.

**Comment by AlfredoG87** [comment]
> > Sorry I can't download the video
> 
> np, let me know if you know any more info. should be really straight forward to replicate. do you want me to convert the video to a gif or something else?

ohh no worries, just knowing that is already fixed is great news!! 💯 

just to plan accordingly, do you have an approximate ETA of when we can see that fix released?

Lastly, want me to close the issue?

**Comment by danielkec** [comment]
Keep it open, I have added it to 4.2.0 milestone, and we will consult internally if we can release 4.1.x bugfix earlier

**Comment by AlfredoG87** [comment]
> Any chance you could try out the fix from a snapshot build?

Yes, I can, can you provide the link to the snapshot build? please

**Comment by danielkec** [comment]
I don't think we have such snapshot build(4.2.0-SNAPSHOT), but it should be easy to build with JDK21+ 
```sh
cd /tmp && git clone git@github.com:helidon-io/helidon.git && cd helidon && mvn install -DskipTests
```

**Comment by AlfredoG87** [comment]
> I don't think we have such snapshot build(4.2.0-SNAPSHOT), but it should be easy to build with JDK21+

Perfect, I can manage that!

**Comment by mattp-swirldslabs** [comment]
Hi @danielkec, I've been working with @AlfredoG87 to troubleshoot this issue on our side. I was able to confirm the inbound fixes in `4.2.0-SNAPSHOT` with our server implementation. Thanks for pointing us to that PR and for all the changes. This helps unblock our project. :) We're eagerly awaiting `4.2.0`!

**Comment by AlfredoG87** [comment]
@danielkec Thank you for your help!! 💯

**Comment by AlfredoG87** [comment]
@m0mus just one question, has this already been release? 4.1.5 or when is it scheduled to be released in 4.1.6?

**Comment by danielkec** [comment]
Hi, sorry for not notifying you earlier. It will be part of [4.1.6](https://github.com/helidon-io/helidon/milestone/114) possibly tomorrow

**Comment by AlfredoG87** [comment]
No problem, I just asked since saw it was closed! 👍 
TYVM
